// AUTO-GENERATED by scripts/generate-city-facts.mjs — do not edit by hand.
// Re-run `node scripts/generate-city-facts.mjs` after editing the seed data.
// Compact per-city facts; full page content is expanded at runtime by
// client/src/data/serviceAreaGenerator.ts.

export type CityTier = "facility" | "nearby" | "onsite";
export type FacilitySlug = "san-diego" | "las-vegas" | "fresno";
export type RegionGroup = "southern-california" | "central-california" | "southern-nevada";

export interface CityFacts {
  slug: string;
  name: string;
  kind: "city" | "district";
  parentCity?: string;
  state: string;
  stateAbbrev: string;
  county: string;
  region: string;
  regionGroup: RegionGroup;
  population: number;
  zipPrefixes: string[];
  landmark: string;
  industries: string[];
  nearby: string[];
  tier: CityTier;
  facility: FacilitySlug;
  driveMinutes: number;
}

export const CITY_FACTS: CityFacts[] = [
  {
    "slug": "san-diego",
    "name": "San Diego",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 1386000,
    "zipPrefixes": [
      "921",
      "920",
      "919"
    ],
    "landmark": "the Port of San Diego",
    "industries": [
      "portLogistics",
      "defense",
      "biotech",
      "warehousing",
      "construction"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 15,
    "nearby": [
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "chula-vista",
    "name": "Chula Vista",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 275000,
    "zipPrefixes": [
      "919"
    ],
    "landmark": "the Chula Vista Bayfront",
    "industries": [
      "warehousing",
      "construction",
      "manufacturing",
      "logistics"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 25,
    "nearby": [
      "San Diego",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "oceanside",
    "name": "Oceanside",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 172000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "Oceanside Harbor",
    "industries": [
      "manufacturing",
      "construction",
      "logistics",
      "defense"
    ],
    "tier": "nearby",
    "facility": "san-diego",
    "driveMinutes": 40,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "escondido",
    "name": "Escondido",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 151000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "the North County industrial corridor",
    "industries": [
      "manufacturing",
      "construction",
      "agriculture",
      "warehousing"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 30,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "carlsbad",
    "name": "Carlsbad",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 115000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "the Palomar Airport business park",
    "industries": [
      "biotech",
      "manufacturing",
      "ecommerce",
      "warehousing"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 30,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "el-cajon",
    "name": "El Cajon",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 106000,
    "zipPrefixes": [
      "920",
      "919"
    ],
    "landmark": "Gillespie Field",
    "industries": [
      "manufacturing",
      "construction",
      "warehousing",
      "retail"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 25,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "vista",
    "name": "Vista",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 98000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "the Vista Business Park",
    "industries": [
      "manufacturing",
      "foodProcessing",
      "warehousing",
      "construction"
    ],
    "tier": "nearby",
    "facility": "san-diego",
    "driveMinutes": 35,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "San Marcos",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "san-marcos",
    "name": "San Marcos",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 94000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "Cal State San Marcos",
    "industries": [
      "manufacturing",
      "buildingMaterials",
      "warehousing",
      "construction"
    ],
    "tier": "nearby",
    "facility": "san-diego",
    "driveMinutes": 35,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "Mira Mesa",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "national-city",
    "name": "National City",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 56000,
    "zipPrefixes": [
      "919"
    ],
    "landmark": "the National City Marine Terminal",
    "industries": [
      "portLogistics",
      "warehousing",
      "logistics",
      "manufacturing"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 20,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "la-mesa",
    "name": "La Mesa",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 61000,
    "zipPrefixes": [
      "919",
      "920"
    ],
    "landmark": "Grossmont Center",
    "industries": [
      "retail",
      "construction",
      "warehousing",
      "logistics"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 20,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "spring-valley",
    "name": "Spring Valley",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 60000,
    "zipPrefixes": [
      "919"
    ],
    "landmark": "the Sweetwater Reservoir area",
    "industries": [
      "construction",
      "warehousing",
      "retail",
      "logistics"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 25,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "lemon-grove",
    "name": "Lemon Grove",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 27000,
    "zipPrefixes": [
      "919"
    ],
    "landmark": "the Lemon Grove trolley depot",
    "industries": [
      "warehousing",
      "construction",
      "manufacturing",
      "logistics"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 22,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "imperial-beach",
    "name": "Imperial Beach",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 26000,
    "zipPrefixes": [
      "919"
    ],
    "landmark": "the Imperial Beach Pier",
    "industries": [
      "construction",
      "hospitality",
      "logistics",
      "warehousing"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 30,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "santee",
    "name": "Santee",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 60000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "Santee Trolley Square",
    "industries": [
      "construction",
      "manufacturing",
      "warehousing",
      "retail"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 25,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "poway",
    "name": "Poway",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 48000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "the Poway Business Park",
    "industries": [
      "manufacturing",
      "aerospace",
      "warehousing",
      "biotech"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 20,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "encinitas",
    "name": "Encinitas",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 61000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "Moonlight Beach",
    "industries": [
      "agriculture",
      "construction",
      "retail",
      "hospitality"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 25,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "solana-beach",
    "name": "Solana Beach",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 12000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "the Cedros Design District",
    "industries": [
      "retail",
      "construction",
      "hospitality",
      "logistics"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 20,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "cardiff",
    "name": "Cardiff",
    "kind": "district",
    "parentCity": "Encinitas",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 12000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "Cardiff State Beach",
    "industries": [
      "construction",
      "retail",
      "hospitality",
      "agriculture"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 25,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "la-jolla",
    "name": "La Jolla",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 46000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "UC San Diego",
    "industries": [
      "biotech",
      "hospitality",
      "retail",
      "construction"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 15,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "mira-mesa",
    "name": "Mira Mesa",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 74000,
    "zipPrefixes": [
      "921"
    ],
    "landmark": "the Mira Mesa tech corridor",
    "industries": [
      "biotech",
      "manufacturing",
      "warehousing",
      "ecommerce"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 5,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "La Mesa",
      "Encinitas"
    ]
  },
  {
    "slug": "kearny-mesa",
    "name": "Kearny Mesa",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 22000,
    "zipPrefixes": [
      "921"
    ],
    "landmark": "Montgomery Field",
    "industries": [
      "manufacturing",
      "logistics",
      "warehousing",
      "defense"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 10,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "miramar",
    "name": "Miramar",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 15000,
    "zipPrefixes": [
      "921"
    ],
    "landmark": "MCAS Miramar",
    "industries": [
      "defense",
      "warehousing",
      "logistics",
      "manufacturing"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 5,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "sorrento-valley",
    "name": "Sorrento Valley",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 10000,
    "zipPrefixes": [
      "921"
    ],
    "landmark": "the Sorrento Valley biotech cluster",
    "industries": [
      "biotech",
      "manufacturing",
      "ecommerce",
      "warehousing"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 10,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "otay-mesa",
    "name": "Otay Mesa",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 20000,
    "zipPrefixes": [
      "921",
      "919"
    ],
    "landmark": "the Otay Mesa Port of Entry",
    "industries": [
      "logistics",
      "warehousing",
      "manufacturing",
      "portLogistics"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 30,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "san-ysidro",
    "name": "San Ysidro",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 28000,
    "zipPrefixes": [
      "921"
    ],
    "landmark": "the San Ysidro border crossing",
    "industries": [
      "logistics",
      "warehousing",
      "retail",
      "construction"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 30,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "rancho-bernardo",
    "name": "Rancho Bernardo",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 50000,
    "zipPrefixes": [
      "921"
    ],
    "landmark": "the Rancho Bernardo tech campuses",
    "industries": [
      "manufacturing",
      "biotech",
      "warehousing",
      "ecommerce"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 18,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "carmel-valley",
    "name": "Carmel Valley",
    "kind": "district",
    "parentCity": "San Diego",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 45000,
    "zipPrefixes": [
      "921"
    ],
    "landmark": "the Del Mar Heights corridor",
    "industries": [
      "biotech",
      "retail",
      "construction",
      "hospitality"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 12,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "del-mar",
    "name": "Del Mar",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Diego County",
    "region": "San Diego County",
    "regionGroup": "southern-california",
    "population": 4000,
    "zipPrefixes": [
      "920"
    ],
    "landmark": "the Del Mar Fairgrounds",
    "industries": [
      "hospitality",
      "retail",
      "construction",
      "logistics"
    ],
    "tier": "facility",
    "facility": "san-diego",
    "driveMinutes": 15,
    "nearby": [
      "San Diego",
      "Chula Vista",
      "Oceanside",
      "Escondido",
      "Carlsbad",
      "El Cajon",
      "Vista",
      "San Marcos",
      "Mira Mesa",
      "La Mesa"
    ]
  },
  {
    "slug": "temecula",
    "name": "Temecula",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Riverside County",
    "region": "Southwest Riverside County",
    "regionGroup": "southern-california",
    "population": 110000,
    "zipPrefixes": [
      "925"
    ],
    "landmark": "Temecula Wine Country",
    "industries": [
      "warehousing",
      "manufacturing",
      "logistics",
      "construction"
    ],
    "tier": "nearby",
    "facility": "san-diego",
    "driveMinutes": 55,
    "nearby": [
      "Riverside",
      "Moreno Valley",
      "Corona",
      "Murrieta",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "murrieta",
    "name": "Murrieta",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Riverside County",
    "region": "Southwest Riverside County",
    "regionGroup": "southern-california",
    "population": 118000,
    "zipPrefixes": [
      "925"
    ],
    "landmark": "the Golden Triangle",
    "industries": [
      "logistics",
      "construction",
      "warehousing",
      "retail"
    ],
    "tier": "nearby",
    "facility": "san-diego",
    "driveMinutes": 60,
    "nearby": [
      "Riverside",
      "Moreno Valley",
      "Corona",
      "Temecula",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "long-beach",
    "name": "Long Beach",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 466000,
    "zipPrefixes": [
      "908",
      "907"
    ],
    "landmark": "the Port of Long Beach",
    "industries": [
      "portLogistics",
      "logistics",
      "manufacturing",
      "warehousing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "torrance",
    "name": "Torrance",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 147000,
    "zipPrefixes": [
      "905"
    ],
    "landmark": "the Torrance refinery corridor",
    "industries": [
      "manufacturing",
      "aerospace",
      "logistics",
      "warehousing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 110,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Pasadena",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "compton",
    "name": "Compton",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 95000,
    "zipPrefixes": [
      "902"
    ],
    "landmark": "the Compton rail yards",
    "industries": [
      "warehousing",
      "logistics",
      "manufacturing",
      "foodProcessing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "inglewood",
    "name": "Inglewood",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 108000,
    "zipPrefixes": [
      "903"
    ],
    "landmark": "SoFi Stadium",
    "industries": [
      "logistics",
      "construction",
      "warehousing",
      "hospitality"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 115,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "downey",
    "name": "Downey",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 114000,
    "zipPrefixes": [
      "902"
    ],
    "landmark": "the Downey industrial corridor",
    "industries": [
      "manufacturing",
      "warehousing",
      "foodProcessing",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 100,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "norwalk",
    "name": "Norwalk",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 103000,
    "zipPrefixes": [
      "906"
    ],
    "landmark": "the Santa Fe Springs industrial belt",
    "industries": [
      "warehousing",
      "logistics",
      "manufacturing",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "whittier",
    "name": "Whittier",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 87000,
    "zipPrefixes": [
      "906"
    ],
    "landmark": "the Whittier Boulevard corridor",
    "industries": [
      "warehousing",
      "construction",
      "foodProcessing",
      "retail"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 100,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "pomona",
    "name": "Pomona",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 151000,
    "zipPrefixes": [
      "917"
    ],
    "landmark": "the Fairplex",
    "industries": [
      "warehousing",
      "logistics",
      "manufacturing",
      "agriculture"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "pasadena",
    "name": "Pasadena",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 138000,
    "zipPrefixes": [
      "911"
    ],
    "landmark": "the Rose Bowl",
    "industries": [
      "construction",
      "biotech",
      "retail",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 120,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "glendale",
    "name": "Glendale",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 197000,
    "zipPrefixes": [
      "912"
    ],
    "landmark": "the Grand Central Creative Campus",
    "industries": [
      "manufacturing",
      "retail",
      "construction",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 120,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "burbank",
    "name": "Burbank",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 107000,
    "zipPrefixes": [
      "915"
    ],
    "landmark": "Hollywood Burbank Airport",
    "industries": [
      "logistics",
      "manufacturing",
      "hospitality",
      "warehousing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 125,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "santa-clarita",
    "name": "Santa Clarita",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 228000,
    "zipPrefixes": [
      "913"
    ],
    "landmark": "the Valencia Industrial Center",
    "industries": [
      "warehousing",
      "manufacturing",
      "logistics",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 140,
    "nearby": [
      "Long Beach",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "el-monte",
    "name": "El Monte",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 109000,
    "zipPrefixes": [
      "917"
    ],
    "landmark": "the El Monte industrial district",
    "industries": [
      "manufacturing",
      "warehousing",
      "foodProcessing",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 110,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "West Covina"
    ]
  },
  {
    "slug": "west-covina",
    "name": "West Covina",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 109000,
    "zipPrefixes": [
      "917"
    ],
    "landmark": "the West Covina retail corridor",
    "industries": [
      "retail",
      "warehousing",
      "construction",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "carson",
    "name": "Carson",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 95000,
    "zipPrefixes": [
      "907"
    ],
    "landmark": "the Carson port and refinery corridor",
    "industries": [
      "portLogistics",
      "warehousing",
      "logistics",
      "energy"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "santa-fe-springs",
    "name": "Santa Fe Springs",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 19000,
    "zipPrefixes": [
      "906"
    ],
    "landmark": "the Santa Fe Springs industrial district",
    "industries": [
      "warehousing",
      "manufacturing",
      "logistics",
      "foodProcessing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 100,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "vernon",
    "name": "Vernon",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 3000,
    "zipPrefixes": [
      "900"
    ],
    "landmark": "the Vernon industrial district",
    "industries": [
      "foodProcessing",
      "coldStorage",
      "warehousing",
      "manufacturing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 110,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "city-of-industry",
    "name": "City of Industry",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 4000,
    "zipPrefixes": [
      "917"
    ],
    "landmark": "the City of Industry rail hub",
    "industries": [
      "warehousing",
      "logistics",
      "manufacturing",
      "ecommerce"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "cerritos",
    "name": "Cerritos",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Greater Los Angeles",
    "regionGroup": "southern-california",
    "population": 49000,
    "zipPrefixes": [
      "907"
    ],
    "landmark": "the Cerritos Auto Square",
    "industries": [
      "warehousing",
      "retail",
      "logistics",
      "manufacturing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte"
    ]
  },
  {
    "slug": "lancaster",
    "name": "Lancaster",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Antelope Valley",
    "regionGroup": "southern-california",
    "population": 173000,
    "zipPrefixes": [
      "935"
    ],
    "landmark": "the Lancaster aerospace corridor",
    "industries": [
      "aerospace",
      "defense",
      "energy",
      "warehousing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 165,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Palmdale",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "palmdale",
    "name": "Palmdale",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Los Angeles County",
    "region": "Antelope Valley",
    "regionGroup": "southern-california",
    "population": 169000,
    "zipPrefixes": [
      "935"
    ],
    "landmark": "Air Force Plant 42",
    "industries": [
      "aerospace",
      "defense",
      "manufacturing",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 160,
    "nearby": [
      "Long Beach",
      "Santa Clarita",
      "Glendale",
      "Lancaster",
      "Pomona",
      "Torrance",
      "Pasadena",
      "Downey",
      "El Monte",
      "West Covina"
    ]
  },
  {
    "slug": "anaheim",
    "name": "Anaheim",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 346000,
    "zipPrefixes": [
      "928"
    ],
    "landmark": "Angel Stadium",
    "industries": [
      "hospitality",
      "manufacturing",
      "warehousing",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "irvine",
    "name": "Irvine",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 314000,
    "zipPrefixes": [
      "926"
    ],
    "landmark": "the Irvine Spectrum",
    "industries": [
      "biotech",
      "manufacturing",
      "ecommerce",
      "warehousing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 80,
    "nearby": [
      "Anaheim",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "santa-ana",
    "name": "Santa Ana",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 310000,
    "zipPrefixes": [
      "927"
    ],
    "landmark": "downtown Santa Ana",
    "industries": [
      "manufacturing",
      "warehousing",
      "construction",
      "foodProcessing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 90,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "huntington-beach",
    "name": "Huntington Beach",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 197000,
    "zipPrefixes": [
      "926"
    ],
    "landmark": "the Huntington Beach Pier",
    "industries": [
      "aerospace",
      "manufacturing",
      "construction",
      "hospitality"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "garden-grove",
    "name": "Garden Grove",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 171000,
    "zipPrefixes": [
      "928"
    ],
    "landmark": "the Garden Grove industrial corridor",
    "industries": [
      "manufacturing",
      "warehousing",
      "logistics",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "costa-mesa",
    "name": "Costa Mesa",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 111000,
    "zipPrefixes": [
      "926"
    ],
    "landmark": "South Coast Plaza",
    "industries": [
      "retail",
      "manufacturing",
      "construction",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 85,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "mission-viejo",
    "name": "Mission Viejo",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 93000,
    "zipPrefixes": [
      "926"
    ],
    "landmark": "the Saddleback Valley",
    "industries": [
      "retail",
      "construction",
      "logistics",
      "warehousing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 70,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "fullerton",
    "name": "Fullerton",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 143000,
    "zipPrefixes": [
      "928"
    ],
    "landmark": "the Fullerton Transportation Center",
    "industries": [
      "manufacturing",
      "foodProcessing",
      "warehousing",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "orange",
    "name": "Orange",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 139000,
    "zipPrefixes": [
      "928"
    ],
    "landmark": "the Orange Plaza Historic District",
    "industries": [
      "manufacturing",
      "construction",
      "warehousing",
      "retail"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 90,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park",
      "Tustin"
    ]
  },
  {
    "slug": "tustin",
    "name": "Tustin",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 80000,
    "zipPrefixes": [
      "927"
    ],
    "landmark": "the Tustin Legacy hangars",
    "industries": [
      "logistics",
      "warehousing",
      "construction",
      "manufacturing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 85,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Buena Park"
    ]
  },
  {
    "slug": "buena-park",
    "name": "Buena Park",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Orange County",
    "region": "Orange County",
    "regionGroup": "southern-california",
    "population": 84000,
    "zipPrefixes": [
      "906"
    ],
    "landmark": "Knott's Berry Farm",
    "industries": [
      "foodProcessing",
      "warehousing",
      "manufacturing",
      "hospitality"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Huntington Beach",
      "Garden Grove",
      "Fullerton",
      "Orange",
      "Costa Mesa",
      "Mission Viejo",
      "Tustin"
    ]
  },
  {
    "slug": "ontario",
    "name": "Ontario",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Bernardino County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 175000,
    "zipPrefixes": [
      "917"
    ],
    "landmark": "Ontario International Airport",
    "industries": [
      "warehousing",
      "logistics",
      "ecommerce",
      "manufacturing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 100,
    "nearby": [
      "San Bernardino",
      "Fontana",
      "Rancho Cucamonga",
      "Chino",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana"
    ]
  },
  {
    "slug": "rancho-cucamonga",
    "name": "Rancho Cucamonga",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Bernardino County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 174000,
    "zipPrefixes": [
      "917"
    ],
    "landmark": "the Rancho Cucamonga logistics corridor",
    "industries": [
      "warehousing",
      "ecommerce",
      "logistics",
      "manufacturing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "San Bernardino",
      "Fontana",
      "Ontario",
      "Chino",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana"
    ]
  },
  {
    "slug": "fontana",
    "name": "Fontana",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Bernardino County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 208000,
    "zipPrefixes": [
      "923"
    ],
    "landmark": "the Fontana trucking corridor",
    "industries": [
      "warehousing",
      "logistics",
      "manufacturing",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 100,
    "nearby": [
      "San Bernardino",
      "Ontario",
      "Rancho Cucamonga",
      "Chino",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana"
    ]
  },
  {
    "slug": "san-bernardino",
    "name": "San Bernardino",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Bernardino County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 222000,
    "zipPrefixes": [
      "924"
    ],
    "landmark": "the San Bernardino rail yards",
    "industries": [
      "warehousing",
      "logistics",
      "manufacturing",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 105,
    "nearby": [
      "Fontana",
      "Ontario",
      "Rancho Cucamonga",
      "Chino",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana"
    ]
  },
  {
    "slug": "chino",
    "name": "Chino",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "San Bernardino County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 91000,
    "zipPrefixes": [
      "917"
    ],
    "landmark": "the Chino Airport industrial area",
    "industries": [
      "warehousing",
      "foodProcessing",
      "manufacturing",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 95,
    "nearby": [
      "San Bernardino",
      "Fontana",
      "Ontario",
      "Rancho Cucamonga",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana"
    ]
  },
  {
    "slug": "corona",
    "name": "Corona",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Riverside County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 157000,
    "zipPrefixes": [
      "928"
    ],
    "landmark": "the Corona industrial corridor",
    "industries": [
      "manufacturing",
      "warehousing",
      "logistics",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 85,
    "nearby": [
      "Riverside",
      "Moreno Valley",
      "Murrieta",
      "Temecula",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "riverside",
    "name": "Riverside",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Riverside County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 314000,
    "zipPrefixes": [
      "925"
    ],
    "landmark": "the Hunter Park industrial district",
    "industries": [
      "warehousing",
      "logistics",
      "manufacturing",
      "agriculture"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 90,
    "nearby": [
      "Moreno Valley",
      "Corona",
      "Murrieta",
      "Temecula",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "moreno-valley",
    "name": "Moreno Valley",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Riverside County",
    "region": "Inland Empire",
    "regionGroup": "southern-california",
    "population": 208000,
    "zipPrefixes": [
      "925"
    ],
    "landmark": "the World Logistics Center corridor",
    "industries": [
      "warehousing",
      "ecommerce",
      "logistics",
      "construction"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 85,
    "nearby": [
      "Riverside",
      "Corona",
      "Murrieta",
      "Temecula",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "oxnard",
    "name": "Oxnard",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Ventura County",
    "region": "Ventura County",
    "regionGroup": "southern-california",
    "population": 202000,
    "zipPrefixes": [
      "930"
    ],
    "landmark": "the Port of Hueneme",
    "industries": [
      "portLogistics",
      "agriculture",
      "foodProcessing",
      "warehousing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 175,
    "nearby": [
      "Thousand Oaks",
      "Simi Valley",
      "Ventura",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "ventura",
    "name": "Ventura",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Ventura County",
    "region": "Ventura County",
    "regionGroup": "southern-california",
    "population": 110000,
    "zipPrefixes": [
      "930"
    ],
    "landmark": "Ventura Harbor",
    "industries": [
      "agriculture",
      "energy",
      "construction",
      "manufacturing"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 170,
    "nearby": [
      "Oxnard",
      "Thousand Oaks",
      "Simi Valley",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "thousand-oaks",
    "name": "Thousand Oaks",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Ventura County",
    "region": "Ventura County",
    "regionGroup": "southern-california",
    "population": 126000,
    "zipPrefixes": [
      "913"
    ],
    "landmark": "the Conejo Valley biotech corridor",
    "industries": [
      "biotech",
      "manufacturing",
      "warehousing",
      "retail"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 155,
    "nearby": [
      "Oxnard",
      "Simi Valley",
      "Ventura",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "simi-valley",
    "name": "Simi Valley",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Ventura County",
    "region": "Ventura County",
    "regionGroup": "southern-california",
    "population": 126000,
    "zipPrefixes": [
      "930"
    ],
    "landmark": "the Ronald Reagan Presidential Library",
    "industries": [
      "manufacturing",
      "warehousing",
      "construction",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "san-diego",
    "driveMinutes": 160,
    "nearby": [
      "Oxnard",
      "Thousand Oaks",
      "Ventura",
      "San Diego",
      "Long Beach",
      "Anaheim",
      "Irvine",
      "Riverside",
      "Santa Ana",
      "Chula Vista"
    ]
  },
  {
    "slug": "fresno",
    "name": "Fresno",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Fresno County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 545000,
    "zipPrefixes": [
      "937",
      "936"
    ],
    "landmark": "the downtown Fresno rail corridor",
    "industries": [
      "agriculture",
      "foodProcessing",
      "warehousing",
      "logistics",
      "coldStorage"
    ],
    "tier": "facility",
    "facility": "fresno",
    "driveMinutes": 12,
    "nearby": [
      "Clovis",
      "Sanger",
      "Reedley",
      "Selma",
      "Kingsburg",
      "Visalia",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville"
    ]
  },
  {
    "slug": "clovis",
    "name": "Clovis",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Fresno County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 124000,
    "zipPrefixes": [
      "936"
    ],
    "landmark": "Old Town Clovis",
    "industries": [
      "construction",
      "manufacturing",
      "agriculture",
      "retail"
    ],
    "tier": "facility",
    "facility": "fresno",
    "driveMinutes": 15,
    "nearby": [
      "Fresno",
      "Sanger",
      "Reedley",
      "Selma",
      "Kingsburg",
      "Visalia",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville"
    ]
  },
  {
    "slug": "madera",
    "name": "Madera",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Madera County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 67000,
    "zipPrefixes": [
      "936"
    ],
    "landmark": "the Madera wine trail",
    "industries": [
      "agriculture",
      "foodProcessing",
      "manufacturing",
      "logistics"
    ],
    "tier": "facility",
    "facility": "fresno",
    "driveMinutes": 30,
    "nearby": [
      "Fresno",
      "Visalia",
      "Clovis",
      "Merced",
      "Tulare",
      "Porterville",
      "Hanford",
      "Delano",
      "Sanger",
      "Lemoore"
    ]
  },
  {
    "slug": "merced",
    "name": "Merced",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Merced County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 90000,
    "zipPrefixes": [
      "953"
    ],
    "landmark": "UC Merced",
    "industries": [
      "agriculture",
      "foodProcessing",
      "warehousing",
      "logistics"
    ],
    "tier": "nearby",
    "facility": "fresno",
    "driveMinutes": 55,
    "nearby": [
      "Fresno",
      "Visalia",
      "Clovis",
      "Tulare",
      "Madera",
      "Porterville",
      "Hanford",
      "Delano",
      "Sanger",
      "Lemoore"
    ]
  },
  {
    "slug": "visalia",
    "name": "Visalia",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Tulare County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 142000,
    "zipPrefixes": [
      "932"
    ],
    "landmark": "the Visalia Industrial Park",
    "industries": [
      "agriculture",
      "coldStorage",
      "warehousing",
      "logistics"
    ],
    "tier": "nearby",
    "facility": "fresno",
    "driveMinutes": 45,
    "nearby": [
      "Tulare",
      "Porterville",
      "Exeter",
      "Fresno",
      "Clovis",
      "Merced",
      "Madera",
      "Hanford",
      "Delano",
      "Sanger"
    ]
  },
  {
    "slug": "tulare",
    "name": "Tulare",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Tulare County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 70000,
    "zipPrefixes": [
      "932"
    ],
    "landmark": "the World Ag Expo grounds",
    "industries": [
      "agriculture",
      "foodProcessing",
      "coldStorage",
      "manufacturing"
    ],
    "tier": "nearby",
    "facility": "fresno",
    "driveMinutes": 55,
    "nearby": [
      "Visalia",
      "Porterville",
      "Exeter",
      "Fresno",
      "Clovis",
      "Merced",
      "Madera",
      "Hanford",
      "Delano",
      "Sanger"
    ]
  },
  {
    "slug": "porterville",
    "name": "Porterville",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Tulare County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 62000,
    "zipPrefixes": [
      "932"
    ],
    "landmark": "the Porterville citrus belt",
    "industries": [
      "agriculture",
      "foodProcessing",
      "warehousing",
      "construction"
    ],
    "tier": "onsite",
    "facility": "fresno",
    "driveMinutes": 70,
    "nearby": [
      "Visalia",
      "Tulare",
      "Exeter",
      "Fresno",
      "Clovis",
      "Merced",
      "Madera",
      "Hanford",
      "Delano",
      "Sanger"
    ]
  },
  {
    "slug": "hanford",
    "name": "Hanford",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Kings County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 58000,
    "zipPrefixes": [
      "932"
    ],
    "landmark": "downtown Hanford",
    "industries": [
      "agriculture",
      "foodProcessing",
      "manufacturing",
      "logistics"
    ],
    "tier": "nearby",
    "facility": "fresno",
    "driveMinutes": 40,
    "nearby": [
      "Lemoore",
      "Fresno",
      "Visalia",
      "Clovis",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville",
      "Delano",
      "Sanger"
    ]
  },
  {
    "slug": "delano",
    "name": "Delano",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Kern County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 52000,
    "zipPrefixes": [
      "932"
    ],
    "landmark": "the Delano table-grape packing district",
    "industries": [
      "agriculture",
      "coldStorage",
      "foodProcessing",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "fresno",
    "driveMinutes": 75,
    "nearby": [
      "Fresno",
      "Visalia",
      "Clovis",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville",
      "Hanford",
      "Sanger",
      "Lemoore"
    ]
  },
  {
    "slug": "selma",
    "name": "Selma",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Fresno County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 25000,
    "zipPrefixes": [
      "936"
    ],
    "landmark": "the Raisin Capital of the World",
    "industries": [
      "agriculture",
      "foodProcessing",
      "warehousing",
      "manufacturing"
    ],
    "tier": "facility",
    "facility": "fresno",
    "driveMinutes": 25,
    "nearby": [
      "Fresno",
      "Clovis",
      "Sanger",
      "Reedley",
      "Kingsburg",
      "Visalia",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville"
    ]
  },
  {
    "slug": "kingsburg",
    "name": "Kingsburg",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Fresno County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 13000,
    "zipPrefixes": [
      "936"
    ],
    "landmark": "the Kingsburg Swedish Village",
    "industries": [
      "agriculture",
      "foodProcessing",
      "manufacturing",
      "logistics"
    ],
    "tier": "facility",
    "facility": "fresno",
    "driveMinutes": 30,
    "nearby": [
      "Fresno",
      "Clovis",
      "Sanger",
      "Reedley",
      "Selma",
      "Visalia",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville"
    ]
  },
  {
    "slug": "reedley",
    "name": "Reedley",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Fresno County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 26000,
    "zipPrefixes": [
      "936"
    ],
    "landmark": "the Reedley fruit-packing district",
    "industries": [
      "agriculture",
      "foodProcessing",
      "coldStorage",
      "warehousing"
    ],
    "tier": "nearby",
    "facility": "fresno",
    "driveMinutes": 35,
    "nearby": [
      "Fresno",
      "Clovis",
      "Sanger",
      "Selma",
      "Kingsburg",
      "Visalia",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville"
    ]
  },
  {
    "slug": "sanger",
    "name": "Sanger",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Fresno County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 27000,
    "zipPrefixes": [
      "936"
    ],
    "landmark": "the Sanger depot district",
    "industries": [
      "agriculture",
      "foodProcessing",
      "warehousing",
      "manufacturing"
    ],
    "tier": "facility",
    "facility": "fresno",
    "driveMinutes": 25,
    "nearby": [
      "Fresno",
      "Clovis",
      "Reedley",
      "Selma",
      "Kingsburg",
      "Visalia",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville"
    ]
  },
  {
    "slug": "lemoore",
    "name": "Lemoore",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Kings County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 27000,
    "zipPrefixes": [
      "932"
    ],
    "landmark": "NAS Lemoore",
    "industries": [
      "defense",
      "agriculture",
      "foodProcessing",
      "logistics"
    ],
    "tier": "nearby",
    "facility": "fresno",
    "driveMinutes": 50,
    "nearby": [
      "Hanford",
      "Fresno",
      "Visalia",
      "Clovis",
      "Merced",
      "Tulare",
      "Madera",
      "Porterville",
      "Delano",
      "Sanger"
    ]
  },
  {
    "slug": "exeter",
    "name": "Exeter",
    "kind": "city",
    "state": "California",
    "stateAbbrev": "CA",
    "county": "Tulare County",
    "region": "Central Valley",
    "regionGroup": "central-california",
    "population": 10000,
    "zipPrefixes": [
      "932"
    ],
    "landmark": "the Exeter citrus murals",
    "industries": [
      "agriculture",
      "foodProcessing",
      "warehousing",
      "construction"
    ],
    "tier": "nearby",
    "facility": "fresno",
    "driveMinutes": 55,
    "nearby": [
      "Visalia",
      "Tulare",
      "Porterville",
      "Fresno",
      "Clovis",
      "Merced",
      "Madera",
      "Hanford",
      "Delano",
      "Sanger"
    ]
  },
  {
    "slug": "las-vegas",
    "name": "Las Vegas",
    "kind": "city",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 660000,
    "zipPrefixes": [
      "891",
      "890"
    ],
    "landmark": "the Las Vegas Strip",
    "industries": [
      "hospitality",
      "warehousing",
      "construction",
      "logistics",
      "ecommerce"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 15,
    "nearby": [
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "henderson",
    "name": "Henderson",
    "kind": "city",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 330000,
    "zipPrefixes": [
      "890"
    ],
    "landmark": "the Henderson Executive Airport industrial area",
    "industries": [
      "manufacturing",
      "warehousing",
      "logistics",
      "construction"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 25,
    "nearby": [
      "Las Vegas",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "north-las-vegas",
    "name": "North Las Vegas",
    "kind": "city",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 280000,
    "zipPrefixes": [
      "890"
    ],
    "landmark": "the Apex Industrial Park",
    "industries": [
      "warehousing",
      "ecommerce",
      "logistics",
      "manufacturing"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 20,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "boulder-city",
    "name": "Boulder City",
    "kind": "city",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 15000,
    "zipPrefixes": [
      "890"
    ],
    "landmark": "the Hoover Dam",
    "industries": [
      "energy",
      "construction",
      "hospitality",
      "logistics"
    ],
    "tier": "nearby",
    "facility": "las-vegas",
    "driveMinutes": 35,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester"
    ]
  },
  {
    "slug": "mesquite",
    "name": "Mesquite",
    "kind": "city",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 22000,
    "zipPrefixes": [
      "890"
    ],
    "landmark": "the Mesquite resort corridor",
    "industries": [
      "hospitality",
      "construction",
      "warehousing",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "las-vegas",
    "driveMinutes": 80,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester"
    ]
  },
  {
    "slug": "pahrump",
    "name": "Pahrump",
    "kind": "city",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Nye County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 45000,
    "zipPrefixes": [
      "890"
    ],
    "landmark": "the Pahrump Valley wineries",
    "industries": [
      "construction",
      "agriculture",
      "retail",
      "logistics"
    ],
    "tier": "onsite",
    "facility": "las-vegas",
    "driveMinutes": 65,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester"
    ]
  },
  {
    "slug": "spring-valley-nv",
    "name": "Spring Valley",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 220000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "Desert Breeze Park",
    "industries": [
      "retail",
      "hospitality",
      "construction",
      "warehousing"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 10,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "summerlin",
    "name": "Summerlin",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 120000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "Downtown Summerlin",
    "industries": [
      "construction",
      "retail",
      "hospitality",
      "logistics"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 25,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "enterprise",
    "name": "Enterprise",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 230000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "the south Las Vegas Boulevard corridor",
    "industries": [
      "warehousing",
      "logistics",
      "ecommerce",
      "construction"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 10,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "sunrise-manor",
    "name": "Sunrise Manor",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 205000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "the Nellis Boulevard corridor",
    "industries": [
      "construction",
      "warehousing",
      "retail",
      "logistics"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 25,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "paradise",
    "name": "Paradise",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 190000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "Harry Reid International Airport",
    "industries": [
      "hospitality",
      "logistics",
      "warehousing",
      "construction"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 10,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Summerlin",
      "Whitney",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "winchester",
    "name": "Winchester",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 36000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "the Las Vegas Convention Center",
    "industries": [
      "hospitality",
      "construction",
      "logistics",
      "retail"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 15,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Mesquite"
    ]
  },
  {
    "slug": "whitney",
    "name": "Whitney",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 46000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "the Boulder Highway corridor",
    "industries": [
      "construction",
      "warehousing",
      "retail",
      "logistics"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 20,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Winchester",
      "Mesquite"
    ]
  },
  {
    "slug": "nellis-afb",
    "name": "Nellis AFB Area",
    "kind": "district",
    "parentCity": "Las Vegas",
    "state": "Nevada",
    "stateAbbrev": "NV",
    "county": "Clark County",
    "region": "Las Vegas Valley",
    "regionGroup": "southern-nevada",
    "population": 3000,
    "zipPrefixes": [
      "891"
    ],
    "landmark": "Nellis Air Force Base",
    "industries": [
      "defense",
      "logistics",
      "construction",
      "warehousing"
    ],
    "tier": "facility",
    "facility": "las-vegas",
    "driveMinutes": 25,
    "nearby": [
      "Las Vegas",
      "Henderson",
      "North Las Vegas",
      "Enterprise",
      "Spring Valley",
      "Sunrise Manor",
      "Paradise",
      "Summerlin",
      "Whitney",
      "Winchester"
    ]
  }
];

export const GENERATED_CITY_SLUGS: string[] = CITY_FACTS.map((c) => c.slug);
