import type { LessonBlock } from "@shared/lesson-blocks";

export interface StepDef {
  title: string;
  type: "lesson" | "video" | "checkpoint" | "download" | "exam" | "content";
  config: any;
  estimatedMinutes: number;
  module: string;
  questions?: QuestionDef[];
}

export interface QuestionDef {
  question: string;
  type: "mcq_single" | "mcq_multi";
  options: string[];
  correctAnswers: string;
  explanation: string;
}

export const CANONICAL_COURSE = {
  title: "Aerial & Scissor Lift Operator Certification",
  slug: "online-aerial-scissor-lift-certification",
  description: "Comprehensive OSHA-compliant aerial lift and scissor lift operator training. Covers OSHA 29 CFR 1926.453 and ANSI/SAIA A92 standards. Includes formal instruction on equipment types, pre-operation inspection, fall protection, stability, safe operation, workplace hazards, and emergency procedures. Note: OSHA also requires employer-conducted practical training and evaluation on the specific equipment.",
  category: "aerial",
  price: "59.00",
};

const img = (name: string) => `/images/training/${name}`;

const blocks = (b: LessonBlock[]) => ({ blocks: b });

export const COURSE_STEPS: StepDef[] = [
  // ═══ MODULE 0: Welcome + OSHA/ANSI Compliance ═══
  {
    module: "Welcome & OSHA/ANSI Compliance",
    title: "Welcome to Aerial & Scissor Lift Certification",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "Welcome to Aerial & Scissor Lift Certification" },
      { type: "heading", level: 2, text: "Welcome to Aerial & Scissor Lift Certification" },
      { type: "heading", level: 3, text: "About This Course" },
      { type: "paragraph", html: "Welcome! This online course provides the <strong>formal instruction</strong> portion of OSHA-compliant aerial lift and scissor lift operator certification. The course takes approximately <strong>60-90 minutes</strong> to complete." },
      { type: "heading", level: 3, text: "What's Included" },
      { type: "list", items: [
        "Interactive training modules covering all OSHA and ANSI-required topics",
        "Knowledge check quizzes throughout",
        "Final certification exam (80% passing score)",
        "Digital certificate with QR-verified credential",
        "Employer documentation packet for practical evaluation",
      ] },
      { type: "heading", level: 3, text: "What's NOT Included" },
      { type: "paragraph", html: "OSHA and ANSI require <strong>multiple components</strong> for full certification: (1) formal instruction (this course), (2) hands-on practical training on the specific equipment, and (3) an evaluation of operator performance. Your employer must conduct the hands-on portion at your worksite." },
      { type: "heading", level: 3, text: "How to Navigate" },
      { type: "paragraph", html: "Complete each step in order. You can track your progress using the sidebar. If you need to stop, your progress is saved automatically. You can retake the final exam up to 3 times." },
      { type: "callout", variant: "tip", text: "Look out for interactive diagrams, flip cards, and scenarios throughout the course — they are the fastest way to lock in what you learn." },
      { type: "key_takeaways", items: [
        "This course covers the formal instruction requirement",
        "Your employer must also conduct hands-on training and evaluation",
        "Complete all modules and pass the final exam at 80% or higher",
        "Your progress saves automatically — resume anytime",
      ] },
    ]),
  },
  {
    module: "Welcome & OSHA/ANSI Compliance",
    title: "OSHA & ANSI Compliance: What This Course Covers",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "OSHA & ANSI Compliance: What This Course Covers" },
      { type: "heading", level: 2, text: "OSHA & ANSI Compliance: What This Course Covers" },
      { type: "heading", level: 3, text: "OSHA Regulations" },
      { type: "paragraph", html: "Aerial lifts are regulated under <strong>29 CFR 1926.453</strong> (aerial lifts in construction) and <strong>29 CFR 1910.178</strong> (powered industrial trucks, which includes scissor lifts under OSHA enforcement). OSHA requires operators to receive:" },
      { type: "list", ordered: true, items: [
        "<strong>Formal instruction</strong> — classroom or online training (this course)",
        "<strong>Practical training</strong> — hands-on experience on the specific equipment",
        "<strong>Evaluation</strong> — a qualified person must evaluate the operator's competence",
      ] },
      { type: "heading", level: 3, text: "ANSI/SAIA A92 Standards" },
      { type: "paragraph", html: "The <strong>American National Standards Institute (ANSI)</strong> and the <strong>Scaffold & Access Industry Association (SAIA)</strong> maintain the A92 series for Mobile Elevating Work Platforms (MEWPs):" },
      { type: "list", items: [
        "<strong>A92.20</strong> — Design, Safety, and Verification",
        "<strong>A92.22</strong> — Safe Use of MEWPs",
        "<strong>A92.24</strong> — Training Requirements for MEWP Operators, Occupants, Supervisors, and Service Personnel",
      ] },
      { type: "paragraph", html: "The 2020 revision restructured these standards and replaced the term 'aerial work platform' with 'MEWP.'" },
      { type: "heading", level: 3, text: "What We Provide" },
      { type: "list", items: [
        "Complete formal instruction covering all OSHA and ANSI-required topics",
        "Knowledge assessment via final exam",
        "Certificate of completion for the formal instruction portion",
        "Employer documentation packet including evaluation checklists",
      ] },
      { type: "heading", level: 3, text: "What Your Employer Must Do" },
      { type: "paragraph", html: "After completing this course, your employer must:" },
      { type: "list", items: [
        "Provide hands-on, equipment-specific practical training",
        "Evaluate your performance in the actual workplace",
        "Complete and maintain the required documentation",
        "Ensure familiarization with the specific make/model you will operate",
        "Re-evaluate operators at least every 3 years",
      ] },
      { type: "callout", variant: "warning", text: "Do not operate an aerial or scissor lift until your employer has completed your hands-on training and evaluation on the specific equipment." },
      { type: "key_takeaways", items: [
        "Aerial lifts are regulated under 29 CFR 1926.453 and 1910.178",
        "ANSI/SAIA A92 standards cover MEWP design, use, and training",
        "This course covers formal instruction only — practical training is also required",
        "Operators must be familiarized with the specific equipment they will operate",
      ] },
    ]),
  },
  {
    module: "Welcome & OSHA/ANSI Compliance",
    title: "Knowledge Check: OSHA & ANSI Requirements",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Which OSHA standard specifically covers aerial lifts?", type: "mcq_single", options: ["29 CFR 1910.178", "29 CFR 1926.453", "29 CFR 1910.147", "29 CFR 1926.450"], correctAnswers: "29 CFR 1926.453", explanation: "29 CFR 1926.453 is the OSHA standard for aerial lifts. Scissor lifts are enforced under 1910.178 (powered industrial trucks)." },
      { question: "What does the ANSI A92.24 standard cover?", type: "mcq_single", options: ["Equipment design requirements", "Training requirements for MEWP operators", "Load capacity ratings", "Maintenance schedules"], correctAnswers: "Training requirements for MEWP operators", explanation: "ANSI A92.24 covers training requirements for MEWP operators, occupants, supervisors, and service personnel." },
      { question: "This online course alone fully satisfies all OSHA aerial lift training requirements.", type: "mcq_single", options: ["True", "False"], correctAnswers: "False", explanation: "OSHA requires formal instruction (this course) PLUS practical training and evaluation on the specific equipment by the employer." },
    ],
  },

  // ═══ MODULE 1: Aerial Lift Basics & Classifications ═══
  {
    module: "Aerial Lift Basics & Classifications",
    title: "What is a Mobile Elevating Work Platform (MEWP)?",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "What is a Mobile Elevating Work Platform (MEWP)?" },
      { type: "heading", level: 2, text: "What is a Mobile Elevating Work Platform (MEWP)?" },
      { type: "heading", level: 3, text: "Definition" },
      { type: "paragraph", html: "A <strong>Mobile Elevating Work Platform (MEWP)</strong> is a machine used to position personnel, tools, and materials at elevated work locations. MEWPs include aerial lifts, scissor lifts, boom lifts, and vertical towers. The term MEWP was adopted by ANSI in the 2020 revision of the A92 standards." },
      { type: "heading", level: 3, text: "MEWP Groups (ANSI A92.20)" },
      { type: "paragraph", html: "ANSI classifies MEWPs into two groups based on how the platform is positioned:" },
      { type: "list", items: [
        "<strong>Group A:</strong> Platforms that can only be elevated vertically — the platform stays within the tipping lines (e.g., scissor lifts, vertical lifts)",
        "<strong>Group B:</strong> Platforms that can be positioned beyond the tipping lines — the boom allows the platform to extend horizontally (e.g., articulating boom lifts, telescopic boom lifts)",
      ] },
      { type: "heading", level: 3, text: "MEWP Types" },
      { type: "paragraph", html: "Within each group, MEWPs are further classified by type:" },
      { type: "list", items: [
        "<strong>Type 1:</strong> Drive is only allowed in the stowed position (not elevated)",
        "<strong>Type 2:</strong> Drive is allowed with the platform in the elevated position",
        "<strong>Type 3:</strong> Drive is allowed with the platform elevated, but drive is controlled from the platform (not the chassis)",
      ] },
      { type: "heading", level: 3, text: "Common Equipment Types" },
      { type: "list", items: [
        "<strong>Scissor lifts</strong> (Group A) — vertical elevation only, large platform area",
        "<strong>Articulating boom lifts</strong> (Group B) — jointed arm provides up-and-over reach",
        "<strong>Telescopic boom lifts</strong> (Group B) — straight arm extends for maximum horizontal reach",
        "<strong>Vertical personnel lifts</strong> (Group A) — small platforms for single-person vertical access",
      ] },
      { type: "key_takeaways", items: [
        "MEWPs are classified into Group A (vertical only) and Group B (can extend beyond tipping lines)",
        "Scissor lifts are Group A; boom lifts are Group B",
        "Types 1, 2, and 3 define when and from where driving is permitted",
        "The term MEWP replaced 'aerial work platform' in the 2020 ANSI revision",
      ] },
    ]),
  },
  {
    module: "Aerial Lift Basics & Classifications",
    title: "Scissor Lifts: Operation and Components",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("scissor-lift-hero.svg"), alt: "Scissor Lifts: Operation and Components" },
      { type: "heading", level: 2, text: "Scissor Lifts: Operation and Components" },
      { type: "heading", level: 3, text: "What is a Scissor Lift?" },
      { type: "paragraph", html: "A <strong>scissor lift</strong> is a Group A MEWP that uses crossed tubular supports (a pantograph mechanism) to raise and lower the platform vertically. Scissor lifts provide a large, stable working platform ideal for tasks requiring multiple workers and materials at moderate heights." },
      { type: "heading", level: 3, text: "Key Components" },
      { type: "list", items: [
        "<strong>Platform:</strong> The work area with guardrails and entry gate",
        "<strong>Scissor mechanism:</strong> Crossed supports that extend/retract to raise/lower",
        "<strong>Chassis/base:</strong> The drive unit with wheels or tracks",
        "<strong>Controls:</strong> Upper (platform) and lower (ground) control panels",
        "<strong>Poletree/Extension deck:</strong> Optional extendable platform section",
        "<strong>Power source:</strong> Electric battery or internal combustion (diesel, gas, LPG)",
      ] },
      { type: "heading", level: 3, text: "Operation Controls" },
      { type: "paragraph", html: "Scissor lifts have both <strong>upper and lower controls</strong>. The upper controls are at the platform and are used by the operator during elevation. Lower controls are at ground level. Per OSHA, lower controls must be able to override upper controls in an emergency, but should not be used for normal operation when an operator is in the platform." },
      { type: "heading", level: 3, text: "Driving Capability" },
      { type: "paragraph", html: "Most modern scissor lifts are <strong>Type 3</strong> — they can be driven from the platform controls while elevated. However, driving while elevated should be done cautiously and only on suitable surfaces. Always check the manufacturer's operating manual for specific limitations." },
      { type: "callout", variant: "tip", text: "Always read the manufacturer's operating manual for the specific make and model before operating any MEWP." },
      { type: "key_takeaways", items: [
        "Scissor lifts are Group A MEWPs with vertical-only elevation",
        "They have both upper (platform) and lower (ground) controls",
        "Lower controls can override upper controls in emergencies",
        "Most modern scissor lifts can be driven from the platform while elevated",
      ] },
    ]),
  },
  {
    module: "Aerial Lift Basics & Classifications",
    title: "Boom Lifts: Articulating and Telescopic",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "Boom Lifts: Articulating and Telescopic" },
      { type: "heading", level: 2, text: "Boom Lifts: Articulating and Telescopic" },
      { type: "heading", level: 3, text: "Articulating Boom Lifts" },
      { type: "paragraph", html: "<strong>Articulating boom lifts</strong> (knuckle booms) have multiple hinged sections that allow the platform to reach up and over obstacles. The jointed arm provides excellent maneuverability for reaching over equipment, structures, or obstacles. These are classified as <strong>Group B</strong> MEWPs because the platform can extend beyond the tipping lines." },
      { type: "heading", level: 3, text: "Telescopic Boom Lifts" },
      { type: "paragraph", html: "<strong>Telescopic boom lifts</strong> (stick booms) use straight, extendable sections for maximum horizontal and vertical reach. They offer the highest reach capabilities but cannot reach over obstacles. Also classified as <strong>Group B</strong> MEWPs." },
      { type: "heading", level: 3, text: "Know Your Boom Lift" },
      { type: "paragraph", html: "Before you operate, you need to know the machine's key components. Tap each marker to learn what it does." },
      { type: "hotspot_diagram", src: img("aerial-lift-anatomy.svg"), alt: "Side view of an articulating boom lift with elevated basket",
        caption: "Anatomy of an articulating boom lift — tap each marker to explore.",
        hotspots: [
          { x: 24, y: 79, label: "Chassis", description: "The wheeled base that supports and moves the entire machine. Its weight counterbalances the elevated platform — always position it on firm, level ground." },
          { x: 31, y: 69, label: "Turret & Ground Controls", description: "The rotating turret carries the boom and houses the lower (ground) control panel. Ground controls must be able to override the platform controls in an emergency." },
          { x: 36, y: 53, label: "Lower Boom", description: "The first boom section rises from the turret. On an articulating lift it works with the knuckle to lift the platform up and over obstacles." },
          { x: 49, y: 41, label: "Knuckle Joint", description: "The hinged joint between boom sections. This articulation is what lets a knuckle boom reach over equipment and structures that a telescopic boom cannot." },
          { x: 62, y: 37, label: "Upper Boom", description: "Extends the platform out beyond the tipping lines — this is why boom lifts are Group B MEWPs and demand extra attention to stability." },
          { x: 82, y: 37, label: "Basket & Guardrails", description: "The work platform. Guardrails are your first line of fall protection — never stand on or lean over them, and keep both feet on the platform floor." },
          { x: 81, y: 23, label: "Operator Harness & Lanyard", description: "The operator wears a full body harness with a lanyard attached to the manufacturer-designated anchor point — required at all times in a boom lift basket." },
          { x: 87, y: 21, label: "Platform Controls", description: "The upper control console lets the operator drive, steer, raise, and lower from the basket. Test these controls every day before use." },
        ] },
      { type: "heading", level: 3, text: "Key Differences from Scissor Lifts" },
      { type: "list", items: [
        "Boom lifts can position the platform <strong>beyond the chassis footprint</strong>",
        "They have <strong>greater reach</strong> but typically smaller platform sizes",
        "Group B MEWPs require additional <strong>fall protection</strong> considerations",
        "Outriggers or stabilizers are often required for operation",
        "More complex stability calculations apply",
      ] },
      { type: "heading", level: 3, text: "Power and Drive Options" },
      { type: "paragraph", html: "Boom lifts may be powered by electric batteries (indoor use), diesel (outdoor/rough terrain), or dual fuel. Many models offer two-wheel, four-wheel, or crab steering for positioning in tight spaces." },
      { type: "key_takeaways", items: [
        "Articulating booms have jointed arms for up-and-over reach",
        "Telescopic booms use straight extension for maximum reach distance",
        "Both are Group B MEWPs — platform extends beyond tipping lines",
        "Outriggers/stabilizers are typically required for boom lift operation",
      ] },
    ]),
  },
  {
    module: "Aerial Lift Basics & Classifications",
    title: "Knowledge Check: MEWP Basics",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "A scissor lift is classified as which MEWP group?", type: "mcq_single", options: ["Group A", "Group B", "Group C", "It is not a MEWP"], correctAnswers: "Group A", explanation: "Scissor lifts are Group A MEWPs because the platform can only be elevated vertically and stays within the tipping lines." },
      { question: "Which type of boom lift has jointed sections that allow reaching over obstacles?", type: "mcq_single", options: ["Telescopic boom lift", "Articulating boom lift", "Vertical tower", "Scissor lift"], correctAnswers: "Articulating boom lift", explanation: "Articulating boom lifts (knuckle booms) have multiple hinged sections that allow the platform to reach up and over obstacles." },
      { question: "On a MEWP, the lower controls should be able to:", type: "mcq_single", options: ["Only be used for driving", "Override the upper controls in an emergency", "Be locked out permanently", "Only be used for refueling"], correctAnswers: "Override the upper controls in an emergency", explanation: "Per OSHA, lower controls must be able to override upper controls in an emergency, but should not be used for normal operation when an operator is in the platform." },
    ],
  },

  // ═══ MODULE 2: Pre-Operation Inspection ═══
  {
    module: "Pre-Operation Inspection",
    title: "Pre-Operation Inspection Checklist",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Pre-Operation Inspection Checklist" },
      { type: "heading", level: 2, text: "Pre-Operation Inspection Checklist" },
      { type: "heading", level: 3, text: "OSHA Requirement" },
      { type: "paragraph", html: "Under <strong>29 CFR 1926.453(a)(1)</strong>, lift controls shall be tested each day prior to use to determine that such controls are in safe working condition. This is a mandatory daily requirement." },
      { type: "heading", level: 3, text: "Visual Inspection" },
      { type: "paragraph", html: "Walk around the entire MEWP, checking for:" },
      { type: "list", items: [
        "<strong>Platform and guardrails:</strong> Check for damage, loose components, missing guardrails",
        "<strong>Hoses and cables:</strong> Look for leaks, chafing, kinks, or wear",
        "<strong>Tires/wheels:</strong> Check for damage, proper inflation, lug nut tightness",
        "<strong>Battery/fuel system:</strong> Check charge level, fuel level, leaks",
        "<strong>Structural components:</strong> Inspect for cracks, bends, weld failures",
        "<strong>Outriggers/stabilizers:</strong> Check for proper function and pad condition",
        "<strong>Safety signs and decals:</strong> Ensure capacity labels and warnings are legible",
        "<strong>Guardrails and gates:</strong> Verify chains/gates are in place and functional",
      ] },
      { type: "heading", level: 3, text: "Functional Testing" },
      { type: "paragraph", html: "After the visual inspection, perform a <strong>functional test</strong> of all controls:" },
      { type: "list", items: [
        "Test <strong>upper controls</strong> (platform): raise, lower, drive, steer",
        "Test <strong>lower controls</strong> (ground): raise, lower, emergency stop",
        "Test <strong>emergency lowering</strong> system",
        "Test <strong>horn</strong> and <strong>alarm systems</strong>",
        "Test <strong>brakes</strong> and <strong>steering</strong>",
        "Verify <strong>tilt alarms</strong> if equipped",
        "Test <strong>power disconnect/emergency stop</strong>",
      ] },
      { type: "heading", level: 3, text: "Practice the Sequence" },
      { type: "drag_drop", mode: "ordering",
        prompt: "Put the daily pre-operation inspection steps in the correct order.",
        items: [
          { id: "insp-walk", label: "Walk around the MEWP and complete the visual inspection" },
          { id: "insp-lower", label: "Function-test the lower (ground) controls" },
          { id: "insp-upper", label: "Function-test the upper (platform) controls" },
          { id: "insp-estop", label: "Test the emergency stop and emergency lowering system" },
          { id: "insp-tag", label: "Tag out and report the MEWP if any defect is found" },
        ] },
      { type: "heading", level: 3, text: "Tag Out Unsafe Equipment" },
      { type: "paragraph", html: "If any defect or safety issue is found during inspection, <strong>do not operate the MEWP</strong>. Tag it out of service immediately and report the problem to your supervisor. Equipment must be repaired before it can be returned to service." },
      { type: "callout", variant: "warning", text: "Never operate a MEWP that fails inspection. Any defect must be corrected before use." },
      { type: "key_takeaways", items: [
        "OSHA requires lift controls to be tested each day before use (29 CFR 1926.453)",
        "Perform both a visual inspection and functional test of all controls",
        "Check platform, guardrails, hoses, tires, fuel/battery, and safety devices",
        "Tag out and report any unsafe equipment immediately",
      ] },
    ]),
  },
  {
    module: "Pre-Operation Inspection",
    title: "Battery and Fuel Maintenance",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("ppe-gloves.svg"), alt: "Battery and Fuel Maintenance" },
      { type: "heading", level: 2, text: "Battery and Fuel Maintenance" },
      { type: "heading", level: 3, text: "Battery-Powered MEWPs" },
      { type: "paragraph", html: "Electric MEWPs use deep-cycle batteries. Proper maintenance extends battery life and ensures safe operation:" },
      { type: "list", items: [
        "Charge batteries in <strong>designated, ventilated areas</strong> only",
        "Turn off charger before connecting or disconnecting",
        "Batteries produce <strong>hydrogen gas</strong> during charging — ensure adequate ventilation",
        "Check electrolyte levels (if applicable) and add only distilled water",
        "Wear <strong>chemical-resistant gloves and eye protection</strong> when handling batteries",
        "Never smoke or use open flames near charging batteries",
      ] },
      { type: "heading", level: 3, text: "Internal Combustion MEWPs" },
      { type: "paragraph", html: "Diesel, gasoline, or LPG-powered MEWPs require specific fuel safety:" },
      { type: "list", items: [
        "Refuel only in <strong>designated areas</strong> with proper ventilation",
        "Turn off the engine before refueling",
        "No smoking or open flames within <strong>50 feet</strong> of refueling",
        "Wear gloves when handling LPG tanks",
        "Check for leaks after connecting LPG tanks",
        "Never store fuel containers on the MEWP platform",
      ] },
      { type: "heading", level: 3, text: "Daily Maintenance" },
      { type: "paragraph", html: "Check the following at the start of each shift:" },
      { type: "list", items: [
        "Battery charge level or fuel level is sufficient for the shift",
        "Hydraulic fluid level is within the acceptable range",
        "Engine oil level (for IC engines)",
        "Coolant level (for liquid-cooled engines)",
        "No fluid leaks of any kind",
      ] },
      { type: "callout", variant: "warning", text: "Hydrogen gas from charging batteries is highly explosive. Always ensure adequate ventilation in charging areas." },
      { type: "key_takeaways", items: [
        "Charge batteries only in designated, ventilated areas",
        "Batteries produce explosive hydrogen gas during charging",
        "No smoking or open flames within 50 feet of refueling or charging",
        "Check all fluid levels at the start of each shift",
      ] },
    ]),
  },
  {
    module: "Pre-Operation Inspection",
    title: "Knowledge Check: Pre-Operation Inspection",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "How often must lift controls be tested before use according to OSHA?", type: "mcq_single", options: ["Weekly", "Monthly", "Each day prior to use", "Only after repairs"], correctAnswers: "Each day prior to use", explanation: "29 CFR 1926.453(a)(1) requires lift controls to be tested each day prior to use to determine they are in safe working condition." },
      { question: "If you find a damaged guardrail during pre-operation inspection, you should:", type: "mcq_single", options: ["Continue working and report at end of shift", "Tag it out of service and do not operate", "Use it only for low-height tasks", "Fix it yourself with tape"], correctAnswers: "Tag it out of service and do not operate", explanation: "Any defect found during inspection requires the equipment to be tagged out and not operated until repaired." },
      { question: "Batteries being charged produce which explosive gas?", type: "mcq_single", options: ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"], correctAnswers: "Hydrogen", explanation: "Electric batteries produce hydrogen gas during charging, which is highly explosive in confined spaces." },
    ],
  },

  // ═══ MODULE 3: Stability & Load Handling ═══
  {
    module: "Stability & Load Handling",
    title: "MEWP Stability Principles",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("stability-triangle.svg"), alt: "MEWP Stability Principles" },
      { type: "heading", level: 2, text: "MEWP Stability Principles" },
      { type: "heading", level: 3, text: "Tipping Lines" },
      { type: "paragraph", html: "Every MEWP has <strong>tipping lines</strong> — the axis around which the MEWP could tip if the center of gravity shifts too far. For Group A MEWPs (scissor lifts), the tipping lines are typically the wheels or outriggers. For Group B MEWPs (boom lifts), the tipping lines are the outrigger pads or wheel positions." },
      { type: "heading", level: 3, text: "Center of Gravity" },
      { type: "paragraph", html: "The <strong>combined center of gravity</strong> includes the MEWP itself, the platform load (personnel, tools, materials), and the boom/platform position. If the combined center of gravity moves outside the tipping lines, the MEWP will tip over." },
      { type: "heading", level: 3, text: "Factors Affecting Stability" },
      { type: "list", items: [
        "<strong>Platform height:</strong> Higher elevation raises the center of gravity",
        "<strong>Load weight:</strong> Exceeding rated capacity shifts the center of gravity",
        "<strong>Boom extension:</strong> Horizontal extension moves the center of gravity outward (Group B)",
        "<strong>Slope/grade:</strong> Operating on a slope shifts the center of gravity downhill",
        "<strong>Wind:</strong> Wind force on the platform and load can destabilize the MEWP",
        "<strong>Surface conditions:</strong> Soft ground, ice, or wet surfaces can cause sinking or sliding",
      ] },
      { type: "heading", level: 3, text: "Outriggers and Stabilizers" },
      { type: "paragraph", html: "Many MEWPs, especially Group B boom lifts, require <strong>outriggers or stabilizers</strong> to be deployed before elevation. OSHA requires that brakes be set and outriggers positioned on pads or a solid surface. Always:" },
      { type: "list", items: [
        "Deploy outriggers fully before elevating",
        "Use outrigger pads on soft surfaces to distribute load",
        "Ensure the surface can support the outrigger load",
        "Never operate without outriggers deployed if the manufacturer requires them",
      ] },
      { type: "callout", variant: "warning", text: "Tip-overs are a leading cause of MEWP fatalities. Always respect capacity limits, surface conditions, and manufacturer stability requirements." },
      { type: "key_takeaways", items: [
        "Tipping lines define the boundary of stability — stay within them",
        "Height, load, boom extension, slope, and wind all affect stability",
        "Outriggers must be deployed on pads/solid surface before elevation",
        "The combined center of gravity must stay within the tipping lines",
      ] },
    ]),
  },
  {
    module: "Stability & Load Handling",
    title: "Rated Capacity and Load Limits",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("load-center.svg"), alt: "Rated Capacity and Load Limits" },
      { type: "heading", level: 2, text: "Rated Capacity and Load Limits" },
      { type: "heading", level: 3, text: "Manufacturer's Capacity Rating" },
      { type: "paragraph", html: "Every MEWP has a manufacturer's <strong>rated capacity</strong> plate that specifies the maximum load the platform can safely carry. This includes the combined weight of all personnel, tools, and materials on the platform. <strong>Never exceed this rating.</strong>" },
      { type: "heading", level: 3, text: "Boom Lift Capacity Considerations" },
      { type: "paragraph", html: "For Group B boom lifts, capacity may vary based on boom position. Some boom lifts have <strong>variable capacity ratings</strong> that change with boom extension and angle. Always check the capacity plate for the specific boom configuration you are using." },
      { type: "heading", level: 3, text: "Personnel Limits" },
      { type: "paragraph", html: "The capacity plate also specifies the maximum number of occupants allowed on the platform. Never exceed this limit. Each occupant must have adequate space to work safely within the platform guardrails." },
      { type: "heading", level: 3, text: "Load Distribution" },
      { type: "paragraph", html: "Distribute loads evenly within the platform. Concentrating weight on one side can shift the center of gravity and affect stability. Secure all tools and materials to prevent them from shifting or falling during operation." },
      { type: "callout", variant: "warning", text: "Overloading a MEWP is one of the leading causes of tip-over accidents. Always verify the total platform load before elevating." },
      { type: "key_takeaways", items: [
        "Never exceed the manufacturer's rated capacity",
        "Capacity includes the combined weight of personnel, tools, and materials",
        "Boom lift capacity may vary with boom position (variable capacity ratings)",
        "Distribute loads evenly and secure all materials",
      ] },
    ]),
  },
  {
    module: "Stability & Load Handling",
    title: "Knowledge Check: Stability & Loads",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "What happens if the combined center of gravity moves outside the tipping lines?", type: "mcq_single", options: ["Nothing — the MEWP is self-correcting", "The MEWP will tip over", "An alarm will sound automatically", "The platform will lower automatically"], correctAnswers: "The MEWP will tip over", explanation: "If the combined center of gravity moves outside the tipping lines, the MEWP will tip over, which is why capacity and stability are critical." },
      { question: "Which factor does NOT affect MEWP stability?", type: "mcq_single", options: ["Platform height", "Load weight", "Wind conditions", "The operator's name"], correctAnswers: "The operator's name", explanation: "Height, load weight, wind, slope, and surface conditions all affect stability. The operator's name is irrelevant to stability." },
      { question: "Rated capacity on a MEWP includes the weight of:", type: "mcq_single", options: ["Only the personnel", "Only the tools", "Personnel, tools, and materials combined", "Only the platform itself"], correctAnswers: "Personnel, tools, and materials combined", explanation: "Rated capacity includes the combined weight of all personnel, tools, and materials on the platform." },
    ],
  },

  // ═══ MODULE 4: Safe Operation & Fall Protection ═══
  {
    module: "Safe Operation & Fall Protection",
    title: "Fall Protection Requirements",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pedestrian-safety.svg"), alt: "Fall Protection Requirements" },
      { type: "heading", level: 2, text: "Fall Protection Requirements" },
      { type: "heading", level: 3, text: "OSHA Fall Protection Standard" },
      { type: "paragraph", html: "Under <strong>29 CFR 1926.453</strong>, employees shall always stand firmly on the floor of the basket. A <strong>body belt</strong> shall be worn and a <strong>lanyard</strong> attached to the boom or basket. However, since January 1, 1998, body belts are <strong>NOT acceptable</strong> as part of a personal fall arrest system — a <strong>full body harness</strong> must be used." },
      { type: "heading", level: 3, text: "Personal Fall Arrest System" },
      { type: "paragraph", html: "A complete fall protection system consists of:" },
      { type: "list", items: [
        "<strong>Full body harness</strong> — distributes fall forces across the body",
        "<strong>Lanyard</strong> — connects the harness to the anchor point",
        "<strong>Anchor point</strong> — the designated attachment point on the boom or basket (must be manufacturer-approved)",
      ] },
      { type: "flip_cards", title: "Fall Protection Gear — Know Each Piece", cards: [
        { front: "Full Body Harness", back: "Distributes fall arrest forces across the thighs, pelvis, chest, and shoulders. Required since January 1, 1998 — body belts are not acceptable." },
        { front: "Lanyard", back: "Connects your harness to the anchor point. Inspect for cuts, fraying, and damaged snap hooks before every use." },
        { front: "Anchor Point", back: "The manufacturer-designated attachment point on the platform or boom. Never anchor to structures, power poles, or anything outside the MEWP." },
        { front: "Body Belt", back: "NOT acceptable for fall arrest since January 1, 1998. In a fall, a belt concentrates all the force on the abdomen — use a full body harness instead." },
      ] },
      { type: "heading", level: 3, text: "Attachment Points" },
      { type: "paragraph", html: "Always attach the lanyard to the <strong>manufacturer-designated anchor point</strong> on the platform or boom. Never attach to:" },
      { type: "list", items: [
        "Nearby structures or building framing",
        "Overhead power lines or poles",
        "Other equipment",
        "Anything outside the MEWP",
      ] },
      { type: "heading", level: 3, text: "Harness Inspection" },
      { type: "paragraph", html: "Inspect your harness and lanyard before each use:" },
      { type: "list", items: [
        "Check for cuts, tears, or abrasions in webbing",
        "Inspect stitching for damage",
        "Check hardware (D-rings, buckles, snap hooks) for damage",
        "Verify the label is legible and within service life",
        "Tag out and replace any damaged equipment immediately",
      ] },
      { type: "callout", variant: "warning", text: "Since January 1, 1998, body belts are NOT acceptable as part of a personal fall arrest system. Full body harnesses are required." },
      { type: "key_takeaways", items: [
        "Body belts are NOT acceptable since January 1, 1998 — use full body harnesses",
        "Attach lanyard only to manufacturer-designated anchor points",
        "Never attach to structures or equipment outside the MEWP",
        "Inspect harness and lanyard before every use",
      ] },
    ]),
  },
  {
    module: "Safe Operation & Fall Protection",
    title: "Safe Operating Procedures",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("safe-driving.svg"), alt: "Safe Operating Procedures" },
      { type: "heading", level: 2, text: "Safe Operating Procedures" },
      { type: "heading", level: 3, text: "Before Elevating" },
      { type: "paragraph", html: "Before raising the platform:" },
      { type: "list", items: [
        "Verify the surface is <strong>level and capable of supporting the load</strong>",
        "Deploy outriggers/stabilizers if required by the manufacturer",
        "Set wheel chocks if on an incline",
        "Check for <strong>overhead hazards</strong> (power lines, structures, ceilings)",
        "Ensure the area is clear of pedestrians and obstructions",
      ] },
      { type: "heading", level: 3, text: "While Elevated" },
      { type: "paragraph", html: "When the platform is elevated:" },
      { type: "list", items: [
        "<strong>Always wear your harness and attach lanyard</strong>",
        "Keep both feet firmly on the platform floor",
        "Never stand on guardrails, mid-rails, or ladders",
        "Never lean over or climb on guardrails",
        "Do not exceed the rated capacity or personnel limit",
        "Be aware of surroundings at all times",
      ] },
      { type: "heading", level: 3, text: "Driving While Elevated" },
      { type: "paragraph", html: "If driving while elevated is permitted by the manufacturer:" },
      { type: "list", items: [
        "Drive at <strong>very low speed</strong>",
        "Watch for surface hazards and obstacles",
        "Avoid sudden starts, stops, or turns",
        "Never drive near drop-offs or open edges",
        "Stop driving if conditions become unsafe",
      ] },
      { type: "paragraph", html: "Per OSHA 1926.453(b)(2)(vii), an aerial lift truck shall not be moved when boom is elevated with workers in basket <strong>unless the equipment is specifically designed for this</strong>." },
      { type: "heading", level: 3, text: "Lowering the Platform" },
      { type: "paragraph", html: "Before lowering:" },
      { type: "list", items: [
        "Ensure the area below is clear of personnel and obstacles",
        "Verify the path is clear of overhead obstructions",
        "Lower slowly and under control",
        "Return boom to stowed position before driving to a new location",
      ] },
      { type: "callout", variant: "tip", text: "Before elevating, always look up and around for overhead hazards like power lines, pipes, and structures." },
      { type: "key_takeaways", items: [
        "Always wear a harness and attach to the designated anchor point",
        "Check for overhead hazards before elevating",
        "Never exceed capacity or personnel limits",
        "Lower slowly and ensure the area is clear before descending",
      ] },
    ]),
  },
  {
    module: "Safe Operation & Fall Protection",
    title: "Knowledge Check: Safe Operation & Fall Protection",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Since January 1, 1998, what type of fall protection is required (not body belts)?", type: "mcq_single", options: ["Body belt only", "Full body harness", "No fall protection needed", "A rope and knot"], correctAnswers: "Full body harness", explanation: "Body belts are not acceptable as part of a personal fall arrest system since January 1, 1998. Full body harnesses are required." },
      { question: "When driving a MEWP while elevated, you should:", type: "mcq_single", options: ["Drive at normal speed", "Drive at very low speed and watch for hazards", "Honk repeatedly while driving", "Never drive while elevated under any circumstances"], correctAnswers: "Drive at very low speed and watch for hazards", explanation: "If driving while elevated is permitted by the manufacturer, drive at very low speed, watch for hazards, and avoid sudden movements." },
      { question: "The lanyard should be attached to:", type: "mcq_single", options: ["Any sturdy-looking object nearby", "The manufacturer-designated anchor point on the MEWP", "A nearby building beam", "The overhead guard"], correctAnswers: "The manufacturer-designated anchor point on the MEWP", explanation: "Always attach the lanyard only to the manufacturer-designated anchor point on the platform or boom." },
    ],
  },

  // ═══ MODULE 5: Workplace Hazards & Electrical Safety ═══
  {
    module: "Workplace Hazards & Electrical Safety",
    title: "Electrical Hazards and Power Lines",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "Electrical Hazards and Power Lines" },
      { type: "heading", level: 2, text: "Electrical Hazards and Power Lines" },
      { type: "heading", level: 3, text: "Power Line Clearance" },
      { type: "paragraph", html: "Working near overhead power lines is one of the most dangerous operations for MEWP operators. OSHA requires minimum clearance distances from power lines:" },
      { type: "list", items: [
        "<strong>Up to 50kV:</strong> Minimum 10 feet clearance",
        "<strong>50kV to 200kV:</strong> Minimum 15 feet clearance",
        "<strong>200kV to 350kV:</strong> Minimum 20 feet clearance",
        "<strong>350kV to 500kV:</strong> Minimum 25 feet clearance",
        "<strong>500kV+:</strong> Minimum 35 feet clearance",
      ] },
      { type: "heading", level: 3, text: "Power Line Safety Rules" },
      { type: "paragraph", html: "When working near power lines:" },
      { type: "list", items: [
        "Always treat power lines as <strong>energized and dangerous</strong>",
        "Do not rely on insulation or covers — they may be damaged",
        "If the boom could swing or drift toward lines, use a <strong>spotter</strong>",
        "Be aware of <strong>wind</strong> — strong gusts can push the platform into lines",
        "Never approach power lines if the MEWP's boom could reach within the minimum clearance distance",
      ] },
      { type: "scenario", title: "Power Line Decision",
        prompt: "You are assigned to repair a sign on a building facade. A 25kV distribution line runs about 12 feet from the work area, and gusty wind is picking up. What do you do?",
        choices: [
          { text: "Proceed carefully — 12 feet is more than the 10-foot minimum", correct: false, feedback: "The 10-foot minimum is an absolute limit, not a target. With gusts pushing the platform and possible boom drift, you cannot guarantee clearance. Stop and reassess with your supervisor." },
          { text: "Stop and have the line de-energized, or reposition so the boom cannot reach within 10 feet — and use a spotter", correct: true, feedback: "Correct. Treat every line as energized. In gusty wind, either eliminate the hazard through the utility company or set up so the platform physically cannot enter the minimum clearance, with a spotter watching." },
          { text: "Tie the platform off to the building so the wind cannot push you toward the line", correct: false, feedback: "Never attach the platform or your lanyard to anything outside the MEWP. That creates a tip-over and fall hazard — and it does not make the clearance safe." },
        ] },
      { type: "heading", level: 3, text: "If Contact Occurs" },
      { type: "paragraph", html: "If the MEWP contacts a power line:" },
      { type: "list", ordered: true, items: [
        "<strong>Stay in the platform</strong> — do not try to jump off",
        "Warn others to stay away from the MEWP",
        "Call emergency services (911) and your utility company",
        "Try to break contact by moving the boom away from the line",
        "Do not leave the platform until the power line is de-energized and confirmed safe",
      ] },
      { type: "heading", level: 3, text: "Ground Personnel Safety" },
      { type: "paragraph", html: "If the MEWP is in contact with a power line, anyone on the ground near the MEWP is at risk of electrocution from <strong>step potential</strong> (electricity spreading through the ground). Ground personnel should stay at least <strong>35 feet away</strong> from the MEWP until the power is confirmed off." },
      { type: "callout", variant: "warning", text: "Power line contact is frequently fatal. Maintain minimum clearance distances at all times and use a spotter when working near energized lines." },
      { type: "key_takeaways", items: [
        "Minimum 10 feet clearance from power lines up to 50kV",
        "Always treat power lines as energized and dangerous",
        "If contact occurs: stay in the platform, call 911, and do not try to jump off",
        "Ground personnel should stay 35+ feet away if contact occurs",
      ] },
    ]),
  },
  {
    module: "Workplace Hazards & Electrical Safety",
    title: "Environmental and Workplace Hazards",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Environmental and Workplace Hazards" },
      { type: "heading", level: 2, text: "Environmental and Workplace Hazards" },
      { type: "heading", level: 3, text: "Weather Conditions" },
      { type: "paragraph", html: "Weather significantly affects MEWP safety:" },
      { type: "list", items: [
        "<strong>Wind:</strong> Most MEWPs have a maximum wind speed rating (typically 28 mph). Never exceed the manufacturer's wind speed limit. Wind force increases with platform height.",
        "<strong>Rain and ice:</strong> Make surfaces slippery and reduce traction. Electrical components can be affected.",
        "<strong>Lightning:</strong> Never operate a MEWP during a thunderstorm — the boom can act as a lightning rod.",
        "<strong>Snow and ice:</strong> Add weight to the platform, reduce surface traction, and can obscure hazards.",
      ] },
      { type: "embedded_quiz", title: "Weather Check", questions: [
        { question: "Wind on site picks up to 30 mph. Your MEWP's maximum wind speed rating is 28 mph. What should you do?", type: "mcq_single", options: ["Continue — 2 mph over the limit is negligible", "Lower the platform and stop elevated work until the wind drops", "Raise the platform more slowly than normal", "Add weight to the platform for stability"], correctAnswers: "Lower the platform and stop elevated work until the wind drops", explanation: "Never exceed the manufacturer's wind speed rating. Wind force increases with height — lower the platform and wait for conditions to improve." },
        { question: "A thunderstorm is approaching your outdoor work site. You should:", type: "mcq_single", options: ["Keep working until the rain starts", "Lower the platform, stop work, and move to shelter", "Work faster to finish the task", "Elevate above the trees for a better view"], correctAnswers: "Lower the platform, stop work, and move to shelter", explanation: "Never operate a MEWP during lightning — the boom can act as a lightning rod. Stop work before the storm arrives." },
      ] },
      { type: "heading", level: 3, text: "Surface Conditions" },
      { type: "paragraph", html: "Before operating, verify the ground surface can support the MEWP's weight including load:" },
      { type: "list", items: [
        "Check for <strong>soft ground, mud, or unstable fill</strong>",
        "Verify floor or slab capacity for indoor use",
        "Look for <strong>covered holes, trenches, or voids</strong>",
        "Check for <strong>slopes and grades</strong> within manufacturer limits",
        "Watch for wet, oily, or icy surfaces",
      ] },
      { type: "heading", level: 3, text: "Overhead Hazards" },
      { type: "paragraph", html: "Always check for overhead hazards before and during elevation:" },
      { type: "list", items: [
        "<strong>Power lines</strong> (see previous lesson for clearance distances)",
        "<strong>Building structures</strong>: ceilings, beams, pipes, ductwork",
        "<strong>Overhead doors</strong> and crane ways",
        "<strong>Tree branches</strong> and outdoor structures",
        "<strong>Falling objects</strong> from above",
      ] },
      { type: "heading", level: 3, text: "Pedestrian Traffic" },
      { type: "paragraph", html: "Protect pedestrians and other workers near MEWP operations:" },
      { type: "list", items: [
        "Use <strong>barricades or caution tape</strong> to establish a work zone",
        "Post <strong>warning signs</strong> at approach points",
        "Use a <strong>ground spotter</strong> in high-traffic areas",
        "Sound the <strong>horn</strong> when lowering or moving",
        "Never assume pedestrians can see or hear the MEWP",
      ] },
      { type: "callout", variant: "warning", text: "Lightning + MEWP = extreme danger. The boom acts as a lightning rod. Never operate during thunderstorms." },
      { type: "key_takeaways", items: [
        "Never exceed the manufacturer's maximum wind speed rating",
        "Never operate a MEWP during lightning storms",
        "Check surface conditions for soft ground, slopes, and voids",
        "Use barricades and spotters to protect pedestrians",
      ] },
    ]),
  },
  {
    module: "Workplace Hazards & Electrical Safety",
    title: "Knowledge Check: Workplace Hazards",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "What is the minimum clearance distance from power lines up to 50kV?", type: "mcq_single", options: ["5 feet", "10 feet", "15 feet", "25 feet"], correctAnswers: "10 feet", explanation: "OSHA requires a minimum clearance of 10 feet from power lines rated up to 50kV. Higher voltage lines require greater distances." },
      { question: "If a MEWP contacts a power line, the operator should:", type: "mcq_single", options: ["Jump off immediately", "Stay in the platform and call 911", "Try to push the line away by hand", "Climb down the boom"], correctAnswers: "Stay in the platform and call 911", explanation: "Stay in the platform — jumping off can cause electrocution. Call emergency services and try to break contact using the controls." },
      { question: "You should never operate a MEWP during which weather condition?", type: "mcq_single", options: ["Light drizzle", "Thunderstorm/lightning", "Cloudy skies", "Cool temperatures"], correctAnswers: "Thunderstorm/lightning", explanation: "Never operate a MEWP during a thunderstorm — the boom can act as a lightning rod, creating an extreme electrocution risk." },
    ],
  },

  // ═══ MODULE 6: Emergency Procedures & Rescue ═══
  {
    module: "Emergency Procedures & Rescue",
    title: "Emergency Controls and Lowering",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Emergency Controls and Lowering" },
      { type: "heading", level: 2, text: "Emergency Controls and Lowering" },
      { type: "heading", level: 3, text: "Emergency Lowering System" },
      { type: "paragraph", html: "All MEWPs are equipped with <strong>emergency lowering</strong> systems that allow the platform to be lowered from the ground if the operator is incapacitated or if the upper controls fail. These may be manual valves, electric switches, or hydraulic pumps. Know where these controls are located before operating." },
      { type: "heading", level: 3, text: "Lower Control Override" },
      { type: "paragraph", html: "Per OSHA 1926.453(b)(2)(iii), upper and lower controls are required. The lower controls must be able to <strong>override the upper controls</strong>. This allows a ground person to safely lower the platform in an emergency. However, lower controls should only be used for normal operation when no operator is in the platform." },
      { type: "heading", level: 3, text: "Emergency Stop" },
      { type: "paragraph", html: "All MEWPs have <strong>emergency stop buttons</strong> at both upper and lower control stations. Pressing the E-stop immediately halts all functions. To resume operation, the E-stop must be manually reset by pulling it out or turning it." },
      { type: "heading", level: 3, text: "Power Failure" },
      { type: "paragraph", html: "If power is lost while the platform is elevated:" },
      { type: "list", items: [
        "Do not panic — the platform will remain in position",
        "Use the <strong>manual lowering valve</strong> to descend slowly",
        "If on a boom lift, use the manual boom retraction system",
        "Call for assistance if you cannot lower the platform safely",
      ] },
      { type: "callout", variant: "tip", text: "Before operating any MEWP, locate and test all emergency controls including the lowering valve and E-stop buttons." },
      { type: "key_takeaways", items: [
        "Know the location of emergency lowering controls before operating",
        "Lower controls can override upper controls in emergencies",
        "E-stop buttons are at both upper and lower control stations",
        "If power fails, use manual lowering systems to descend safely",
      ] },
    ]),
  },
  {
    module: "Emergency Procedures & Rescue",
    title: "Rescue Planning and Procedures",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pedestrian-safety.svg"), alt: "Rescue Planning and Procedures" },
      { type: "heading", level: 2, text: "Rescue Planning and Procedures" },
      { type: "heading", level: 3, text: "ANSI A92.22 Rescue Requirements" },
      { type: "paragraph", html: "ANSI A92.22 requires that a <strong>rescue plan</strong> be developed before MEWP use begins. The plan must address how an operator will be retrieved from the platform if they are unable to operate the controls. The plan must be communicated to all relevant personnel." },
      { type: "heading", level: 3, text: "Rescue Plan Components" },
      { type: "paragraph", html: "A complete rescue plan includes:" },
      { type: "list", items: [
        "Identification of <strong>trained rescue personnel</strong> on site",
        "Location and operation of <strong>lower controls</strong> and emergency lowering",
        "Access to a <strong>secondary MEWP</strong> or ladder for rescue if needed",
        "Emergency contact numbers (911, site supervisor)",
        "Procedure for <strong>power line contact</strong> emergencies",
        "Procedure for <strong>tip-over</strong> emergencies",
      ] },
      { type: "heading", level: 3, text: "If an Operator is Incapacitated" },
      { type: "paragraph", html: "If the operator in the platform becomes incapacitated:" },
      { type: "list", ordered: true, items: [
        "Use the <strong>lower controls</strong> to lower the platform",
        "If lower controls fail, use the <strong>emergency lowering valve</strong>",
        "If the platform cannot be lowered, use a <strong>secondary MEWP</strong> to reach the operator",
        "Call <strong>911</strong> for medical emergencies",
        "Never attempt to climb the boom or scissor mechanism",
      ] },
      { type: "heading", level: 3, text: "Tip-Over Response" },
      { type: "paragraph", html: "If a tip-over occurs:" },
      { type: "list", items: [
        "<strong>Stay in the platform</strong> — do not jump",
        "Brace yourself and hold onto the guardrails",
        "Signal for help",
        "Do not attempt to operate the controls until help arrives",
        "Seek medical evaluation after any tip-over incident",
      ] },
      { type: "callout", variant: "warning", text: "Never attempt to climb the boom or scissor mechanism to rescue someone. Use lower controls or a secondary MEWP." },
      { type: "key_takeaways", items: [
        "ANSI A92.22 requires a rescue plan before MEWP use",
        "Identify trained rescue personnel before starting work",
        "Use lower controls or emergency lowering to rescue an incapacitated operator",
        "In a tip-over, stay in the platform and do not jump",
      ] },
    ]),
  },
  {
    module: "Emergency Procedures & Rescue",
    title: "Knowledge Check: Emergency Procedures",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "What does ANSI A92.22 require before MEWP use begins?", type: "mcq_single", options: ["A rescue plan", "A weather report", "A second operator", "A backup battery"], correctAnswers: "A rescue plan", explanation: "ANSI A92.22 requires a rescue plan to be developed before MEWP use begins, addressing how an operator will be retrieved if incapacitated." },
      { question: "If a tip-over occurs, the operator should:", type: "mcq_single", options: ["Jump off immediately", "Stay in the platform and hold on", "Try to right the MEWP", "Climb down the boom"], correctAnswers: "Stay in the platform and hold on", explanation: "Stay in the platform during a tip-over — do not jump. Brace yourself, hold the guardrails, and signal for help." },
      { question: "The emergency stop (E-stop) button is located at:", type: "mcq_single", options: ["Only at the upper controls", "Only at the lower controls", "Both upper and lower control stations", "Only on the chassis"], correctAnswers: "Both upper and lower control stations", explanation: "E-stop buttons are at both upper (platform) and lower (ground) control stations for emergency shutdown." },
    ],
  },

  // ═══ MODULE 7: Final Exam & Completion ═══
  {
    module: "Final Exam & Completion",
    title: "Final Exam: Aerial & Scissor Lift Certification",
    type: "exam",
    estimatedMinutes: 15,
    config: {
      passing_score: 80,
      max_attempts: 3,
      randomize_questions: true,
    },
    questions: [
      { question: "Which OSHA standard specifically covers aerial lifts?", type: "mcq_single", options: ["29 CFR 1910.178", "29 CFR 1926.453", "29 CFR 1910.147", "29 CFR 1926.450"], correctAnswers: "29 CFR 1926.453", explanation: "29 CFR 1926.453 is the OSHA standard for aerial lifts." },
      { question: "A scissor lift is classified as which MEWP group?", type: "mcq_single", options: ["Group A", "Group B", "Group C", "Group D"], correctAnswers: "Group A", explanation: "Scissor lifts are Group A MEWPs — the platform can only be elevated vertically and stays within the tipping lines." },
      { question: "How often must lift controls be tested before use?", type: "mcq_single", options: ["Weekly", "Monthly", "Each day prior to use", "Only after repairs"], correctAnswers: "Each day prior to use", explanation: "29 CFR 1926.453(a)(1) requires lift controls to be tested each day prior to use." },
      { question: "Since January 1, 1998, what type of fall protection is required?", type: "mcq_single", options: ["Body belt only", "Full body harness", "No fall protection needed", "A safety net"], correctAnswers: "Full body harness", explanation: "Body belts are not acceptable since January 1, 1998. Full body harnesses are required as part of a personal fall arrest system." },
      { question: "What is the minimum clearance from power lines up to 50kV?", type: "mcq_single", options: ["5 feet", "10 feet", "15 feet", "25 feet"], correctAnswers: "10 feet", explanation: "OSHA requires a minimum clearance of 10 feet from power lines rated up to 50kV." },
      { question: "If a MEWP contacts a power line, the operator should:", type: "mcq_single", options: ["Jump off immediately", "Stay in the platform and call 911", "Push the line away", "Climb down the boom"], correctAnswers: "Stay in the platform and call 911", explanation: "Stay in the platform — jumping off can cause electrocution. Call emergency services and try to break contact using the controls." },
      { question: "What should you do if a defect is found during pre-operation inspection?", type: "mcq_single", options: ["Continue working and report later", "Tag it out of service and do not operate", "Use it for short tasks only", "Fix it with tape"], correctAnswers: "Tag it out of service and do not operate", explanation: "Any defect found during inspection requires the equipment to be tagged out and not operated until repaired." },
      { question: "The lanyard should be attached to:", type: "mcq_single", options: ["Any nearby sturdy object", "The manufacturer-designated anchor point", "A building beam", "The overhead guard"], correctAnswers: "The manufacturer-designated anchor point", explanation: "Always attach the lanyard only to the manufacturer-designated anchor point on the platform or boom." },
      { question: "Never operate a MEWP during which weather condition?", type: "mcq_single", options: ["Light drizzle", "Thunderstorm/lightning", "Cloudy skies", "Cool weather"], correctAnswers: "Thunderstorm/lightning", explanation: "Never operate a MEWP during a thunderstorm — the boom acts as a lightning rod." },
      { question: "If a tip-over occurs, the operator should:", type: "mcq_single", options: ["Jump off immediately", "Stay in the platform and hold on", "Try to right the MEWP", "Turn off the engine"], correctAnswers: "Stay in the platform and hold on", explanation: "Stay in the platform during a tip-over. Do not jump. Brace yourself and signal for help." },
      { question: "What does ANSI A92.22 require before MEWP use begins?", type: "mcq_single", options: ["A rescue plan", "A weather report", "A second operator", "A video recording"], correctAnswers: "A rescue plan", explanation: "ANSI A92.22 requires a rescue plan to be developed before MEWP use begins." },
      { question: "The lower controls on a MEWP must be able to:", type: "mcq_single", options: ["Only drive the MEWP", "Override the upper controls in an emergency", "Be locked permanently", "Only be used for refueling"], correctAnswers: "Override the upper controls in an emergency", explanation: "Lower controls must be able to override upper controls in an emergency, per OSHA 1926.453." },
      { question: "Batteries being charged produce which explosive gas?", type: "mcq_single", options: ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"], correctAnswers: "Hydrogen", explanation: "Electric batteries produce hydrogen gas during charging, which is highly explosive." },
      { question: "What happens if the center of gravity moves outside the tipping lines?", type: "mcq_single", options: ["Nothing", "The MEWP will tip over", "An alarm sounds", "The platform lowers automatically"], correctAnswers: "The MEWP will tip over", explanation: "If the combined center of gravity moves outside the tipping lines, the MEWP will tip over." },
      { question: "Rated capacity on a MEWP includes the weight of:", type: "mcq_single", options: ["Only personnel", "Only tools", "Personnel, tools, and materials combined", "Only the platform"], correctAnswers: "Personnel, tools, and materials combined", explanation: "Rated capacity includes the combined weight of all personnel, tools, and materials on the platform." },
      { question: "An aerial lift truck shall not be moved when the boom is elevated with workers in the basket unless:", type: "mcq_single", options: ["The supervisor approves", "The equipment is specifically designed for this", "It is an emergency", "The workers are wearing harnesses"], correctAnswers: "The equipment is specifically designed for this", explanation: "Per OSHA 1926.453(b)(2)(vii), the truck shall not be moved when boom is elevated with workers in basket unless specifically designed for this purpose." },
      { question: "No smoking or open flames within how many feet of charging batteries?", type: "mcq_single", options: ["10 feet", "25 feet", "50 feet", "100 feet"], correctAnswers: "50 feet", explanation: "No smoking or open flames within 50 feet of battery charging areas due to explosive hydrogen gas risk." },
      { question: "This online course alone fully satisfies all OSHA aerial lift training requirements.", type: "mcq_single", options: ["True", "False"], correctAnswers: "False", explanation: "OSHA requires formal instruction (this course) PLUS practical training and evaluation on the specific equipment by the employer." },
      { question: "Ground personnel should stay how far from a MEWP in contact with a power line?", type: "mcq_single", options: ["10 feet", "25 feet", "35 feet", "50 feet"], correctAnswers: "35 feet", explanation: "Ground personnel should stay at least 35 feet away due to step potential — electricity spreading through the ground." },
      { question: "Employees shall always stand firmly on the ___ of the basket.", type: "mcq_single", options: ["Edge", "Floor", "Guardrail", "Mid-rail"], correctAnswers: "Floor", explanation: "OSHA 1926.453 requires employees to always stand firmly on the floor of the basket. Never on guardrails or other surfaces." },
      { question: "What must be deployed before elevating a boom lift that requires them?", type: "mcq_single", options: ["Outriggers/stabilizers", "Extension cords", "Safety nets", "Rope ladders"], correctAnswers: "Outriggers/stabilizers", explanation: "Outriggers or stabilizers must be fully deployed on pads or solid surface before elevating, per OSHA requirements." },
      { question: "Never operate a MEWP exceeding the manufacturer's maximum:", type: "mcq_single", options: ["Color rating", "Wind speed rating", "Decibel rating", "Tire pressure"], correctAnswers: "Wind speed rating", explanation: "Most MEWPs have a maximum wind speed rating (typically 28 mph). Never exceed this limit." },
    ],
  },
  {
    module: "Final Exam & Completion",
    title: "Congratulations: What's Next",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "You're Certified! What's Next" },
      { type: "heading", level: 2, text: "You're Certified! What's Next" },
      { type: "heading", level: 3, text: "Your Certificate" },
      { type: "paragraph", html: "Congratulations on completing the formal instruction portion of your aerial and scissor lift operator certification! Your digital certificate is now available for download. It includes a unique certificate number and QR code that employers can use for instant verification." },
      { type: "heading", level: 3, text: "Next Step: Practical Evaluation" },
      { type: "paragraph", html: "Remember, your employer must still complete the <strong>hands-on practical training and evaluation</strong> on the specific equipment you will operate. Share the employer documentation packet with your supervisor, including:" },
      { type: "list", items: [
        "Performance Evaluation Checklist for aerial/scissor lifts",
        "Operator Permit / Authorization Form",
        "Equipment-specific familiarization requirements",
      ] },
      { type: "heading", level: 3, text: "Stay Safe" },
      { type: "paragraph", html: "Your training doesn't end here. Continue to follow safe operating procedures every day. If you ever have questions or need a refresher, you can revisit this course at any time. Stay safe out there!" },
      { type: "callout", variant: "tip", text: "Bookmark your verification page link — employers can use it to instantly verify your certification." },
      { type: "key_takeaways", items: [
        "Download your certificate from your certification page",
        "Share the employer packet with your supervisor for practical evaluation",
        "Your employer must provide equipment-specific hands-on training",
        "Re-evaluation is required at least every 3 years",
      ] },
    ]),
  },
];
