import type { LessonBlock } from "@shared/lesson-blocks";
import { StepDef, QuestionDef } from "./course-content-forklift-ttt";

export const CANONICAL_COURSE_ES = {
  title: "Certificación Capacitar al Capacitador de Montacargas",
  slug: "certificacion-capacitar-capacitador-montacargas-en-linea",
  description: "Certificación integral Capacitar al Capacitador en cumplimiento con OSHA para capacitación de operadores de montacargas. Cubre las calificaciones de instructor bajo OSHA 29 CFR 1910.178(l)(2)(iii), principios de aprendizaje de adultos, diseño de programas de capacitación, todos los temas requeridos por OSHA, metodología de capacitación práctica, evaluación de operadores, administración de programas y cultura de seguridad. Al completar, estará calificado para capacitar y evaluar operadores de montacargas en sus instalaciones.",
  category: "trainer",
  price: "150.00",
};

const img = (name: string) => `/images/training/${name}`;

const blocks = (b: LessonBlock[]) => ({ blocks: b });

export const COURSE_STEPS_ES: StepDef[] = [
  // ═══ MÓDULO 0: Marco Regulatorio OSHA ═══
  {
    module: "Marco Regulatorio OSHA",
    title: "Bienvenida y Marco Regulatorio OSHA",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "Bienvenida y Marco Regulatorio OSHA" },
      { type: "heading", level: 2, text: "Bienvenida y Marco Regulatorio OSHA" },
      { type: "heading", level: 3, text: "Acerca de Este Curso" },
      { type: "paragraph", html: "¡Bienvenido a la Certificación Capacitar al Capacitador de Montacargas! Este curso lo prepara para convertirse en un <strong>instructor calificado de operadores de montacargas</strong> bajo OSHA 29 CFR 1910.178(l)(2)(iii). El curso toma aproximadamente <strong>2-3 horas</strong>." },
      { type: "heading", level: 3, text: "Calificaciones del Instructor (1910.178(l)(2)(iii))" },
      { type: "paragraph", html: "OSHA establece: <em>\"Toda la capacitación y evaluación de operadores será conducida por personas que tengan el conocimiento, capacitación y experiencia para capacitar operadores de camiones industriales motorizados y evaluar su competencia.\"</em>" },
      { type: "paragraph", html: "OSHA <strong>no</strong> requiere una certificación específica para instructores. Se requieren tres calificaciones:" },
      { type: "list", ordered: true, items: [
        "<strong>Conocimiento</strong> — de la norma OSHA y el tema",
        "<strong>Capacitación</strong> — capacitación formal sobre los temas que enseñará",
        "<strong>Experiencia</strong> — experiencia práctica operando el equipo",
      ] },
      { type: "flip_cards", title: "Las Tres Calificaciones del Instructor", cards: [
        { front: "Conocimiento", back: "Debe conocer a fondo la norma OSHA (29 CFR 1910.178) y el tema: capacidad, estabilidad, inspecciones y reglas de operación segura." },
        { front: "Capacitación", back: "Debe haber recibido capacitación formal sobre los temas que enseñará. Este curso proporciona esa capacitación formal para instructores." },
        { front: "Experiencia", back: "Debe tener experiencia práctica operando el equipo. Un instructor que no puede demostrar una habilidad no puede enseñarla ni evaluarla con credibilidad." },
      ] },
      { type: "heading", level: 3, text: "Lo Que Cubre Este Curso" },
      { type: "list", items: [
        "Revisión completa de 29 CFR 1910.178",
        "Responsabilidades del empleador bajo la norma",
        "Requisitos de documentación y certificación",
        "Los 22 temas requeridos de capacitación",
        "Principios de aprendizaje de adultos y metodología",
        "Diseño de capacitación práctica y evaluación de operadores",
        "Administración de programas y cultura de seguridad",
      ] },
      { type: "heading", level: 3, text: "Nota Importante" },
      { type: "paragraph", html: "Este curso lo califica para <strong>capacitar y evaluar operadores</strong>. <strong>No</strong> lo certifica para operar equipo. Debe ser un operador competente de montacargas antes de tomar este curso." },
      { type: "callout", variant: "warning", text: "Este curso no lo certifica para operar un montacargas. Debe ser un operador competente." },
      { type: "key_takeaways", items: [
        "OSHA requiere que los instructores tengan conocimiento, capacitación y experiencia",
        "No se requiere certificación específica de instructor por OSHA",
        "Este curso cubre la capacitación formal para instructores",
        "Capacitar al Capacitador NO lo certifica para operar equipo",
      ] },
    ]),
  },
  {
    module: "Marco Regulatorio OSHA",
    title: "Responsabilidades del Empleador y Documentación",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "Responsabilidades del Empleador y Documentación" },
      { type: "heading", level: 2, text: "Responsabilidades del Empleador y Documentación" },
      { type: "heading", level: 3, text: "Deber del Empleador (1910.178(l)(1))" },
      { type: "paragraph", html: "El empleador es responsable de asegurar que cada operador sea <strong>capacitado</strong>, <strong>evaluado</strong> y <strong>certificado</strong>. Esto incluye capacitación inicial, evaluación de competencia, recapacitación cuando sea necesaria, y re-evaluación al menos cada 3 años." },
      { type: "heading", level: 3, text: "Requisitos de Certificación (1910.178(l)(6))" },
      { type: "paragraph", html: "La certificación debe incluir: <strong>nombre del operador</strong>, <strong>fecha de capacitación</strong>, <strong>fecha de evaluación</strong>, y <strong>identidad de la persona(s)</strong> que realiza la capacitación o evaluación." },
      { type: "heading", level: 3, text: "Conservación de Registros" },
      { type: "paragraph", html: "Mantenga registros de capacitación disponibles para inspección de OSHA. Mejor práctica: conservar durante el empleo más 3 años. Incluya: currículo, listas de evaluación, permisos de operador, registros de recapacitación, reportes de incidentes." },
      { type: "heading", level: 3, text: "Inspección y Aplicación de OSHA" },
      { type: "paragraph", html: "OSHA puede realizar <strong>inspecciones sin previo aviso</strong>. Las multas por incumplimiento pueden alcanzar <strong>$15,625 por violación seria</strong> (2023), y hasta <strong>$156,259</strong> por violaciones intencionales o repetidas." },
      { type: "callout", variant: "tip", text: "Cree un archivo de capacitación para cada operador con certificación, evaluaciones y recapacitación." },
      { type: "key_takeaways", items: [
        "El empleador es responsable de la capacitación y evaluación de operadores",
        "La certificación debe incluir nombre, fechas y identidad del instructor",
        "Conserve registros durante el empleo más 3 años",
        "Las multas de OSHA pueden exceder $15,000 por violación",
      ] },
    ]),
  },
  {
    module: "Marco Regulatorio OSHA",
    title: "Verificación de Conocimiento: Marco OSHA",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Qué tres calificaciones debe tener un instructor de montacargas según OSHA?", type: "mcq_single", options: ["Título universitario, certificado de enseñanza, 5 años de experiencia", "Conocimiento, capacitación y experiencia", "Diploma de secundaria, certificación de montacargas, aprobación del supervisor", "Certificación de OSHA, primeros auxilios, licencia de conducir"], correctAnswers: "Conocimiento, capacitación y experiencia", explanation: "OSHA requiere que los instructores tengan conocimiento, capacitación y experiencia para capacitar operadores y evaluar su competencia." },
      { question: "¿Qué debe incluir la certificación del operador según 1910.178(l)(6)?", type: "mcq_single", options: ["Número de Seguro Social del operador", "Nombre del operador, fecha de capacitación, fecha de evaluación, identidad del instructor", "Registros médicos del operador", "Solo la firma del operador"], correctAnswers: "Nombre del operador, fecha de capacitación, fecha de evaluación, identidad del instructor", explanation: "La certificación debe incluir nombre, fechas de capacitación y evaluación, e identidad del instructor/evaluador." },
      { question: "¿Con qué frecuencia deben ser re-evaluados los operadores según OSHA?", type: "mcq_single", options: ["Cada año", "Cada 2 años", "Cada 3 años", "Cada 5 años"], correctAnswers: "Cada 3 años", explanation: "OSHA requiere re-evaluación al menos cada tres años." },
    ],
  },

  // ═══ MÓDULO 1: Principios de Aprendizaje de Adultos ═══
  {
    module: "Principios de Aprendizaje de Adultos",
    title: "Cómo Aprenden los Adultos: Andragogía",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "Cómo Aprenden los Adultos: Andragogía" },
      { type: "heading", level: 2, text: "Cómo Aprenden los Adultos: Andragogía" },
      { type: "heading", level: 3, text: "Teoría de Aprendizaje de Adultos" },
      { type: "paragraph", html: "Los adultos aprenden diferente que los niños. Principios clave (<strong>andragogía</strong>):" },
      { type: "list", items: [
        "<strong>Autodirigidos:</strong> Quieren responsabilidad por su aprendizaje",
        "<strong>Basados en experiencia:</strong> Traen experiencia valiosa",
        "<strong>Orientados a relevancia:</strong> Aprenden mejor cuando es relevante para su trabajo",
        "<strong>Centrados en problemas:</strong> Prefieren aprendizaje que resuelve problemas reales",
        "<strong>Motivados internamente:</strong> Por autoestima, mejor calidad de trabajo",
      ] },
      { type: "heading", level: 3, text: "Estilos de Aprendizaje" },
      { type: "paragraph", html: "Incluya los tres estilos en su capacitación:" },
      { type: "list", items: [
        "<strong>Visual:</strong> Diagramas, videos, demostraciones",
        "<strong>Auditivo:</strong> Conferencias, discusiones, explicaciones verbales",
        "<strong>Kinestésico:</strong> Práctica hands-on, operación de equipo",
      ] },
      { type: "heading", level: 3, text: "Técnicas de Presentación Efectivas" },
      { type: "list", items: [
        "Comience con el <strong>por qué</strong> — explique la justificación de seguridad",
        "Use <strong>ejmplos del mundo real</strong> del lugar de trabajo",
        "Sesiones <strong>cortas</strong> (15-20 minutos por tema)",
        "Fomente <strong>preguntas y discusión</strong>",
        "Use <strong>multimedia</strong> — videos, diapositivas, demostraciones",
        "Proporcione <strong>práctica hands-on</strong> inmediatamente",
      ] },
      { type: "heading", level: 3, text: "Gestión de Dinámica de Grupo" },
      { type: "paragraph", html: "Cree un <strong>ambiente de aprendizaje seguro</strong>, maneje participantes dominantes, involucre participantes callados, aborde concepciones erróneas de seguridad, mantenga el <strong>horario</strong>." },
      { type: "callout", variant: "tip", text: "Pregunte a los participantes sobre su experiencia al inicio. Sus historias son excelentes ejemplos de enseñanza." },
      { type: "key_takeaways", items: [
        "Los adultos son autodirigidos, basados en experiencia y orientados a relevancia",
        "Incluya elementos visuales, auditivos y kinestésicos",
        "Comience con el 'por qué' y use ejemplos del mundo real",
        "Cree un ambiente de aprendizaje seguro",
      ] },
    ]),
  },
  {
    module: "Principios de Aprendizaje de Adultos",
    title: "Estrategias de Evaluación",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Estrategias de Evaluación" },
      { type: "heading", level: 2, text: "Estrategias de Evaluación" },
      { type: "heading", level: 3, text: "Evaluación de Conocimiento" },
      { type: "paragraph", html: "Pruebe la comprensión mediante: <strong>exámenes escritos</strong>, <strong>preguntas orales</strong>, <strong>cuestionarios throughout</strong>, <strong>estudios de caso</strong>." },
      { type: "heading", level: 3, text: "Evaluación Práctica" },
      { type: "paragraph", html: "Evalúe habilidades mediante: <strong>demostración</strong>, <strong>observación</strong>, <strong>listas de verificación</strong>, <strong>evaluación progresiva</strong>." },
      { type: "heading", level: 3, text: "Criterios de Aprobación/Reprobación" },
      { type: "paragraph", html: "Establezca criterios claros: puntuación de aprobación (típicamente 80%), habilidades obligatorias, fallas críticas de seguridad (reprobación automática), intentos permitidos, remediación." },
      { type: "heading", level: 3, text: "Proporcionar Retroalimentación" },
      { type: "paragraph", html: "Retroalimentación <strong>específica</strong>, <strong>oportuna</strong>, <strong>equilibrada</strong> (fortalezas y debilidades), <strong>accionable</strong>." },
      { type: "key_takeaways", items: [
        "Use evaluaciones de conocimiento y prácticas",
        "Establezca criterios claros antes de la capacitación",
        "Use listas de verificación estandarizadas",
        "Proporcione retroalimentación específica y oportuna",
      ] },
    ]),
  },
  {
    module: "Principios de Aprendizaje de Adultos",
    title: "Verificación de Conocimiento: Aprendizaje de Adultos",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Los adultos aprenden mejor cuando la capacitación es:", type: "mcq_single", options: ["Puramente teórica", "Directamente relevante para su trabajo", "Basada en memorización", "En sesiones largas"], correctAnswers: "Directamente relevante para su trabajo", explanation: "Los adultos son orientados a relevancia — aprenden mejor cuando el contenido es aplicable a su trabajo." },
      { question: "¿Cuál NO es uno de los tres estilos de aprendizaje?", type: "mcq_single", options: ["Visual", "Auditivo", "Kinestésico", "Olfativo"], correctAnswers: "Olfativo", explanation: "Los tres estilos son visual, auditivo y kinestésico." },
      { question: "La retroalimentación debe ser:", type: "mcq_single", options: ["Retrasada varios días", "General y vaga", "Específica, oportuna, equilibrada y accionable", "Solo sobre debilidades"], correctAnswers: "Específica, oportuna, equilibrada y accionable", explanation: "La retroalimentación efectiva es específica, oportuna, equilibrada y accionable." },
    ],
  },

  // ═══ MÓDULO 2: Diseño del Programa de Capacitación ═══
  {
    module: "Diseño del Programa de Capacitación",
    title: "Diseñando Su Programa de Capacitación",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "Diseñando Su Programa de Capacitación" },
      { type: "heading", level: 2, text: "Diseñando Su Programa de Capacitación" },
      { type: "heading", level: 3, text: "Evaluación de Necesidades" },
      { type: "paragraph", html: "Identifique: <strong>tipos de equipo</strong> en uso, <strong>condiciones del lugar de trabajo</strong>, <strong>niveles de experiencia</strong>, <strong>peligros específicos del sitio</strong>, <strong>requisitos regulatorios</strong>." },
      { type: "heading", level: 3, text: "Objetivos de Aprendizaje" },
      { type: "paragraph", html: "Escriba <strong>objetivos medibles</strong> con verbos de acción: \"demostrar\", \"identificar\", \"realizar\". Evite términos vagos como \"entender\"." },
      { type: "heading", level: 3, text: "Estructura del Currículo" },
      { type: "list", ordered: true, items: [
        "<strong>Instrucción formal</strong> — teoría y conocimiento",
        "<strong>Capacitación práctica</strong> — demostraciones y práctica guiada",
        "<strong>Evaluación</strong> — conocimiento y habilidades",
        "<strong>Documentación</strong> — registros de certificación",
      ] },
      { type: "drag_drop", mode: "ordering",
        prompt: "Ordene las fases de un programa de capacitación en cumplimiento con OSHA en el orden correcto.",
        items: [
          { id: "phase-formal", label: "Instrucción formal — teoría y conocimiento" },
          { id: "phase-practical", label: "Capacitación práctica — demostraciones y práctica guiada" },
          { id: "phase-evaluation", label: "Evaluación — evaluar conocimiento y habilidades" },
          { id: "phase-documentation", label: "Documentación — completar registros de certificación" },
        ] },
      { type: "heading", level: 3, text: "Materiales de Capacitación" },
      { type: "paragraph", html: "Prepare: presentaciones, manuales de equipo, listas de inspección, formularios de evaluación, examen escrito, reglas de seguridad del sitio, ayudas visuales." },
      { type: "callout", variant: "tip", text: "Personalice su capacitación a su lugar de trabajo específico." },
      { type: "key_takeaways", items: [
        "Comience con evaluación de necesidades de su instalación",
        "Escriba objetivos medibles con verbos de acción",
        "Estructura: instrucción formal, práctica, evaluación, documentación",
        "Prepare todos los materiales antes de la sesión",
      ] },
    ]),
  },
  {
    module: "Diseño del Programa de Capacitación",
    title: "Diseño de Ejercicios Prácticos",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Diseño de Ejercicios Prácticos" },
      { type: "heading", level: 2, text: "Diseño de Ejercicios Prácticos" },
      { type: "heading", level: 3, text: "Desarrollo Progresivo de Habilidades" },
      { type: "list", ordered: true, items: [
        "<strong>Controles básicos</strong> — arrancar, girar, detener",
        "<strong>Maniobras simples</strong> — adelante, reversa, giros",
        "<strong>Manejo de cargas</strong> — recoger, transportar, apilar",
        "<strong>Operaciones complejas</strong> — rampas, muelles, pasillos estrechos",
        "<strong>Tareas específicas del sitio</strong>",
      ] },
      { type: "heading", level: 3, text: "Configuración de Área de Práctica" },
      { type: "paragraph", html: "Conos, tarimas, rampa simulada, pasillo estrecho, espacio libre de tráfico." },
      { type: "heading", level: 3, text: "Técnica de Práctica Guiada" },
      { type: "list", ordered: true, items: [
        "<strong>Demostrar</strong> la habilidad",
        "<strong>Explicar</strong> cada paso",
        "Practicar con <strong>guía</strong>",
        "<strong>Retroalimentación inmediata</strong>",
        "Práctica <strong>independiente</strong>",
        "<strong>Evaluar</strong>",
      ] },
      { type: "heading", level: 3, text: "Corregir Comportamientos Inseguros" },
      { type: "paragraph", html: "<strong>Detener</strong> inmediatamente, explicar por qué es inseguro, demostrar el procedimiento correcto, repetir correctamente." },
      { type: "key_takeaways", items: [
        "Desarrolle habilidades progresivamente",
        "Configure un área de práctica designada",
        "Use el ciclo demostrar-practicar-evaluar",
        "Detenga comportamientos inseguros inmediatamente",
      ] },
    ]),
  },
  {
    module: "Diseño del Programa de Capacitación",
    title: "Verificación de Conocimiento: Diseño del Programa",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Los objetivos de aprendizaje deben usar:", type: "mcq_single", options: ["Términos vagos como 'entender'", "Verbos de acción medibles como 'demostrar'", "Párrafos largos", "Solo los objetivos del instructor"], correctAnswers: "Verbos de acción medibles como 'demostrar'", explanation: "Los objetivos deben usar verbos de acción medibles." },
      { question: "La progresión recomendada para capacitación práctica es:", type: "mcq_single", options: ["Comenzar con operaciones complejas", "Comenzar con controles básicos y construir progresivamente", "Solo evaluar al final", "Saltar a tareas específicas"], correctAnswers: "Comenzar con controles básicos y construir progresivamente", explanation: "Construya habilidades progresivamente." },
    ],
  },

  // ═══ MÓDULO 3: Temas Requeridos Profundización ═══
  {
    module: "Temas Requeridos Profundización",
    title: "Temas Relacionados con el Camión (1910.178(l)(3)(i))",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("forklift-hero.svg"), alt: "Temas Relacionados con el Camión (1910.178(l)(3)(i))" },
      { type: "heading", level: 2, text: "Temas Relacionados con el Camión (1910.178(l)(3)(i))" },
      { type: "heading", level: 3, text: "OSHA Requiere 13 Temas Relacionados con el Camión" },
      { type: "paragraph", html: "OSHA 1910.178(l)(3)(i) requiere capacitación en <strong>13 temas relacionados con el camión</strong> (A-M):" },
      { type: "heading", level: 3, text: "Temas A-E" },
      { type: "list", items: [
        "(A) Instrucciones de operación, advertencias y precauciones",
        "(B) Diferencias entre el camión y el automóvil",
        "(C) Controles e instrumentación del camión",
        "(D) Operación del motor",
        "(E) Dirección y maniobras",
      ] },
      { type: "heading", level: 3, text: "Temas F-I" },
      { type: "list", items: [
        "(F) Visibilidad (incluyendo restricciones por carga)",
        "(G) Adaptación de horquillas y accesorios",
        "(H) Capacidad del vehículo",
        "(I) Estabilidad del vehículo (triángulo de estabilidad)",
      ] },
      { type: "heading", level: 3, text: "Temas J-M" },
      { type: "list", items: [
        "(J) Inspección y mantenimiento que el operador debe realizar",
        "(K) Reabastecimiento de combustible y carga de baterías",
        "(L) Limitaciones de operación",
        "(M) Otras instrucciones del manual del operador",
      ] },
      { type: "embedded_quiz", questions: [
        { question: "¿Cuál es la manera más efectiva de enseñar los controles e instrumentación del camión?", type: "mcq_single", options: ["Mostrar fotos en una presentación", "Usar el equipo real que los operadores usarán", "Que los operadores lean el manual por su cuenta", "Describir los controles verbalmente"], correctAnswers: "Usar el equipo real que los operadores usarán", explanation: "Los controles e instrumentación deben enseñarse en el equipo real, con los operadores demostrando cada función de control ellos mismos." },
        { question: "La estabilidad del vehículo (el triángulo de estabilidad) pertenece a ¿qué categoría de temas requeridos?", type: "mcq_single", options: ["Temas relacionados con el camión", "Temas relacionados con el lugar de trabajo", "Temas opcionales", "Temas solo para instructores"], correctAnswers: "Temas relacionados con el camión", explanation: "La estabilidad del vehículo es el tema (I) de los 13 temas relacionados con el camión requeridos por 1910.178(l)(3)(i)." },
      ] },
      { type: "callout", variant: "tip", text: "Cree una lista de verificación de los 13 temas y márquelos a medida que los cubre." },
      { type: "key_takeaways", items: [
        "OSHA requiere 13 temas relacionados con el camión",
        "Cubra controles, dirección, visibilidad, capacidad, estabilidad",
        "Use el equipo real para enseñar controles",
        "Cree una lista de verificación de los 13 temas",
      ] },
    ]),
  },
  {
    module: "Temas Requeridos Profundización",
    title: "Temas Relacionados con el Lugar de Trabajo (1910.178(l)(3)(ii))",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Temas Relacionados con el Lugar de Trabajo (1910.178(l)(3)(ii))" },
      { type: "heading", level: 2, text: "Temas Relacionados con el Lugar de Trabajo (1910.178(l)(3)(ii))" },
      { type: "heading", level: 3, text: "OSHA Requiere 9 Temas del Lugar de Trabajo" },
      { type: "paragraph", html: "OSHA 1910.178(l)(3)(ii) requiere <strong>9 temas relacionados con el lugar de trabajo</strong> (A-I). Son específicos del sitio:" },
      { type: "heading", level: 3, text: "Temas A-C" },
      { type: "list", items: [
        "(A) Condiciones de superficie",
        "(B) Composición de cargas y estabilidad",
        "(C) Manipulación, apilado y desapilado de cargas",
      ] },
      { type: "heading", level: 3, text: "Temas D-F" },
      { type: "list", items: [
        "(D) Tráfico de peatones",
        "(E) Pasillos estrechos y lugares restringidos",
        "(F) Ubicaciones peligrosas clasificadas",
      ] },
      { type: "heading", level: 3, text: "Temas G-I" },
      { type: "list", items: [
        "(G) Rampas y superficies inclinadas",
        "(H) Ambientes cerrados y ventilación",
        "(I) Otras condiciones ambientales únicas",
      ] },
      { type: "key_takeaways", items: [
        "OSHA requiere 9 temas del lugar de trabajo",
        "Son específicos del sitio y deben personalizarse",
        "Camine por la instalación real durante la capacitación",
        "Cubra superficies, cargas, peatones, rampas, ventilación",
      ] },
    ]),
  },
  {
    module: "Temas Requeridos Profundización",
    title: "Verificación de Conocimiento: Temas Requeridos",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Cuántos temas relacionados con el camión requiere OSHA?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "13", explanation: "OSHA requiere 13 temas relacionados con el camión (A-M)." },
      { question: "¿Cuántos temas del lugar de trabajo requiere OSHA?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "9", explanation: "OSHA requiere 9 temas del lugar de trabajo (A-I)." },
      { question: "Los temas del lugar de trabajo deben ser:", type: "mcq_single", options: ["Genéricos", "Personalizados a su instalación específica", "Memorizados del texto de OSHA", "Omitidos para operadores experimentados"], correctAnswers: "Personalizados a su instalación específica", explanation: "Los temas del lugar de trabajo son específicos del sitio." },
    ],
  },

  // ═══ MÓDULO 4: Metodología de Capacitación Práctica ═══
  {
    module: "Metodología de Capacitación Práctica",
    title: "Conducción de Sesiones de Capacitación Práctica",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Conducción de Sesiones de Capacitación Práctica" },
      { type: "heading", level: 2, text: "Conducción de Sesiones de Capacitación Práctica" },
      { type: "heading", level: 3, text: "Configuración para el Éxito" },
      { type: "paragraph", html: "Área <strong>libre de peatones</strong>, montacargas en <strong>condiciones seguras</strong>, <strong>listas de evaluación</strong> listas, revisar <strong>procedimientos de emergencia</strong>." },
      { type: "heading", level: 3, text: "Ciclo Demostración-Práctica-Evaluación" },
      { type: "list", ordered: true, items: [
        "<strong>Demostrar</strong> cada habilidad",
        "<strong>Práctica guiada</strong> con coaching",
        "<strong>Práctica independiente</strong>",
        "<strong>Evaluar</strong> contra la lista",
      ] },
      { type: "heading", level: 3, text: "Habilidades Clave a Practicar" },
      { type: "paragraph", html: "Inspección pre-turno, conducción básica, manejo de cargas, operación en rampas, operaciones de muelle, estacionamiento y apagado." },
      { type: "heading", level: 3, text: "Seguridad Durante la Capacitación" },
      { type: "paragraph", html: "El instructor es responsable de la seguridad. Mantenga <strong>ruta de escape</strong>, nunca permita <strong>maniobras peligrosas</strong>, detenga ejercicios inseguros inmediatamente." },
      { type: "scenario", title: "Decisión del Instructor",
        prompt: "Durante la práctica guiada, su participante recoge una tarima y comienza a girar con la carga elevada a unos cinco pies del suelo, moviéndose rápido. No hay nadie más cerca. ¿Qué hace usted?",
        choices: [
          { text: "Dejarlo terminar la maniobra y mencionarlo durante el debriefing", correct: false, feedback: "El comportamiento inseguro debe detenerse en el momento en que lo vea. Una carga elevada en un giro rápido es el escenario clásico de volcadura — esperar al debriefing es esperar un accidente." },
          { text: "Detener el ejercicio inmediatamente, explicar por qué es inseguro, demostrar la técnica correcta y hacer que lo repita", correct: true, feedback: "Correcto. Detenga la operación inmediatamente, explique por qué el comportamiento es inseguro, demuestre el procedimiento correcto y haga que el participante repita la operación correctamente. Documente problemas recurrentes." },
          { text: "Subirse al camión y tomar los controles para terminar la maniobra", correct: false, feedback: "Nunca se acerque ni se suba a un montacargas en movimiento — eso lo pone en la zona de peligro. Indique al participante que se detenga y corrija el comportamiento desde una posición segura." },
        ] },
      { type: "callout", variant: "warning", text: "Como instructor, es responsable de la seguridad durante la capacitación práctica." },
      { type: "key_takeaways", items: [
        "Use el ciclo demostrar-practicar-evaluar",
        "Practique: inspección, conducción, cargas, rampas, muelles",
        "Mantenga el área despejada",
        "Detenga comportamientos inseguros inmediatamente",
      ] },
    ]),
  },
  {
    module: "Metodología de Capacitación Práctica",
    title: "Verificación de Conocimiento: Capacitación Práctica",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "El ciclo recomendado de capacitación es:", type: "mcq_single", options: ["Probar primero, luego enseñar", "Demostrar, práctica guiada, práctica independiente, evaluar", "Solo conferencia", "Solo evaluar"], correctAnswers: "Demostrar, práctica guiada, práctica independiente, evaluar", explanation: "El ciclo efectivo es demostrar, guiar práctica, permitir práctica independiente, luego evaluar." },
      { question: "Si un participante realiza una maniobra insegura, debe:", type: "mcq_single", options: ["Dejarlo terminar y abordarlo después", "Detener el ejercicio inmediatamente", "Ignorarlo si nadie resultó herido", "Solo anotarlo en la evaluación"], correctAnswers: "Detener el ejercicio inmediatamente", explanation: "Detenga el comportamiento inseguro inmediatamente." },
    ],
  },

  // ═══ MÓDULO 5: Evaluación de Operadores ═══
  {
    module: "Evaluación de Operadores",
    title: "Conducción de la Evaluación del Operador",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Conducción de la Evaluación del Operador" },
      { type: "heading", level: 2, text: "Conducción de la Evaluación del Operador" },
      { type: "heading", level: 3, text: "Evaluación vs. Capacitación" },
      { type: "paragraph", html: "La capacitación y evaluación son <strong>actividades separadas</strong>. La evaluación determina si el operador es competente para operar independientemente. <strong>Observe sin coaching</strong>." },
      { type: "heading", level: 3, text: "Diseño de Lista de Evaluación" },
      { type: "paragraph", html: "Inspección pre-turno, arranque, conducción, manejo de cargas, rampas/muelles, estacionamiento, conciencia de seguridad." },
      { type: "heading", level: 3, text: "Conducción de la Evaluación" },
      { type: "list", ordered: true, items: [
        "Explicar qué se evaluará",
        "Aclarar que es evaluación, no capacitación",
        "Observar y calificar",
        "Tomar notas",
        "Debriefing después",
      ] },
      { type: "heading", level: 3, text: "Decisiones de Aprobación/Reprobación" },
      { type: "paragraph", html: "<strong>Aprobar:</strong> todo seguro. <strong>Reprobación automática:</strong> riesgo de volcadura, casi-accidente con peatón, exceder capacidad. Proporcione remediación y re-evaluación." },
      { type: "key_takeaways", items: [
        "La evaluación es separada de la capacitación",
        "Use listas estandarizadas",
        "Establezca criterios claros de aprobación/reprobación",
        "Proporcione remediación para reprobados",
      ] },
    ]),
  },
  {
    module: "Evaluación de Operadores",
    title: "Verificación de Conocimiento: Evaluación de Operadores",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Durante una evaluación, el instructor debe:", type: "mcq_single", options: ["Coaching en cada paso", "Observar sin coaching", "Tomar control si lucha", "Omitir items conocidos"], correctAnswers: "Observar sin coaching", explanation: "La evaluación es separada de la capacitación — observe sin coaching." },
      { question: "Si un operador reprueba la evaluación, debe:", type: "mcq_single", options: ["Certificarlo de todos modos", "Proporcionar capacitación adicional y re-evaluar", "Despedir al operador", "Ignorar la reprobación"], correctAnswers: "Proporcionar capacitación adicional y re-evaluar", explanation: "Proporcione remediación y re-evaluación." },
    ],
  },

  // ═══ MÓDULO 6: Administración y Cultura de Seguridad ═══
  {
    module: "Administración y Cultura de Seguridad",
    title: "Administrando Su Programa de Capacitación",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "Administrando Su Programa de Capacitación" },
      { type: "heading", level: 2, text: "Administrando Su Programa de Capacitación" },
      { type: "heading", level: 3, text: "Gestión de Registros" },
      { type: "paragraph", html: "Mantenga: fecha de capacitación, currículo, resultados de evaluación, certificación, recapacitación, re-evaluación, reportes de incidentes." },
      { type: "heading", level: 3, text: "Disparadores de Recapacitación (1910.178(l)(4))" },
      { type: "paragraph", html: "Recapacitación requerida cuando: operación insegura observada, accidente o casi-accidente, evaluación revela operación insegura, nuevo tipo de camión, cambio en condiciones del lugar de trabajo. Más evaluación cada <strong>3 años</strong>." },
      { type: "drag_drop", mode: "matching",
        prompt: "Relacione cada situación con el disparador de recapacitación que representa.",
        items: [
          { id: "sit-speeding", label: "Un operador es visto acelerando por una intersección ciega sin tocar la bocina", targetId: "trig-unsafe" },
          { id: "sit-rack", label: "Un operador golpea un poste del estante al salir en reversa de un pasillo", targetId: "trig-accident" },
          { id: "sit-reach", label: "Un operador de contrapeso sentado es asignado a un camión reach de pie", targetId: "trig-newtruck" },
          { id: "sit-ramp", label: "Se instala una nueva rampa entre el almacén y el patio", targetId: "trig-workplace" },
        ],
        targets: [
          { id: "trig-unsafe", label: "Operación insegura observada" },
          { id: "trig-accident", label: "Accidente o casi-accidente" },
          { id: "trig-newtruck", label: "Asignado a un tipo diferente de camión" },
          { id: "trig-workplace", label: "Cambio en las condiciones del lugar de trabajo" },
        ] },
      { type: "heading", level: 3, text: "Gestión de Equipo Nuevo" },
      { type: "paragraph", html: "Capacitación específica al equipo antes de permitir operación. Revise el manual. Familiarización con controles. Evalúe antes de certificar." },
      { type: "heading", level: 3, text: "Mejora Continua" },
      { type: "paragraph", html: "Revise datos de accidentes, actualice materiales cuando cambien las regulaciones, solicite retroalimentación, manténgase al día con OSHA." },
      { type: "key_takeaways", items: [
        "Mantenga registros detallados de capacitación",
        "La recapacitación es requerida por operación insegura, accidentes, equipo nuevo",
        "Proporcione capacitación específica al equipo nuevo",
        "Mejore continuamente basado en datos",
      ] },
    ]),
  },
  {
    module: "Administración y Cultura de Seguridad",
    title: "Construyendo una Cultura de Seguridad",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("pedestrian-safety.svg"), alt: "Construyendo una Cultura de Seguridad" },
      { type: "heading", level: 2, text: "Construyendo una Cultura de Seguridad" },
      { type: "heading", level: 3, text: "El Rol del Instructor" },
      { type: "paragraph", html: "Como instructor, es un <strong>líder de seguridad</strong>. Su actitud y comportamiento establecen el tono. Lidere con el ejemplo." },
      { type: "heading", level: 3, text: "Promover Mentalidad de 'Seguridad Primero'" },
      { type: "paragraph", html: "Fomente detener el trabajo si es inseguro, recompense reportar peligros, nunca presione para apresurar, haga la seguridad un tema regular, reconozca comportamientos seguros." },
      { type: "heading", level: 3, text: "Compromiso de la Gerencia" },
      { type: "paragraph", html: "Abogue por: tiempo adecuado de capacitación, mantenimiento de equipo, aplicación de reglas, investigación de accidentes, auditorías regulares." },
      { type: "heading", level: 3, text: "Seguridad como Proceso Continuo" },
      { type: "paragraph", html: "La seguridad no es un evento único — es un proceso continuo de refuerzo, recapacitación y comunicación." },
      { type: "callout", variant: "tip", text: "Comience cada turno con un briefing de seguridad de 2 minutos." },
      { type: "key_takeaways", items: [
        "El instructor es un líder de seguridad",
        "Fomente una política de 'detener el trabajo'",
        "Abogue por compromiso de la gerencia",
        "La seguridad es un proceso continuo",
      ] },
    ]),
  },
  {
    module: "Administración y Cultura de Seguridad",
    title: "Verificación de Conocimiento: Administración y Cultura",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "La recapacitación es requerida cuando:", type: "mcq_single", options: ["Solo cada 3 años", "Se observa operación insegura", "Solo cuando OSHA visita", "Solo para nuevos empleados"], correctAnswers: "Se observa operación insegura", explanation: "La recapacitación es requerida por operación insegura, accidentes, evaluaciones fallidas, equipo nuevo, o cambios en el lugar de trabajo." },
      { question: "Como instructor, su rol en la cultura de seguridad es:", type: "mcq_single", options: ["Solo enseñar el material", "Liderar con el ejemplo y ser un líder de seguridad", "Aplicar reglas pero no seguirlas", "Solo reportar a la gerencia"], correctAnswers: "Liderar con el ejemplo y ser un líder de seguridad", explanation: "El instructor es un líder de seguridad que establece el tono." },
    ],
  },

  // ═══ MÓDULO 7: Examen Final y Finalización ═══
  {
    module: "Examen Final y Finalización",
    title: "Examen Final: Certificación Capacitar al Capacitador",
    type: "exam",
    estimatedMinutes: 15,
    config: { passing_score: 80, max_attempts: 3, randomize_questions: true },
    questions: [
      { question: "¿Qué norma OSHA establece las calificaciones del instructor?", type: "mcq_single", options: ["29 CFR 1910.178(l)(2)(iii)", "29 CFR 1926.453", "29 CFR 1910.147", "29 CFR 1926.500"], correctAnswers: "29 CFR 1910.178(l)(2)(iii)", explanation: "29 CFR 1910.178(l)(2)(iii) establece que la capacitación debe ser conducida por personas con conocimiento, capacitación y experiencia." },
      { question: "¿Qué tres calificaciones debe poseer un instructor?", type: "mcq_single", options: ["Título, certificado, licencia", "Conocimiento, capacitación y experiencia", "Edad, educación, aptitud física", "Antigüedad, aprobación, permanencia"], correctAnswers: "Conocimiento, capacitación y experiencia", explanation: "OSHA requiere conocimiento, capacitación y experiencia." },
      { question: "¿Qué debe incluir la certificación del operador?", type: "mcq_single", options: ["Foto del operador", "Nombre, fecha de capacitación, fecha de evaluación, identidad del instructor", "SSN del operador", "Solo la firma del empleador"], correctAnswers: "Nombre, fecha de capacitación, fecha de evaluación, identidad del instructor", explanation: "Debe incluir nombre, fechas e identidad del instructor." },
      { question: "¿Con qué frecuencia deben ser re-evaluados los operadores?", type: "mcq_single", options: ["Cada año", "Cada 2 años", "Cada 3 años", "Cada 5 años"], correctAnswers: "Cada 3 años", explanation: "OSHA requiere re-evaluación cada tres años." },
      { question: "¿Cuántos temas relacionados con el camión deben cubrirse?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "13", explanation: "Se requieren 13 temas relacionados con el camión (A-M)." },
      { question: "¿Cuántos temas del lugar de trabajo deben cubrirse?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "9", explanation: "Se requieren 9 temas del lugar de trabajo (A-I)." },
      { question: "Los adultos aprenden mejor cuando la capacitación es:", type: "mcq_single", options: ["Puramente teórica", "Directamente relevante para su trabajo", "Basada en memorización", "En conferencias largas"], correctAnswers: "Directamente relevante para su trabajo", explanation: "Los adultos son orientados a relevancia." },
      { question: "Los tres estilos de aprendizaje son:", type: "mcq_single", options: ["Visual, auditivo, kinestésico", "Lectura, escritura, aritmética", "Rápido, medio, lento", "Individual, grupal, en línea"], correctAnswers: "Visual, auditivo, kinestésico", explanation: "Los tres estilos son visual, auditivo y kinestésico." },
      { question: "Los objetivos de aprendizaje deben usar:", type: "mcq_single", options: ["Términos vagos como 'entender'", "Verbos de acción medibles como 'demostrar'", "Párrafos largos", "Solo el nombre del instructor"], correctAnswers: "Verbos de acción medibles como 'demostrar'", explanation: "Use verbos de acción medibles." },
      { question: "El ciclo recomendado de capacitación práctica es:", type: "mcq_single", options: ["Probar, enseñar, probar", "Demostrar, práctica guiada, práctica independiente, evaluar", "Solo conferencia", "Solo evaluar"], correctAnswers: "Demostrar, práctica guiada, práctica independiente, evaluar", explanation: "El ciclo efectivo." },
      { question: "Durante una evaluación, el instructor debe:", type: "mcq_single", options: ["Coaching en cada paso", "Observar sin coaching", "Tomar control si lucha", "Omitir items conocidos"], correctAnswers: "Observar sin coaching", explanation: "Observe sin coaching." },
      { question: "La recapacitación es requerida cuando:", type: "mcq_single", options: ["Solo cada 3 años", "Se observa operación insegura", "Solo cuando OSHA visita", "Solo para nuevos empleados"], correctAnswers: "Se observa operación insegura", explanation: "Requerida por operación insegura, accidentes, etc." },
      { question: "Si un operador reprueba la evaluación práctica:", type: "mcq_single", options: ["Certificarlo de todos modos", "Proporcionar capacitación adicional y re-evaluar", "Despedir al operador", "Ignorar la reprobación"], correctAnswers: "Proporcionar capacitación adicional y re-evaluar", explanation: "Proporcione remediación y re-evaluación." },
      { question: "Este curso Capacitar al Capacitador lo certifica para:", type: "mcq_single", options: ["Operar cualquier montacargas", "Capacitar y evaluar operadores de montacargas", "Inspeccionar montacargas para OSHA", "Vender materiales de capacitación"], correctAnswers: "Capacitar y evaluar operadores de montacargas", explanation: "Lo califica para capacitar y evaluar operadores." },
      { question: "Los temas del lugar de trabajo deben ser:", type: "mcq_single", options: ["Genéricos", "Personalizados a su instalación específica", "Omitidos para experimentados", "Memorizados de OSHA"], correctAnswers: "Personalizados a su instalación específica", explanation: "Son específicos del sitio." },
      { question: "Como instructor, es un:", type: "mcq_single", options: ["Solo un maestro", "Líder de seguridad que lidera con el ejemplo", "Aplicador de reglas", "Solo guardián de registros"], correctAnswers: "Líder de seguridad que lidera con el ejemplo", explanation: "El instructor es un líder de seguridad." },
      { question: "OSHA puede multar hasta cuánto por violación seria?", type: "mcq_single", options: ["$1,000", "$5,000", "$15,625", "$100,000"], correctAnswers: "$15,625", explanation: "Las multas por violaciones serias pueden alcanzar $15,625 (2023)." },
      { question: "¿Qué es una falla crítica que resulta en reprobación automática?", type: "mcq_single", options: ["Conducción lenta", "Riesgo de volcadura o casi-accidente con peatón", "Olvidar tocar la bocina una vez", "Estacionarse ligeramente descentrado"], correctAnswers: "Riesgo de volcadura o casi-accidente con peatón", explanation: "Las fallas críticas de seguridad resultan en reprobación automática." },
      { question: "La retroalimentación efectiva debe ser:", type: "mcq_single", options: ["Retrasada y vaga", "Específica, oportuna, equilibrada y accionable", "Solo sobre debilidades", "Solo al final"], correctAnswers: "Específica, oportuna, equilibrada y accionable", explanation: "Específica, oportuna, equilibrada y accionable." },
      { question: "Los registros de capacitación deben conservarse por:", type: "mcq_single", options: ["30 días", "1 año", "Duración del empleo más 3 años", "Para siempre"], correctAnswers: "Duración del empleo más 3 años", explanation: "Mejor práctica: empleo más 3 años." },
    ],
  },
  {
    module: "Examen Final y Finalización",
    title: "Felicitaciones: Es un Instructor Certificado",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "¡Es un Instructor Certificado! ¿Qué Sigue?" },
      { type: "heading", level: 2, text: "¡Es un Instructor Certificado! ¿Qué Sigue?" },
      { type: "heading", level: 3, text: "Su Certificación" },
      { type: "paragraph", html: "¡Felicitaciones por completar la Certificación Capacitar al Capacitador! Está calificado para <strong>capacitar y evaluar operadores de montacargas</strong> en sus instalaciones bajo OSHA 29 CFR 1910.178(l)(2)(iii)." },
      { type: "heading", level: 3, text: "Próximos Pasos" },
      { type: "list", items: [
        "Descargue su certificado de instructor",
        "Desarrolle su currículo específico al sitio",
        "Cree listas de evaluación práctica",
        "Programe su primera sesión de capacitación",
        "Mantenga su propia competencia como operador",
      ] },
      { type: "heading", level: 3, text: "Manténgase Actualizado" },
      { type: "paragraph", html: "Continúe desarrollando sus habilidades. Manténgase al día con regulaciones de OSHA, asista a recapacitación y mejore continuamente." },
      { type: "callout", variant: "tip", text: "Comience con una sesión piloto para refinar su currículo." },
      { type: "key_takeaways", items: [
        "Está calificado para capacitar y evaluar operadores",
        "Desarrolle su currículo y formularios de evaluación",
        "Mantenga su competencia como operador",
        "Manténgase al día con OSHA",
      ] },
    ]),
  },
];
