import type { LessonBlock } from "@shared/lesson-blocks";

export interface StepDef {
  title: string;
  type: "lesson" | "video" | "checkpoint" | "download" | "exam" | "content";
  config: any;
  estimatedMinutes: number;
  module: string;
  questions?: QuestionDef[];
}

export interface QuestionDef {
  question: string;
  type: "mcq_single" | "mcq_multi";
  options: string[];
  correctAnswers: string;
  explanation: string;
}

export const CANONICAL_COURSE = {
  title: "Online Forklift Operator Certification",
  slug: "online-forklift-operator-certification",
  description: "Comprehensive OSHA-compliant powered industrial truck (forklift) operator training. Covers formal instruction, safety procedures, load handling, and employer documentation. Complete video training, knowledge checks, and pass the final exam to receive your industry-recognized certification. Note: OSHA also requires employer-conducted practical training and evaluation.",
  category: "forklift",
  price: "45.00",
};

const img = (name: string) => `/images/training/${name}`;
const photo = (name: string) => `/images/training/photos/${name}`;

const blocks = (b: LessonBlock[]) => ({ blocks: b });

export const COURSE_STEPS: StepDef[] = [
  // ═══ MODULE 0: Welcome + OSHA Compliance ═══
  {
    module: "Welcome & OSHA Compliance",
    title: "Welcome to Forklift Operator Certification",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: photo("warehouse-aisle-scene.svg"), alt: "Warehouse aisle with pallet racking and a loading door" },
      { type: "heading", level: 2, text: "Welcome to Forklift Operator Certification" },
      { type: "heading", level: 3, text: "About This Course" },
      { type: "paragraph", html: "Welcome! This online course provides the <strong>formal instruction</strong> portion of OSHA-compliant powered industrial truck (PIT/forklift) operator certification. The course takes approximately <strong>45–60 minutes</strong> to complete." },
      { type: "heading", level: 3, text: "What's Included" },
      { type: "list", items: [
        "Interactive training modules covering all OSHA-required topics",
        "Knowledge check quizzes throughout",
        "Final certification exam (80% passing score)",
        "Digital certificate with QR-verified credential",
        "Employer documentation packet for practical evaluation",
      ] },
      { type: "heading", level: 3, text: "What's NOT Included" },
      { type: "paragraph", html: "OSHA requires <strong>three components</strong> for full certification: (1) formal instruction (this course), (2) practical/hands-on training, and (3) an evaluation of operator performance. Your employer must conduct the hands-on portion at your worksite. We provide all the forms they need in Module 7." },
      { type: "heading", level: 3, text: "How to Navigate" },
      { type: "paragraph", html: "Complete each step in order. You can track your progress using the sidebar. If you need to stop, your progress is saved automatically. You can retake the final exam up to 3 times." },
      { type: "callout", variant: "tip", text: "Look out for interactive diagrams, flip cards, and scenarios throughout the course — they are the fastest way to lock in what you learn." },
      { type: "key_takeaways", items: [
        "This course covers the formal instruction requirement",
        "Your employer must also conduct hands-on training and evaluation",
        "Complete all modules and pass the final exam at 80% or higher",
        "Your progress saves automatically — resume anytime",
      ] },
    ]),
  },
  {
    module: "Welcome & OSHA Compliance",
    title: "OSHA Compliance: What This Course Covers",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: photo("ppe-workers-scene.svg"), alt: "Workers in full PPE standing in front of a forklift" },
      { type: "heading", level: 2, text: "OSHA Compliance: What This Course Covers" },
      { type: "heading", level: 3, text: "OSHA's Three-Part Requirement" },
      { type: "paragraph", html: "Under <strong>29 CFR 1910.178(l)</strong>, OSHA requires all forklift operators to complete three components before operating at work. Explore each one in the diagram below." },
      { type: "hotspot_diagram", src: img("osha-compliance.svg"), alt: "OSHA three-part training requirement infographic",
        caption: "OSHA 29 CFR 1910.178(l): all three parts are required.",
        hotspots: [
          { x: 17, y: 42, label: "1. Formal Instruction", description: "Classroom or online training covering all OSHA safety topics — that is exactly what this course provides. It ends with a knowledge assessment (your final exam)." },
          { x: 48, y: 42, label: "2. Practical Training", description: "Hands-on experience operating the specific equipment at your worksite, provided by your employer after you finish this course." },
          { x: 78, y: 42, label: "3. Evaluation", description: "A supervisor or qualified trainer must observe you operating and sign off on your competence. We include the evaluation forms in Module 7." },
          { x: 50, y: 80, label: "Certified Operator", description: "Only after all three components are complete are you a fully certified operator. Re-evaluation is required at least every 3 years." },
        ] },
      { type: "heading", level: 3, text: "What Your Employer Must Do" },
      { type: "list", items: [
        "Provide practical, hands-on training on the specific equipment you will operate",
        "Evaluate your performance in the actual workplace",
        "Complete and maintain the required documentation (provided in Module 7)",
        "Re-evaluate operators at least every 3 years",
      ] },
      { type: "paragraph", html: "<em>Important: This online course alone does not fully satisfy OSHA requirements. The practical training and evaluation must be completed by your employer at your worksite.</em>" },
      { type: "callout", variant: "warning", text: "Do not operate a forklift until your employer has completed your hands-on training and evaluation." },
      { type: "key_takeaways", items: [
        "OSHA requires formal instruction + practical training + evaluation",
        "This course covers the formal instruction and knowledge assessment",
        "Your employer must complete hands-on training and evaluation",
        "Operators must be re-evaluated at least every 3 years",
      ] },
    ]),
  },
  {
    module: "Welcome & OSHA Compliance",
    title: "Knowledge Check: OSHA Requirements",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "OSHA training for forklift operators requires formal instruction, practical training, AND an evaluation.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "OSHA requires all three components: formal instruction, practical/hands-on training, and an evaluation of operator performance." },
      { question: "This online course replaces the need for hands-on evaluation by your employer.", type: "mcq_single", options: ["True", "False"], correctAnswers: "False", explanation: "This course covers formal instruction only. Your employer must still conduct hands-on training and evaluation at your worksite." },
      { question: "If you are unsure about an operation, you should ask your supervisor before proceeding.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "Always consult your supervisor when uncertain. Operating a forklift without proper knowledge creates serious safety risks." },
    ],
  },

  // ═══ MODULE 1: Forklift Basics + Responsibilities ═══
  {
    module: "Forklift Basics & Responsibilities",
    title: "What is a Powered Industrial Truck (PIT)?",
    type: "lesson",
    estimatedMinutes: 6,
    config: blocks([
      { type: "hero_image", src: photo("forklift-lifting-scene.svg"), alt: "Forklift raising a palletized load to a rack while a spotter watches" },
      { type: "heading", level: 2, text: "What is a Powered Industrial Truck (PIT)?" },
      { type: "heading", level: 3, text: "Definition" },
      { type: "paragraph", html: "A <strong>Powered Industrial Truck (PIT)</strong> is any mobile, self-propelled vehicle used to carry, push, pull, lift, stack, or tier materials. Common names include forklift, pallet jack, rider truck, fork truck, and lift truck." },
      { type: "paragraph", html: "PITs may be powered by electric motors or internal combustion engines (propane, gasoline, diesel)." },
      { type: "heading", level: 3, text: "Know Your Machine" },
      { type: "paragraph", html: "Before you operate, you need to know the machine's key components. Tap each marker to learn what it does." },
      { type: "hotspot_diagram", src: img("forklift-anatomy.svg"), alt: "Side view of a counterbalance forklift",
        hotspots: [
          { x: 36, y: 31, label: "Overhead Guard", description: "Protects the operator from falling objects. It is not designed to withstand a full load falling on it — never lift more than rated capacity." },
          { x: 56, y: 35, label: "Mast", description: "The vertical assembly that raises and lowers the load. Lift chains and hydraulic cylinders inside the mast do the lifting work." },
          { x: 61, y: 67, label: "Load Backrest", description: "Keeps the load from sliding back toward the operator when the mast is tilted back." },
          { x: 73, y: 86, label: "Forks", description: "Carry the load. Inspect daily for cracks, bends, and heel wear. Always spread them to fit the pallet and insert fully." },
          { x: 24, y: 69, label: "Counterweight", description: "The heavy rear section that balances the load on the forks. This is why a forklift steers from the rear and why overloading is so dangerous." },
          { x: 46, y: 79, label: "Drive Wheels (front)", description: "The front wheels carry most of the weight and drive the machine. They form the front two corners of the stability triangle." },
          { x: 27, y: 81, label: "Steer Wheels (rear)", description: "Forklifts steer with the REAR wheels — the tail swings wide in turns. Always check your rear swing clearance." },
          { x: 46, y: 69, label: "Data Plate", description: "Lists the truck's rated capacity, load center, weight, and fuel type. Read it before every job — it is your legal lifting limit." },
          { x: 34, y: 53, label: "Operator Seat & Seat Belt", description: "Your seat belt is your primary protection in a tip-over. Buckle up before starting the engine, every time." },
        ] },
      { type: "heading", level: 3, text: "OSHA Equipment Classifications" },
      { type: "paragraph", html: "OSHA groups powered industrial trucks into 7 classes. Flip each card to see what the class covers." },
      { type: "flip_cards", title: "The 7 OSHA Classes", cards: [
        { front: "Class I", back: "Electric Motor Rider Trucks — sit-down counterbalance trucks powered by battery." },
        { front: "Class II", back: "Electric Motor Narrow Aisle Trucks — reach trucks and order pickers built for tight aisles." },
        { front: "Class III", back: "Electric Walkie/Rider Pallet Jacks and Stackers — walk-behind or ride-on pallet movers." },
        { front: "Class IV", back: "Internal Combustion Rider Trucks with Cushion Tires — for smooth indoor floors." },
        { front: "Class V", back: "Internal Combustion Trucks with Pneumatic Tires — indoor/outdoor use on rougher surfaces." },
        { front: "Class VI", back: "Electric and IC Engine Tractors — tuggers that pull loads rather than lift them." },
        { front: "Class VII", back: "Rough Terrain Forklift Trucks — large-tire trucks for construction sites and yards." },
      ] },
      { type: "heading", level: 3, text: "Who Can Operate" },
      { type: "paragraph", html: "Only <strong>trained and authorized</strong> employees may operate a PIT. You must be at least <strong>18 years old</strong>. Your certification is valid for <strong>3 years</strong>, after which you must be re-evaluated." },
      { type: "heading", level: 3, text: "Employer vs. Operator Responsibilities" },
      { type: "list", items: [
        "<strong>Employer:</strong> Must provide training, ensure equipment is maintained, enforce safety rules",
        "<strong>Operator:</strong> Must follow all safety rules, perform pre-shift inspections, report hazards and incidents immediately",
      ] },
      { type: "key_takeaways", items: [
        "A PIT is any powered vehicle used to move, lift, or stack materials",
        "There are 7 OSHA classifications of powered industrial trucks",
        "Operators must be 18+ years old, trained, and authorized",
        "Certification is valid for 3 years",
      ] },
    ]),
  },
  {
    module: "Forklift Basics & Responsibilities",
    title: "Authorization & Safe Work Culture",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: photo("operator-at-controls-scene.svg"), alt: "Operator seated at forklift controls wearing hi-vis vest and seat belt" },
      { type: "heading", level: 2, text: "Authorization & Safe Work Culture" },
      { type: "heading", level: 3, text: "Reporting Hazards" },
      { type: "paragraph", html: "As an operator, you are responsible for immediately reporting any unsafe conditions: damaged equipment, spills, obstructions, poor lighting, or near-miss incidents. Never assume someone else will report it." },
      { type: "heading", level: 3, text: "No Passengers — Ever" },
      { type: "paragraph", html: "Your forklift is designed to safely transport <strong>only one person — the operator</strong>. Never allow riders on the forks, sides, or any part of the truck unless using an OSHA-approved safety platform with guardrails, toe boards, and a fall protection harness." },
      { type: "heading", level: 3, text: "Stay Alert" },
      { type: "list", items: [
        "No cell phone use while operating",
        "No headphones or earbuds",
        "No horseplay or stunt driving",
        "Keep your entire body inside the protective cage at all times",
        "Never operate under the influence of drugs or alcohol",
      ] },
      { type: "heading", level: 3, text: "OSHA Enforcement" },
      { type: "paragraph", html: "OSHA can conduct <strong>unannounced inspections</strong>. Fines for uncertified operators can reach <strong>$7,000 per day per unqualified employee</strong>, retroactive to the hire date. A single uncertified operator working for one year could result in nearly <strong>$2 million</strong> in fines." },
      { type: "callout", variant: "warning", text: "Stunt driving and horseplay are strictly prohibited and can result in termination and OSHA violations." },
      { type: "key_takeaways", items: [
        "Report all hazards and incidents immediately",
        "No passengers unless using an approved safety platform",
        "Stay alert — no phones, headphones, or horseplay",
        "OSHA fines for non-compliance are severe",
      ] },
    ]),
  },
  {
    module: "Forklift Basics & Responsibilities",
    title: "Knowledge Check: Basics & Responsibilities",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "When is it acceptable to carry a passenger on a forklift?", type: "mcq_single", options: ["When driving slowly", "When an OSHA-approved safety platform with guardrails is properly attached", "During emergencies", "When the supervisor approves"], correctAnswers: "When an OSHA-approved safety platform with guardrails is properly attached", explanation: "Passengers are never allowed unless using an OSHA-approved work platform with guardrails, toe boards, and fall protection." },
      { question: "If you notice a minor oil leak on the forklift during pre-shift inspection, you should:", type: "mcq_single", options: ["Continue working and report at end of shift", "Report it immediately and do not operate until cleared", "Clean it up and keep working", "Only report if it gets worse"], correctAnswers: "Report it immediately and do not operate until cleared", explanation: "Any safety concern must be reported immediately. Vehicles should not be operated until they are deemed safe." },
      { question: "Your entire body must remain inside the forklift's protective cage at all times while operating.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "Keep all body parts inside the operator's area to avoid crush hazards with the mast, overhead guard, or surrounding objects." },
    ],
  },

  // ═══ MODULE 2: Stability + Load Handling ═══
  {
    module: "Stability & Load Handling",
    title: "Stability Triangle and Center of Gravity",
    type: "lesson",
    estimatedMinutes: 6,
    config: blocks([
      { type: "hero_image", src: img("stability-triangle.svg"), alt: "Top-down view of a forklift showing the stability triangle" },
      { type: "heading", level: 2, text: "Stability Triangle and Center of Gravity" },
      { type: "heading", level: 3, text: "What is the Stability Triangle?" },
      { type: "paragraph", html: "The <strong>stability triangle</strong> is the three-point base formed by the two front axle ends and the rear axle pivot point. As long as the combined center of gravity of the truck and its load stays within this triangle, the forklift remains stable." },
      { type: "hotspot_diagram", src: img("stability-triangle.svg"), alt: "Stability triangle diagram with front axle, rear pivot, and center of gravity",
        caption: "Tap each point of the triangle to understand how stability works.",
        hotspots: [
          { x: 38, y: 47, label: "Front Axle (drive wheels)", description: "The two front wheel contact points form the wide base of the triangle. Most of the machine + load weight rides here." },
          { x: 50, y: 73, label: "Rear Axle Pivot", description: "The rear axle pivots on a single center point — that is the third corner of the triangle, NOT the two rear wheels. This is why forklifts feel tippy in turns." },
          { x: 50, y: 56, label: "Center of Gravity", description: "With no load, the CG sits near the middle of the triangle. Lifting, tilting, and turning all move it. Keep it inside the triangle or the truck tips." },
          { x: 50, y: 84, label: "Tip-Over Zone", description: "If the combined CG crosses outside the triangle — from overloading, raised loads, sharp turns, or slopes — the forklift tips toward that side." },
        ] },
      { type: "heading", level: 3, text: "See It In Motion" },
      { type: "image", src: img("stability-triangle-animated.svg"), alt: "Animation of the center of gravity moving outside the stability triangle", caption: "Watch how raising a load pushes the center of gravity toward the edge of the triangle." },
      { type: "heading", level: 3, text: "Tip-Over Risk" },
      { type: "paragraph", html: "When the center of gravity shifts outside the stability triangle — due to overloading, sharp turns, or operating on slopes — the forklift can <strong>tip over</strong>. Tip-overs are one of the leading causes of forklift fatalities." },
      { type: "list", items: [
        "Never make sharp turns at speed",
        "Reduce speed before turning",
        "Be extra cautious on ramps, slopes, and uneven surfaces",
      ] },
      { type: "heading", level: 3, text: "Lateral Stability" },
      { type: "paragraph", html: "Turning too quickly shifts the center of gravity sideways. The higher the load, the more unstable the truck becomes during turns. Always <strong>slow down before turning</strong>, not during the turn." },
      { type: "callout", variant: "warning", text: "Tip-overs are among the leading causes of forklift operator fatalities. Always respect the stability triangle." },
      { type: "key_takeaways", items: [
        "The stability triangle is formed by the front axle ends and rear axle pivot",
        "Keep the center of gravity within the triangle to prevent tip-overs",
        "Reduce speed before turns — sharp turns cause lateral instability",
        "Higher loads mean greater tip-over risk during turns",
      ] },
    ]),
  },
  {
    module: "Stability & Load Handling",
    title: "Rated Capacity & Data Plate",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("load-center.svg"), alt: "Diagram of load center distance and capacity" },
      { type: "heading", level: 2, text: "Rated Capacity & Data Plate" },
      { type: "heading", level: 3, text: "The Data Plate" },
      { type: "paragraph", html: "Every forklift has a manufacturer's <strong>data plate</strong> indicating the maximum lifting capacity at various load centers. Before lifting any load, verify your forklift is rated to handle its weight." },
      { type: "heading", level: 3, text: "Load Center" },
      { type: "paragraph", html: "The <strong>load center</strong> is the distance from the fork's vertical face to the center of the load. A forklift's capacity decreases as the load center increases. Always verify you're using the right equipment for the weight and size of the load." },
      { type: "image", src: img("load-center-animated.svg"), alt: "Animation showing capacity dropping as the load center grows", caption: "As the load center grows from 24 to 36 inches, the same truck can safely lift far less." },
      { type: "drag_drop", mode: "matching",
        prompt: "Match each load center distance to the capacity this truck can safely lift.",
        items: [
          { id: "lc24", label: "24 in load center", targetId: "cap5000" },
          { id: "lc30", label: "30 in load center", targetId: "cap4000" },
          { id: "lc36", label: "36 in load center", targetId: "cap3300" },
        ],
        targets: [
          { id: "cap5000", label: "5,000 lbs — full rated capacity" },
          { id: "cap4000", label: "4,000 lbs — reduced capacity" },
          { id: "cap3300", label: "3,300 lbs — lowest capacity" },
        ] },
      { type: "heading", level: 3, text: "Attachments Reduce Capacity" },
      { type: "paragraph", html: "Using attachments (clamps, rotators, fork extensions) changes the truck's center of gravity and <strong>reduces the rated capacity</strong>. Always check the adjusted capacity when using any attachment." },
      { type: "heading", level: 3, text: "Never Overload" },
      { type: "paragraph", html: "Exceeding the rated capacity greatly increases the risk of instability and tip-over. Display weight limits clearly on the vehicle. If a load seems too heavy or unbalanced, do not attempt to lift it — get a higher-capacity truck." },
      { type: "key_takeaways", items: [
        "Always check the data plate for rated capacity before lifting",
        "Capacity decreases as load center distance increases",
        "Attachments reduce the forklift's rated capacity",
        "Never exceed the rated capacity — use a larger truck if needed",
      ] },
    ]),
  },
  {
    module: "Stability & Load Handling",
    title: "Picking Up and Carrying Loads Safely",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: photo("forklift-lifting-scene.svg"), alt: "Forklift placing a pallet on a rack level" },
      { type: "heading", level: 2, text: "Picking Up and Carrying Loads Safely" },
      { type: "heading", level: 3, text: "Fork Position" },
      { type: "paragraph", html: "Carry forks as low as possible — typically <strong>4 to 6 inches</strong> from the ground. This lowers the center of gravity and reduces the risk of tip-over." },
      { type: "heading", level: 3, text: "Mast Tilt" },
      { type: "paragraph", html: "Tilt the mast slightly back when traveling with a load to stabilize it. Never tilt loads forward except when depositing them. Excessive forward tilt can cause the truck to tip." },
      { type: "heading", level: 3, text: "Visibility" },
      { type: "paragraph", html: "If a load blocks your forward view, <strong>drive in reverse</strong> to maintain a clear line of sight. Use spotters when navigating tight spaces or areas with limited visibility." },
      { type: "heading", level: 3, text: "Securing Loads" },
      { type: "paragraph", html: "Before transporting any load, ensure it is <strong>properly secured and balanced</strong>. You may need shrink-wrap or straps to prevent shifting or spilling during transport. Never move an unsecured load." },
      { type: "embedded_quiz", questions: [
        { question: "You pick up a wrapped pallet and realize it completely blocks your forward view. What do you do?", type: "mcq_single", options: ["Lean out the side to see around it", "Raise the load higher so you can see under it", "Travel in reverse with a clear line of sight", "Drive forward slowly and honk"], correctAnswers: "Travel in reverse with a clear line of sight", explanation: "When the load blocks your forward view, travel in reverse so you can see where you are going. Never lean outside the cage or raise the load to see under it." },
        { question: "While carrying a load, the mast should be tilted:", type: "mcq_single", options: ["Fully forward", "Slightly back", "It doesn't matter", "Fully down"], correctAnswers: "Slightly back", explanation: "A slight back tilt cradles the load against the backrest and keeps it stable during travel." },
      ] },
      { type: "callout", variant: "tip", text: "When you can't see past the load, travel in reverse and use a spotter for tight areas." },
      { type: "key_takeaways", items: [
        "Carry forks 4–6 inches from the ground",
        "Tilt the mast back when traveling with a load",
        "Drive in reverse if the load blocks your forward view",
        "Always ensure loads are secured before moving",
      ] },
    ]),
  },
  {
    module: "Stability & Load Handling",
    title: "Knowledge Check: Stability & Loads",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "When traveling with a load, forks should be:", type: "mcq_single", options: ["Raised as high as possible", "At eye level", "4 to 6 inches from the ground", "Touching the ground"], correctAnswers: "4 to 6 inches from the ground", explanation: "Carrying forks 4–6 inches from the ground keeps the center of gravity low and reduces tip-over risk." },
      { question: "Using attachments on a forklift affects the:", type: "mcq_single", options: ["Color of the forklift", "Rated capacity — it is reduced", "Horn volume", "Tire pressure"], correctAnswers: "Rated capacity — it is reduced", explanation: "Attachments change the center of gravity and reduce the forklift's rated lifting capacity." },
      { question: "You should slow down before entering a turn, not during the turn.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "Slowing down during a turn increases lateral instability. Always reduce speed before you begin turning." },
      { question: "If a load is too heavy for your forklift, you should:", type: "mcq_single", options: ["Try to lift it carefully", "Use a larger-capacity truck", "Add counterweight to the back", "Drive faster for momentum"], correctAnswers: "Use a larger-capacity truck", explanation: "Never exceed rated capacity. Get the right equipment for the job." },
    ],
  },

  // ═══ MODULE 3: Pre-Operation Inspection + Fueling/Charging ═══
  {
    module: "Pre-Operation Inspection & Fueling",
    title: "Pre-Shift Inspection Checklist",
    type: "lesson",
    estimatedMinutes: 6,
    config: blocks([
      { type: "hero_image", src: photo("pre-inspection-scene.svg"), alt: "Operator inspecting forklift forks with a checklist before a shift" },
      { type: "heading", level: 2, text: "Pre-Shift Inspection Checklist" },
      { type: "heading", level: 3, text: "Your Responsibility" },
      { type: "paragraph", html: "As the operator, it is <strong>your responsibility</strong> to conduct a daily safety inspection before using the machine. This must be done at the <strong>start of each shift</strong>." },
      { type: "heading", level: 3, text: "Walk-Around Inspection" },
      { type: "paragraph", html: "Do a full walk-around before you climb on. Tap each point on the forklift to see what to check." },
      { type: "hotspot_diagram", src: img("forklift-anatomy.svg"), alt: "Forklift walkaround inspection points",
        caption: "A complete walk-around takes less than 5 minutes and can save a life.",
        hotspots: [
          { x: 46, y: 79, label: "Tires & Wheels", description: "Check for cuts, chunks missing, proper inflation (pneumatic), and debris wrapped around axles." },
          { x: 73, y: 86, label: "Forks", description: "Look for cracks, bends, and heel wear. Check the fork locking pins. Bent or cracked forks mean the truck is out of service." },
          { x: 56, y: 35, label: "Mast & Lift Chains", description: "Inspect chains for kinks, rust, and broken links. Check that the mast raises, lowers, and tilts smoothly without jerking." },
          { x: 40, y: 63, label: "Hydraulics & Leaks", description: "Look under the truck for fresh fluid spots. Check hoses and cylinders for leaks. A hydraulic leak means DO NOT OPERATE." },
          { x: 36, y: 31, label: "Overhead Guard", description: "Check for bent posts, cracks, or missing bolts. The guard is your protection from falling loads." },
          { x: 46, y: 69, label: "Data Plate", description: "Must be present and legible. If you cannot read the rated capacity, do not operate the truck." },
          { x: 34, y: 53, label: "Seat & Seat Belt", description: "Test that the seat belt latches and retracts. Buckle up before starting the engine — every single time." },
          { x: 42, y: 56, label: "Horn, Lights & Alarm", description: "Test the horn, headlights, warning lights, and backup alarm. If pedestrians can't hear you coming, the truck is not safe." },
        ] },
      { type: "heading", level: 3, text: "Also Check" },
      { type: "list", items: [
        "<strong>Brakes:</strong> Test both service and parking brakes",
        "<strong>Steering:</strong> Check for responsiveness",
        "<strong>Fluid levels:</strong> Fuel, oil, coolant, hydraulic fluid",
      ] },
      { type: "heading", level: 3, text: "Tag Out Unsafe Equipment" },
      { type: "paragraph", html: "If you find any safety issue, <strong>do not operate the forklift</strong>. Report the problem to your supervisor or maintenance team immediately. Tag out the equipment so no one else uses it until repairs are completed." },
      { type: "embedded_quiz", questions: [
        { question: "During your walk-around you find a slow hydraulic drip under the mast. The truck seems to work fine. What now?", type: "mcq_single", options: ["Operate carefully and re-check at lunch", "Wipe it clean and keep working", "Tag out the truck and report it — do not operate", "Add hydraulic fluid to compensate"], correctAnswers: "Tag out the truck and report it — do not operate", explanation: "Any hydraulic leak can lead to sudden loss of load control. Tag out and report — never operate a leaking truck." },
      ] },
      { type: "callout", variant: "tip", text: "Always buckle your seat belt before starting the engine — it's your primary protection in a tip-over." },
      { type: "key_takeaways", items: [
        "Pre-shift inspection is required before every shift",
        "Check tires, forks, chains, hydraulics, lights, horn, brakes, steering",
        "Tag out and report any unsafe equipment immediately",
        "Never operate a forklift that fails inspection",
      ] },
    ]),
  },
  {
    module: "Pre-Operation Inspection & Fueling",
    title: "Maintenance and Repairs",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Forklift inspection points diagram" },
      { type: "heading", level: 2, text: "Maintenance and Repairs" },
      { type: "heading", level: 3, text: "Repair Before Use" },
      { type: "paragraph", html: "If a safety issue is identified during inspection, <strong>repairs must be made before the equipment is used</strong>. Never operate a forklift with known defects." },
      { type: "heading", level: 3, text: "Fluid Leaks" },
      { type: "paragraph", html: "Do not operate any vehicle with <strong>fuel, oil, or hydraulic leaks</strong>. Hydraulic leaks can lead to sudden loss of load control, creating an extremely dangerous situation." },
      { type: "heading", level: 3, text: "Document and Report" },
      { type: "paragraph", html: "All maintenance issues must be documented and reported. This creates a paper trail for compliance and helps prevent recurring issues." },
      { type: "key_takeaways", items: [
        "Repairs must be completed before the equipment is used",
        "Never operate a forklift with any fluid leaks",
        "Document all maintenance issues for compliance",
      ] },
    ]),
  },
  {
    module: "Pre-Operation Inspection & Fueling",
    title: "Fueling and Charging Safety",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("ppe-gloves.svg"), alt: "Required PPE for fueling: gloves, vest, hard hat, eye protection" },
      { type: "heading", level: 2, text: "Fueling and Charging Safety (LPG / Electric)" },
      { type: "heading", level: 3, text: "Designated Areas Only" },
      { type: "paragraph", html: "Refueling and recharging must <strong>only occur in designated areas</strong> with proper ventilation. Never refuel in general work areas." },
      { type: "heading", level: 3, text: "PPE Requirements" },
      { type: "list", items: [
        "Wear <strong>gloves</strong> when handling LPG tanks",
        "Wear <strong>eye protection</strong> as applicable",
        "Follow your facility's specific PPE requirements",
      ] },
      { type: "heading", level: 3, text: "No Smoking" },
      { type: "paragraph", html: "Employees are <strong>strictly prohibited from smoking</strong> or using any open flame while operating a forklift. Sparks or open flames must remain at least <strong>50 feet away</strong> from fueling stations and battery recharging areas." },
      { type: "flip_cards", title: "LPG vs. Electric — Know Your Fuel", cards: [
        { front: "LPG (Propane)", back: "Wear gloves — liquid propane causes frostbite. Check for leaks after connecting, secure the tank, and report any gas smell immediately." },
        { front: "Electric (Battery)", back: "Turn off the charger before connecting or disconnecting. Charging produces explosive hydrogen gas — ventilation is mandatory." },
      ] },
      { type: "callout", variant: "warning", text: "No smoking, open flames, or sparks near fueling or charging areas. Hydrogen gas from charging batteries is highly explosive." },
      { type: "key_takeaways", items: [
        "Refuel/recharge only in designated, ventilated areas",
        "Wear gloves when handling LPG tanks",
        "No smoking within 50 feet of fueling/charging areas",
        "Always check for leaks after connecting LPG tanks",
      ] },
    ]),
  },
  {
    module: "Pre-Operation Inspection & Fueling",
    title: "Knowledge Check: Inspections & Fueling",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "If a safety issue is found during pre-shift inspection, repairs must be completed:", type: "mcq_single", options: ["By end of day", "Before the equipment is used", "Within a week", "Only if a supervisor requests it"], correctAnswers: "Before the equipment is used", explanation: "Repairs must be made before use if the equipment is unsafe. Never operate a defective forklift." },
      { question: "Gloves should be worn when handling LPG (propane) tanks.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "LPG can cause frostbite on contact with skin. Gloves provide essential protection." },
      { question: "Is it acceptable to smoke near a forklift charging station as long as you're careful?", type: "mcq_single", options: ["Yes, if no gas is visible", "No, never within 50 feet", "Only during breaks", "Only outdoors"], correctAnswers: "No, never within 50 feet", explanation: "Smoking and open flames must remain at least 50 feet from fueling and charging areas due to explosive gas risk." },
    ],
  },

  // ═══ MODULE 4: Safe Driving + Pedestrians + Intersections ═══
  {
    module: "Safe Driving & Pedestrians",
    title: "Speed, Space, and Awareness",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("safe-driving.svg"), alt: "Proper driving posture with seat belt, low load, and eyes forward" },
      { type: "heading", level: 2, text: "Speed, Space, and Awareness" },
      { type: "heading", level: 3, text: "Speed Limits" },
      { type: "paragraph", html: "The maximum safe speed for operating a forklift is typically <strong>5 mph</strong>. Forklifts are designed to move heavy loads, not to race. Focus on working <strong>efficiently, not faster</strong>." },
      { type: "heading", level: 3, text: "Stopping Distance" },
      { type: "paragraph", html: "Maintain adequate stopping distance at all times. Keep at least <strong>three vehicle lengths</strong> or a <strong>3-second gap</strong> between vehicles." },
      { type: "heading", level: 3, text: "Surface Conditions" },
      { type: "paragraph", html: "Be aware of wet floors, debris, oil spills, and uneven surfaces. These conditions significantly increase stopping distance and tip-over risk. Slow down and navigate carefully." },
      { type: "embedded_quiz", questions: [
        { question: "Another forklift is working in the same aisle ahead of you. How much space should you keep?", type: "mcq_single", options: ["One vehicle length", "Half an aisle", "At least three vehicle lengths", "Enough to see their forks"], correctAnswers: "At least three vehicle lengths", explanation: "Keep at least three vehicle lengths (about a 3-second gap) so you can stop safely if they brake suddenly." },
      ] },
      { type: "key_takeaways", items: [
        "Maximum safe speed is typically 5 mph",
        "Maintain at least 3 vehicle lengths between trucks",
        "Wet floors and debris increase stopping distance",
        "Efficiency comes from smooth operation, not speed",
      ] },
    ]),
  },
  {
    module: "Safe Driving & Pedestrians",
    title: "Intersections, Blind Spots, and Horn Use",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Warehouse aisle with clearance zones" },
      { type: "heading", level: 2, text: "Intersections, Blind Spots, and Horn Use" },
      { type: "heading", level: 3, text: "Approach With Caution" },
      { type: "paragraph", html: "At every intersection, blind corner, or area with limited visibility: <strong>slow down, sound your horn, and look both ways</strong> before proceeding." },
      { type: "heading", level: 3, text: "Mirrors and Visibility" },
      { type: "paragraph", html: "Use available mirrors and look in the direction of travel. If a load blocks your forward view, travel in reverse. Never pass at intersections, blind spots, or hazardous areas." },
      { type: "heading", level: 3, text: "Horn Protocol" },
      { type: "paragraph", html: "The horn is a <strong>warning device</strong>, not a demand for right-of-way. Sound it at intersections, blind corners, doorways, and whenever pedestrians may be present. Use it to alert others to your presence." },
      { type: "key_takeaways", items: [
        "Slow down, honk, and look at every intersection",
        "Use mirrors and drive in reverse when view is blocked",
        "The horn warns others — it doesn't give you right-of-way",
        "Never pass at intersections or blind spots",
      ] },
    ]),
  },
  {
    module: "Safe Driving & Pedestrians",
    title: "Pedestrian Right of Way",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: photo("pedestrian-crossing-scene.svg"), alt: "Forklift yielding to a pedestrian in a marked walkway" },
      { type: "heading", level: 2, text: "Pedestrian Right of Way" },
      { type: "heading", level: 3, text: "Pedestrians Always Have Priority" },
      { type: "paragraph", html: "Pedestrians <strong>always have the right of way</strong>. Never drive toward a person near a fixed object. Always ensure people are clear before moving." },
      { type: "image", src: img("pedestrian-safety.svg"), alt: "Diagram of forklift blind spots and pedestrian separation zones", caption: "Blind spots extend behind the truck and around the mast — assume pedestrians don't see you." },
      { type: "heading", level: 3, text: "Communication" },
      { type: "list", items: [
        "Make <strong>eye contact</strong> with pedestrians before proceeding",
        "Sound the horn as a <strong>warning</strong>, not as a demand to move",
        "Wait for pedestrians to acknowledge you and move to safety",
      ] },
      { type: "scenario", title: "What Would You Do?",
        prompt: "You are carrying a pallet down the main aisle at walking speed. Twenty feet ahead, a coworker steps out from between two racks reading a clipboard. They have not seen you.",
        choices: [
          { text: "Sound the horn repeatedly and keep moving — they'll step back", correct: false, feedback: "The horn is a warning, not a demand for right of way. A startled pedestrian may step the wrong way. You must stop until they are clear." },
          { text: "Stop, sound the horn once, and wait for eye contact before proceeding", correct: true, feedback: "Exactly right. Pedestrians always have the right of way. Stop, warn, make eye contact, and only proceed once they are clearly out of your path." },
          { text: "Steer around them while keeping your speed", correct: false, feedback: "Never swerve around a pedestrian who hasn't seen you — they may move into your new path, and sharp steering with a load risks a tip-over." },
        ] },
      { type: "heading", level: 3, text: "Pedestrian Zones" },
      { type: "paragraph", html: "Be especially alert in areas where pedestrians commonly walk: near break rooms, restrooms, offices, shipping/receiving areas, and anywhere workers cross forklift paths." },
      { type: "key_takeaways", items: [
        "Pedestrians always have the right of way",
        "Make eye contact before proceeding near people",
        "Sound the horn as a warning, not a demand",
        "Be extra alert near break rooms, offices, and crossing areas",
      ] },
    ]),
  },
  {
    module: "Safe Driving & Pedestrians",
    title: "Direction Changes and Smooth Handling",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: img("safe-driving.svg"), alt: "Safe driving posture and smooth handling" },
      { type: "heading", level: 2, text: "Direction Changes and Smooth Handling" },
      { type: "heading", level: 3, text: "Complete Stop Before Direction Change" },
      { type: "paragraph", html: "Always come to a <strong>complete stop</strong> before changing from forward to reverse or vice versa. Abrupt direction changes can cause loads to shift or fall, and increase tip-over risk." },
      { type: "heading", level: 3, text: "Smooth Movements" },
      { type: "paragraph", html: "Smooth acceleration, braking, and steering prevent load shifts, spills, and tip-overs. Jerky movements are the enemy of stability." },
      { type: "heading", level: 3, text: "Do Not Accelerate While Turning" },
      { type: "paragraph", html: "Accelerating during a turn significantly increases the risk of tipping. The unique weight distribution of a forklift, combined with a heavy load, makes it easy to lose control if not handled carefully." },
      { type: "key_takeaways", items: [
        "Come to a complete stop before changing direction",
        "Smooth acceleration and braking prevent load shifts",
        "Never accelerate while turning",
        "Jerky movements increase tip-over risk",
      ] },
    ]),
  },
  {
    module: "Safe Driving & Pedestrians",
    title: "Knowledge Check: Safe Driving",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "The primary purpose of the forklift horn is to:", type: "mcq_single", options: ["Demand right of way", "Warn others of your presence", "Signal that you're speeding", "Request pedestrians to move faster"], correctAnswers: "Warn others of your presence", explanation: "The horn is a warning device to alert others to the forklift's presence, not a demand for right-of-way." },
      { question: "Pedestrians always have the right of way around forklifts.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "Pedestrians always have priority. Operators must yield to pedestrians at all times." },
      { question: "When approaching an intersection, you should:", type: "mcq_single", options: ["Speed up to clear it quickly", "Stop, sound horn, and look both ways", "Flash your headlights", "Assume no one is coming"], correctAnswers: "Stop, sound horn, and look both ways", explanation: "Operators must slow down/stop, sound the horn, and look before proceeding through any intersection." },
      { question: "The safest way to change direction (forward to reverse) is to:", type: "mcq_single", options: ["Come to a complete stop first", "Shift quickly while moving", "Turn the steering wheel sharply", "Accelerate through the change"], correctAnswers: "Come to a complete stop first", explanation: "Always stop completely before changing direction to prevent load shifts and maintain stability." },
      { question: "It's okay to speed if no one else is around.", type: "mcq_single", options: ["True", "False"], correctAnswers: "False", explanation: "Speed limits apply at all times regardless of whether other people are present. Hazards can appear unexpectedly." },
    ],
  },

  // ═══ MODULE 5: Ramps, Docks, Trailers, and Elevated Work ═══
  {
    module: "Ramps, Docks & Elevated Work",
    title: "Ramps and Slopes",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("ramps-slopes.svg"), alt: "Forklift on a ramp with the load pointed upgrade" },
      { type: "heading", level: 2, text: "Ramps and Slopes" },
      { type: "heading", level: 3, text: "Loaded Travel on Ramps" },
      { type: "paragraph", html: "When traveling on a ramp <strong>with a load</strong>: keep the load pointed <strong>uphill</strong> (upgrade). This means driving forward up a ramp and in reverse down a ramp when loaded." },
      { type: "heading", level: 3, text: "Unloaded Travel on Ramps" },
      { type: "paragraph", html: "When traveling on a ramp <strong>without a load</strong>: the forks should point <strong>downhill</strong> (downgrade)." },
      { type: "scenario", title: "Ramp Decision",
        prompt: "You picked up a full pallet on the upper level and need to take it DOWN the ramp to ground level. What is the correct way to descend?",
        choices: [
          { text: "Drive forward down the ramp — you can see better", correct: false, feedback: "With the load pointed downhill, gravity pulls the pallet off the forks and the combined center of gravity shifts toward the front axle — a recipe for losing the load or tipping." },
          { text: "Back down the ramp so the load stays pointed uphill", correct: true, feedback: "Correct. Loaded on a ramp = load always points upgrade. Going down, that means traveling in reverse, slowly, looking over your shoulder or using a spotter." },
          { text: "Turn around halfway down to face the load uphill", correct: false, feedback: "Never turn on a ramp. Turning shifts the center of gravity sideways on an incline — this is one of the highest tip-over-risk maneuvers possible." },
        ] },
      { type: "heading", level: 3, text: "Ramp Safety Rules" },
      { type: "list", items: [
        "Ascend and descend slowly",
        "On steep grades (>10%), travel with load upgrade",
        "Tilt load back slightly for stability",
        "<strong>Never turn on a ramp</strong> — the risk of tip-over is extremely high",
        "Never park on a ramp unless absolutely necessary (chock wheels if you must)",
      ] },
      { type: "callout", variant: "warning", text: "Turning on a ramp dramatically increases tip-over risk. Always travel straight up or down." },
      { type: "key_takeaways", items: [
        "Loaded: keep load pointed uphill (upgrade)",
        "Unloaded: forks pointed downhill (downgrade)",
        "Never turn on a ramp — extreme tip-over risk",
        "Travel slowly and tilt the load back slightly",
      ] },
    ]),
  },
  {
    module: "Ramps, Docks & Elevated Work",
    title: "Docks and Trailer Safety",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: photo("dock-loading-scene.svg"), alt: "Forklift entering a trailer over a dock plate at a loading dock" },
      { type: "heading", level: 2, text: "Docks and Trailer Safety" },
      { type: "heading", level: 3, text: "Before Entering a Trailer" },
      { type: "list", items: [
        "Verify the trailer is <strong>properly chocked</strong> (wheel chocks in place)",
        "Confirm the trailer <strong>brakes are set</strong>",
        "Check the condition of the trailer floor — look for rot, holes, or weakness",
        "Ensure a <strong>dock plate</strong> is properly positioned",
      ] },
      { type: "heading", level: 3, text: "Know the Dock Hazards" },
      { type: "paragraph", html: "Dock areas pack several serious hazards into a small space. Tap each marker to learn what to check." },
      { type: "hotspot_diagram", src: img("dock-scene.svg"), alt: "Cross-section of a loading dock with trailer, dock plate, and wheel chocks",
        hotspots: [
          { x: 54, y: 67, label: "Dock Plate", description: "Must be rated for your truck's weight, properly seated, and secured before you cross. Never jump the gap — enter straight and slow, forks 4–6 inches up." },
          { x: 31, y: 88, label: "Wheel Chocks", description: "Chocks against the trailer wheels stop it from creeping away from the dock. Verify them yourself — do not take anyone's word for it." },
          { x: 31, y: 62, label: "Trailer Floor", description: "Check for rot, holes, and weak boards before driving in. Confirm the trailer's landing gear or nose support if the tractor is detached." },
          { x: 61, y: 67, label: "Dock Edge", description: "An open dock is a 4-foot drop. Stay at least one tire-width from the edge and never operate near an unprotected open dock door." },
          { x: 59, y: 73, label: "Trailer Creep Gap", description: "Every forklift entry pushes the trailer slightly. Watch the gap between trailer and dock — a growing gap means the trailer is creeping and must be re-secured." },
        ] },
      { type: "heading", level: 3, text: "Trailer Movement" },
      { type: "paragraph", html: "A forklift's braking force can cause an unbraked trailer to move away from the dock, potentially trapping the forklift inside. <strong>Always verify chocks and brakes</strong> before entering." },
      { type: "key_takeaways", items: [
        "Always verify chocks and brakes before entering a trailer",
        "Use a dock plate — never jump the gap",
        "Check trailer floor condition before driving on it",
        "Maintain at least one tire-width from dock edges",
      ] },
    ]),
  },
  {
    module: "Ramps, Docks & Elevated Work",
    title: "Lifting People and Elevated Work",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: photo("aerial-lift-scene.svg"), alt: "Worker in a harness on an elevated platform with a ground guard below" },
      { type: "heading", level: 2, text: "Lifting People and Elevated Work" },
      { type: "heading", level: 3, text: "Never Lift People on Bare Forks" },
      { type: "paragraph", html: "It is <strong>never acceptable</strong> to lift a person on the forks without an approved safety platform. This includes standing on pallets, buckets, or any makeshift platform." },
      { type: "heading", level: 3, text: "Approved Safety Platforms" },
      { type: "list", items: [
        "<strong>42-inch guardrails</strong> on all sides",
        "Mid-rail positioned halfway between top rail and platform",
        "<strong>4-inch toe boards</strong>",
        "Secure attachment to the mast (chain or locking device)",
        "<strong>7-foot overhead guard</strong> for crush protection",
        "Personal fall protection (safety line and harness)",
      ] },
      { type: "heading", level: 3, text: "Operator Responsibilities During Elevation" },
      { type: "paragraph", html: "When lifting a person in a platform: the engine must remain running, the operator must <strong>stay at the controls at all times</strong>, and the forklift must not be driven to another location with a person elevated." },
      { type: "key_takeaways", items: [
        "Never lift people on bare forks or makeshift platforms",
        "Only use OSHA-approved platforms with guardrails and fall protection",
        "Operator must remain at the controls while someone is elevated",
        "Never move the forklift with a person elevated in a platform",
      ] },
    ]),
  },
  {
    module: "Ramps, Docks & Elevated Work",
    title: "Knowledge Check: Ramps, Docks & Elevation",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "When traveling UP a ramp with a load, the load should face:", type: "mcq_single", options: ["Downhill", "Uphill", "It doesn't matter", "Sideways"], correctAnswers: "Uphill", explanation: "When traveling on a ramp with a load, keep the load pointed uphill (upgrade) to prevent the load from sliding off the forks." },
      { question: "Is it acceptable to lift a maintenance worker on the forks without a safety platform?", type: "mcq_single", options: ["Yes, if they hold on", "No, never without an approved safety platform", "Yes, for quick tasks", "Only with supervisor approval"], correctAnswers: "No, never without an approved safety platform", explanation: "Lifting people on bare forks is never acceptable. An OSHA-approved safety platform with guardrails, toe boards, and fall protection is required." },
      { question: "An OSHA-approved safety platform must include guardrails, toe boards, and fall protection.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "Approved platforms must have 42-inch guardrails, mid-rails, 4-inch toe boards, secure mast attachment, overhead guard, and personal fall protection." },
    ],
  },

  // ═══ MODULE 6: Parking, Unattended Forklift, and Shutdown ═══
  {
    module: "Parking & Shutdown",
    title: "Parking and Securing the Forklift",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("parking-shutdown.svg"), alt: "Parked forklift with forks lowered, chocked wheel, and shutdown steps" },
      { type: "heading", level: 2, text: "Parking and Securing the Forklift" },
      { type: "heading", level: 3, text: "Parking Procedure" },
      { type: "paragraph", html: "Every shutdown follows the same sequence. Put the steps in order — you will do this at the end of every shift for the rest of your career." },
      { type: "drag_drop", mode: "ordering",
        prompt: "Arrange the parking procedure steps in the correct order.",
        items: [
          { id: "p1", label: "Lower forks completely flat to the ground" },
          { id: "p2", label: "Tilt forks slightly forward" },
          { id: "p3", label: "Set the parking brake" },
          { id: "p4", label: "Neutralize all controls" },
          { id: "p5", label: "Turn off the engine / power" },
          { id: "p6", label: "Remove the key" },
        ] },
      { type: "heading", level: 3, text: "Parking Location" },
      { type: "paragraph", html: "Park only in <strong>designated areas</strong>. Never block fire exits, emergency equipment, or traffic lanes. If parking on an incline, chock the wheels." },
      { type: "key_takeaways", items: [
        "Lower forks, set brake, neutralize controls, turn off engine, remove key",
        "Park only in designated areas",
        "Never block fire exits or emergency equipment",
        "Chock wheels if parking on an incline",
      ] },
    ]),
  },
  {
    module: "Parking & Shutdown",
    title: "Unattended Forklift Definition",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: img("parking-shutdown.svg"), alt: "Forklift parked and secured" },
      { type: "heading", level: 2, text: "Unattended Forklift: When and What To Do" },
      { type: "heading", level: 3, text: "What 'Unattended' Means" },
      { type: "paragraph", html: "A forklift is considered <strong>unattended</strong> when the operator is <strong>more than 25 feet away</strong> from the vehicle AND the vehicle is <strong>out of their line of sight</strong>." },
      { type: "heading", level: 3, text: "Unattended Procedure" },
      { type: "list", items: [
        "Shut off power",
        "Set brakes",
        "Lower forks fully",
        "Return mast to vertical",
        "Remove the key to prevent unauthorized use",
        "Block wheels if on an incline",
      ] },
      { type: "heading", level: 3, text: "Temporarily Dismounted (Within 25 Feet)" },
      { type: "paragraph", html: "If you are within 25 feet and have the forklift in your line of sight:" },
      { type: "list", items: [
        "Lower forks",
        "Neutralize controls",
        "Set brakes",
      ] },
      { type: "paragraph", html: "You do not need to remove the key in this case, but the forklift must be secured." },
      { type: "heading", level: 3, text: "Reporting Accidents" },
      { type: "paragraph", html: "Report <strong>all accidents</strong>, even minor ones — including minor scrapes, near-misses, and property damage. Failure to report can lead to disciplinary action and hides safety issues that need to be addressed." },
      { type: "key_takeaways", items: [
        "Unattended = 25+ feet away AND out of sight",
        "Full shutdown required when unattended: power off, brake set, key removed",
        "Within 25 feet: lower forks, neutralize controls, set brakes",
        "Report ALL accidents, even minor ones",
      ] },
    ]),
  },
  {
    module: "Parking & Shutdown",
    title: "Knowledge Check: Parking & Shutdown",
    type: "checkpoint",
    estimatedMinutes: 1,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "When leaving a forklift unattended, the correct steps include:", type: "mcq_single", options: ["Just turn off the engine", "Lower forks, set brake, turn off engine, remove key", "Set the brake only", "Nothing if it's just for a few minutes"], correctAnswers: "Lower forks, set brake, turn off engine, remove key", explanation: "When unattended: shut off power, set brakes, lower forks, return mast to vertical, and remove the key." },
      { question: "You should report accidents even if they seem minor.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "All accidents must be reported, including minor ones and near-misses. This helps identify and correct safety issues." },
    ],
  },

  // ═══ MODULE 7: Site-Specific Rules + Employer Packet ═══
  {
    module: "Site-Specific Rules & Employer Packet",
    title: "Site-Specific Training Matters",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Warehouse aisle showing site-specific clearances" },
      { type: "heading", level: 2, text: "Site-Specific Training Matters" },
      { type: "heading", level: 3, text: "Every Workplace Is Different" },
      { type: "paragraph", html: "Every worksite has unique hazards: narrow aisles, specific pedestrian traffic patterns, loading docks, racking configurations, cold storage areas, outdoor areas, and more. Your supervisor must review <strong>site-specific policies</strong> with you before you operate at any new location." },
      { type: "heading", level: 3, text: "Site-Specific Topics" },
      { type: "list", items: [
        "Facility speed limits and traffic patterns",
        "Designated parking and charging areas",
        "Pedestrian zones and crossings",
        "Emergency procedures and assembly points",
        "Communication protocols (radio, signals)",
        "Specific equipment types and attachments used",
      ] },
      { type: "heading", level: 3, text: "What Your Employer Owes You" },
      { type: "paragraph", html: "OSHA puts specific duties on your employer. Flip each card to see what they are responsible for." },
      { type: "flip_cards", title: "Employer Responsibilities", cards: [
        { front: "Practical Training", back: "Hands-on training on the specific equipment you will operate, at the actual worksite, before you work solo." },
        { front: "Evaluation", back: "A supervisor or qualified trainer must watch you operate and formally sign off on your competence." },
        { front: "Documentation", back: "Signed evaluation forms, permits, and attendance records kept on file — OSHA can request them during inspections." },
        { front: "Refresher Training", back: "Required after an accident or near-miss, when unsafe operation is observed, or when you move to new equipment or a new facility." },
        { front: "Re-Evaluation", back: "At least every 3 years, your employer must re-evaluate your performance to keep your certification current." },
      ] },
      { type: "key_takeaways", items: [
        "Every workplace has unique hazards that require site-specific training",
        "Your supervisor must review site policies before you operate",
        "Additional training is required for new equipment or facilities",
        "After accidents or observed unsafe behavior, retraining is required",
      ] },
    ]),
  },
  {
    module: "Site-Specific Rules & Employer Packet",
    title: "OSHA Rules & Regulations (Reference)",
    type: "download",
    estimatedMinutes: 1,
    config: {
      description: "This reference document outlines the essential OSHA safety standards for Powered Industrial Truck operators. Your training has been covered by the lessons in this course — this is provided as an additional reference.",
      downloads: [
        { label: "OSHA Guidelines for Safe Operation of PITs (PDF)", url: "/api/documents/osha-rules-regulations/download", filename: "OSHA-Guidelines-for-the-Safe-Operation-of-Powered-Industrial-Trucks.pdf" },
      ],
    },
  },
  {
    module: "Site-Specific Rules & Employer Packet",
    title: "Employer Practical Evaluation Packet",
    type: "download",
    estimatedMinutes: 2,
    config: {
      description: "Your employer must complete a hands-on evaluation before you can operate a forklift at their facility. Provide these forms to your supervisor. They include the performance evaluation checklist, operator permit/authorization form, and site attendance sheet.",
      downloads: [
        { label: "Performance Test (PDF)", url: "/api/documents/performance-evaluation/download", filename: "PERFORMANCE-TEST.pdf" },
        { label: "PIT Permit to Operate (PDF)", url: "/api/documents/operator-permit/download", filename: "Powered-Industrial-Truck-PIT-PERMIT-TO-OPERATE.pdf" },
        { label: "Attendance Form & Scheduling (PDF)", url: "/api/documents/attendance-sheet/download", filename: "ATTENDANCE-FORM-AND-SCHEDULING.pdf" },
      ],
      important: "Have your supervisor complete these forms and keep them on file. OSHA may request these records during inspections.",
    },
  },
  {
    module: "Site-Specific Rules & Employer Packet",
    title: "Site Presentation (Reference)",
    type: "download",
    estimatedMinutes: 1,
    config: {
      description: "This presentation covers OSHA guidelines, equipment types, safe operating procedures, and loading protocols. It serves as a comprehensive reference for forklift operators.",
      downloads: [
        { label: "Forklift Certified Training Presentation (PDF)", url: "/api/documents/site-presentation/download", filename: "Forklift-Certified-Training.pdf" },
      ],
    },
  },

  // ═══ MODULE 8: Final Exam + Completion ═══
  {
    module: "Final Exam & Completion",
    title: "Final Exam: Forklift Operator Certification",
    type: "exam",
    estimatedMinutes: 15,
    config: {
      passing_score: 80,
      max_attempts: 3,
      randomize_questions: true,
    },
    questions: [
      { question: "What is the maximum recommended safe speed for a forklift in a warehouse?", type: "mcq_single", options: ["3 mph", "5 mph", "10 mph", "15 mph"], correctAnswers: "5 mph", explanation: "OSHA recommends a maximum of 5 mph in warehouse environments." },
      { question: "Before operating a forklift at the start of each shift, you must:", type: "mcq_single", options: ["Start the engine and test it while driving", "Perform a pre-operation inspection", "Load cargo first to test the forks", "Check only the fuel level"], correctAnswers: "Perform a pre-operation inspection", explanation: "A complete pre-operation inspection must be performed before every shift." },
      { question: "Which OSHA standard covers powered industrial trucks (forklifts)?", type: "mcq_single", options: ["29 CFR 1910.176", "29 CFR 1910.178", "29 CFR 1910.180", "29 CFR 1926.602"], correctAnswers: "29 CFR 1910.178", explanation: "29 CFR 1910.178 is the specific OSHA standard for powered industrial trucks." },
      { question: "How often must forklift operators be re-evaluated per OSHA requirements?", type: "mcq_single", options: ["Every year", "Every 2 years", "Every 3 years", "Every 5 years"], correctAnswers: "Every 3 years", explanation: "OSHA requires operator re-evaluation at least every three years." },
      { question: "When traveling with a large load that blocks your forward view, you should:", type: "mcq_single", options: ["Drive slowly forward", "Travel in reverse to maintain a clear line of sight", "Honk repeatedly while driving forward", "Have someone walk ahead"], correctAnswers: "Travel in reverse to maintain a clear line of sight", explanation: "When a load obstructs forward vision, the operator should travel in reverse for a clear line of sight." },
      { question: "The stability triangle on a forklift is formed by:", type: "mcq_single", options: ["The dashboard warning lights", "The two front axle ends and the rear axle pivot point", "The three pedals", "The fuel gauge, temperature, and battery indicators"], correctAnswers: "The two front axle ends and the rear axle pivot point", explanation: "The stability triangle is the three-point base formed by the two front axle ends and the rear axle pivot point." },
      { question: "When is it acceptable to carry passengers on a forklift?", type: "mcq_single", options: ["Never, unless an OSHA-approved safety platform is mounted", "When going slowly", "In emergencies only", "When a supervisor permits it"], correctAnswers: "Never, unless an OSHA-approved safety platform is mounted", explanation: "Passengers are never allowed unless using an OSHA-approved work platform with guardrails and fall protection." },
      { question: "At intersections and blind corners, forklift operators should:", type: "mcq_single", options: ["Speed up to clear quickly", "Stop, sound horn, and proceed slowly after checking", "Trust that pedestrians will move", "Flash headlights"], correctAnswers: "Stop, sound horn, and proceed slowly after checking", explanation: "Operators must stop, sound the horn, and look both ways before proceeding through any intersection." },
      { question: "Forklifts must be refueled or recharged:", type: "mcq_single", options: ["Anywhere that's convenient", "Only in designated areas with proper ventilation", "While the engine is running", "Near the loading dock"], correctAnswers: "Only in designated areas with proper ventilation", explanation: "Refueling/recharging must only occur in designated, well-ventilated areas." },
      { question: "The primary cause of forklift tip-overs is:", type: "mcq_single", options: ["Engine failure", "Overloading and improper turning", "Bad tires", "Low fuel"], correctAnswers: "Overloading and improper turning", explanation: "Most tip-overs result from exceeding load capacity or turning too sharply/quickly." },
      { question: "What is the minimum age required to operate a forklift?", type: "mcq_single", options: ["16", "18", "21", "No minimum with training"], correctAnswers: "18", explanation: "OSHA requires operators to be at least 18 years old." },
      { question: "Who is responsible for ensuring forklift operators are properly trained?", type: "mcq_single", options: ["The operator", "The employer", "OSHA directly", "The forklift manufacturer"], correctAnswers: "The employer", explanation: "Under 29 CFR 1910.178(l), the employer is responsible for ensuring operators are trained and evaluated." },
      { question: "When going UP a ramp with a load, you should:", type: "mcq_single", options: ["Drive forward with load pointing uphill", "Drive in reverse with load pointing downhill", "Drive sideways for stability", "Speed up for momentum"], correctAnswers: "Drive forward with load pointing uphill", explanation: "When ascending a ramp with a load, travel with the load pointed uphill (upgrade) — drive forward up the ramp." },
      { question: "How far from the ground should forks be carried when traveling?", type: "mcq_single", options: ["At knee height", "At waist height", "4 to 6 inches", "Fully on the ground"], correctAnswers: "4 to 6 inches", explanation: "Carry forks 4–6 inches from the ground to keep the center of gravity low and reduce tip-over risk." },
      { question: "When parking a forklift and leaving it unattended, you must:", type: "mcq_single", options: ["Just turn off the engine", "Lower forks, set brake, turn off engine, and remove the key", "Leave it running for the next operator", "Only set the parking brake"], correctAnswers: "Lower forks, set brake, turn off engine, and remove the key", explanation: "Full shutdown is required: lower forks, set brake, turn off engine, remove key, and chock wheels if on an incline." },
      { question: "A forklift is considered 'unattended' when the operator is:", type: "mcq_single", options: ["5 feet away", "10 feet away", "More than 25 feet away and out of the line of sight", "In the same building"], correctAnswers: "More than 25 feet away and out of the line of sight", explanation: "A vehicle is unattended when the operator is more than 25 feet away AND the vehicle is out of their view." },
      { question: "Using attachments on a forklift:", type: "mcq_single", options: ["Increases the rated capacity", "Has no effect on capacity", "Reduces the rated capacity", "Only affects speed"], correctAnswers: "Reduces the rated capacity", explanation: "Attachments change the center of gravity and reduce the forklift's rated lifting capacity." },
      { question: "Pedestrians near forklift operations:", type: "mcq_single", options: ["Should move out of the way quickly", "Always have the right of way", "Must wear reflective vests to be seen", "Should signal the operator"], correctAnswers: "Always have the right of way", explanation: "Pedestrians always have the right of way. Forklift operators must yield to pedestrians at all times." },
      { question: "This online course alone fully satisfies all OSHA forklift training requirements.", type: "mcq_single", options: ["True", "False"], correctAnswers: "False", explanation: "OSHA requires formal instruction (this course) PLUS practical training and evaluation conducted by the employer." },
      { question: "If you discover a hydraulic leak during pre-shift inspection, you should:", type: "mcq_single", options: ["Continue working carefully", "Report it and do NOT operate the forklift", "Top off the hydraulic fluid and continue", "Check again at end of shift"], correctAnswers: "Report it and do NOT operate the forklift", explanation: "Never operate a forklift with fluid leaks. Hydraulic leaks can cause sudden loss of load control." },
      { question: "Smoking is prohibited within how many feet of fueling or charging areas?", type: "mcq_single", options: ["10 feet", "25 feet", "50 feet", "100 feet"], correctAnswers: "50 feet", explanation: "No smoking or open flames within 50 feet of fueling stations and battery recharging areas." },
      { question: "Before driving into a trailer at a loading dock, you must verify:", type: "mcq_single", options: ["The trailer color matches the order", "Wheel chocks are in place and brakes are set", "The trailer is empty", "The dock light is green"], correctAnswers: "Wheel chocks are in place and brakes are set", explanation: "Always verify chocks are placed and trailer brakes are set to prevent the trailer from separating from the dock." },
      { question: "When should forklift operators sound their horn?", type: "mcq_single", options: ["Only in emergencies", "At intersections, blind corners, and areas with pedestrians", "Only when the supervisor is watching", "Only outdoors"], correctAnswers: "At intersections, blind corners, and areas with pedestrians", explanation: "Sound the horn at intersections, blind corners, doorways, and whenever pedestrians may be present." },
      { question: "An OSHA-approved safety platform for lifting people must include:", type: "mcq_single", options: ["Just a flat surface", "Guardrails, toe boards, mast attachment, and fall protection", "A ladder", "Nothing special — any platform works"], correctAnswers: "Guardrails, toe boards, mast attachment, and fall protection", explanation: "OSHA requires 42-inch guardrails, mid-rails, 4-inch toe boards, secure mast attachment, overhead guard, and personal fall protection." },
      { question: "Operators should keep their entire body inside the forklift's protective cage at all times.", type: "mcq_single", options: ["True", "False"], correctAnswers: "True", explanation: "Never extend any body part beyond the protective cage to avoid crush hazards." },
      { question: "OSHA fines for operating without proper forklift certification can reach:", type: "mcq_single", options: ["$100 per employee", "$1,000 per employee", "$7,000 per day per unqualified employee", "No fines, just warnings"], correctAnswers: "$7,000 per day per unqualified employee", explanation: "OSHA can fine employers up to $7,000 per day per uncertified operator, retroactive to the hire date." },
      { question: "After successfully completing the final exam, what must your employer still do?", type: "mcq_single", options: ["Nothing — you're fully certified", "Conduct practical training and evaluation at the worksite", "File paperwork with OSHA", "Buy you a hard hat"], correctAnswers: "Conduct practical training and evaluation at the worksite", explanation: "The employer must still provide hands-on training specific to the equipment and workplace, and evaluate the operator's performance." },
    ],
  },
  {
    module: "Final Exam & Completion",
    title: "Congratulations: What's Next",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: photo("ppe-workers-scene.svg"), alt: "Team of certified workers in PPE in front of a forklift" },
      { type: "heading", level: 2, text: "You're Certified! What's Next" },
      { type: "heading", level: 3, text: "Your Certificate" },
      { type: "paragraph", html: "Congratulations on completing the formal instruction portion of your forklift operator certification! Your digital certificate is now available for download. It includes a unique certificate number and QR code that employers can use for instant verification." },
      { type: "heading", level: 3, text: "Next Step: Practical Evaluation" },
      { type: "paragraph", html: "Remember, your employer must still complete the <strong>hands-on practical evaluation</strong> at your worksite. Share the employer documentation packet (available in Module 7) with your supervisor. It includes:" },
      { type: "list", items: [
        "Performance Evaluation Checklist",
        "Operator Permit / Authorization Form",
        "Site Attendance Sheet",
      ] },
      { type: "heading", level: 3, text: "Wallet Card (Optional)" },
      { type: "paragraph", html: "Want a professional, wallet-sized operator ID card? Order your physical card from your certification page. It makes it easy to show proof of training on the job." },
      { type: "heading", level: 3, text: "Stay Safe" },
      { type: "paragraph", html: "Your training doesn't end here. Continue to follow safe operating procedures every day. If you ever have questions or need a refresher, you can revisit this course at any time. Stay safe out there!" },
      { type: "callout", variant: "tip", text: "Bookmark your verification page link — employers can use it to instantly verify your certification." },
      { type: "key_takeaways", items: [
        "Download your certificate from your certification page",
        "Share the employer packet with your supervisor for practical evaluation",
        "Consider ordering a wallet-sized operator ID card",
        "Re-evaluation is required at least every 3 years",
      ] },
    ]),
  },
];
