import type { LessonBlock } from "@shared/lesson-blocks";
import { StepDef } from "./course-content-aerial";

export const CANONICAL_COURSE_ES = {
  title: "Certificación en Línea para Operador de Elevadores Aéreos y de Tijera",
  slug: "certificacion-elevadores-aereos-tijera-en-linea",
  description: "Capacitación integral para operadores de elevadores aéreos y de tijera en cumplimiento con OSHA. Cubre los estándares 29 CFR 1926.453 y ANSI/SAIA A92. Incluye instrucción formal sobre tipos de equipo, inspección pre-operación, protección contra caídas, estabilidad, operación segura, peligros del lugar de trabajo y procedimientos de emergencia. Nota: OSHA también requiere capacitación práctica y evaluación en el equipo específico por parte del empleador.",
  category: "aerial",
  price: "59.00",
};

const img = (name: string) => `/images/training/${name}`;

const blocks = (b: LessonBlock[]) => ({ blocks: b });

export const COURSE_STEPS_ES: StepDef[] = [
  // ═══ MÓDULO 0: Bienvenida + Cumplimiento OSHA/ANSI ═══
  {
    module: "Bienvenida y Cumplimiento OSHA/ANSI",
    title: "Bienvenido a la Certificación de Elevadores Aéreos y de Tijera",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "Bienvenido a la Certificación de Elevadores Aéreos y de Tijera" },
      { type: "heading", level: 2, text: "Bienvenido a la Certificación de Elevadores Aéreos y de Tijera" },
      { type: "heading", level: 3, text: "Acerca de Este Curso" },
      { type: "paragraph", html: "¡Bienvenido! Este curso en línea proporciona la porción de <strong>instrucción formal</strong> de la certificación de operador de elevadores aéreos y de tijera en cumplimiento con OSHA. El curso toma aproximadamente <strong>60-90 minutos</strong> para completar." },
      { type: "heading", level: 3, text: "Qué Incluye" },
      { type: "list", items: [
        "Módulos de capacitación interactivos que cubren todos los temas requeridos por OSHA y ANSI",
        "Cuestionarios de verificación de conocimiento",
        "Examen final de certificación (80% para aprobar)",
        "Certificado digital con credencial verificada por código QR",
        "Paquete de documentación del empleador para evaluación práctica",
      ] },
      { type: "heading", level: 3, text: "Qué NO Incluye" },
      { type: "paragraph", html: "OSHA y ANSI requieren <strong>múltiples componentes</strong> para la certificación completa: (1) instrucción formal (este curso), (2) capacitación práctica en el equipo específico, y (3) una evaluación del desempeño del operador. Su empleador debe realizar la parte práctica en su lugar de trabajo." },
      { type: "heading", level: 3, text: "Cómo Navegar" },
      { type: "paragraph", html: "Complete cada paso en orden. Puede seguir su progreso usando la barra lateral. Si necesita detenerse, su progreso se guarda automáticamente. Puede retomar el examen final hasta 3 veces." },
      { type: "callout", variant: "tip", text: "Esté atento a los diagramas interactivos, tarjetas y escenarios a lo largo del curso — son la forma más rápida de afianzar lo que aprende." },
      { type: "key_takeaways", items: [
        "Este curso cubre el requisito de instrucción formal",
        "Su empleador también debe realizar capacitación práctica y evaluación",
        "Complete todos los módulos y apruebe el examen final con 80% o más",
        "Su progreso se guarda automáticamente — reanude en cualquier momento",
      ] },
    ]),
  },
  {
    module: "Bienvenida y Cumplimiento OSHA/ANSI",
    title: "Cumplimiento OSHA y ANSI: Lo Que Cubre Este Curso",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "Cumplimiento OSHA y ANSI: Lo Que Cubre Este Curso" },
      { type: "heading", level: 2, text: "Cumplimiento OSHA y ANSI: Lo Que Cubre Este Curso" },
      { type: "heading", level: 3, text: "Regulaciones de OSHA" },
      { type: "paragraph", html: "Los elevadores aéreos están regulados bajo <strong>29 CFR 1926.453</strong> (elevadores aéreos en construcción) y <strong>29 CFR 1910.178</strong> (camiones industriales motorizados, que incluye elevadores de tijera bajo la aplicación de OSHA). OSHA requiere que los operadores reciban:" },
      { type: "list", ordered: true, items: [
        "<strong>Instrucción formal</strong> — capacitación en aula o en línea (este curso)",
        "<strong>Capacitación práctica</strong> — experiencia práctica en el equipo específico",
        "<strong>Evaluación</strong> — una persona calificada debe evaluar la competencia del operador",
      ] },
      { type: "heading", level: 3, text: "Estándares ANSI/SAIA A92" },
      { type: "paragraph", html: "El <strong>Instituto Nacional Estadounidense de Estándares (ANSI)</strong> y la <strong>Asociación de la Industria de Andamios y Acceso (SAIA)</strong> mantienen la serie A92 para Plataformas de Trabajo Móvil Elevadora (MEWPs):" },
      { type: "list", items: [
        "<strong>A92.20</strong> — Diseño, Seguridad y Verificación",
        "<strong>A92.22</strong> — Uso Seguro de MEWPs",
        "<strong>A92.24</strong> — Requisitos de Capacitación",
      ] },
      { type: "paragraph", html: "La revisión de 2020 reestructuró estos estándares y reemplazó el término 'plataforma de trabajo aéreo' con 'MEWP'." },
      { type: "heading", level: 3, text: "Lo Que Proporcionamos" },
      { type: "list", items: [
        "Instrucción formal completa cubriendo todos los temas requeridos por OSHA y ANSI",
        "Evaluación de conocimiento mediante examen final",
        "Certificado de finalización para la porción de instrucción formal",
        "Paquete de documentación del empleador incluyendo listas de evaluación",
      ] },
      { type: "heading", level: 3, text: "Lo Que Su Empleador Debe Hacer" },
      { type: "paragraph", html: "Después de completar este curso, su empleador debe:" },
      { type: "list", items: [
        "Proporcionar capacitación práctica específica al equipo",
        "Evaluar su desempeño en el lugar de trabajo real",
        "Completar y mantener la documentación requerida",
        "Asegurar la familiarización con la marca/modelo específico que operará",
        "Re-evaluar a los operadores al menos cada 3 años",
      ] },
      { type: "callout", variant: "warning", text: "No opere un elevador aéreo o de tijera hasta que su empleador haya completado su capacitación práctica y evaluación en el equipo específico." },
      { type: "key_takeaways", items: [
        "Los elevadores aéreos están regulados bajo 29 CFR 1926.453 y 1910.178",
        "Los estándares ANSI/SAIA A92 cubren diseño, uso y capacitación de MEWPs",
        "Este curso cubre solo la instrucción formal — también se requiere capacitación práctica",
        "Los operadores deben familiarizarse con el equipo específico que operarán",
      ] },
    ]),
  },
  {
    module: "Bienvenida y Cumplimiento OSHA/ANSI",
    title: "Verificación de Conocimiento: Requisitos OSHA y ANSI",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Qué norma de OSHA cubre específicamente los elevadores aéreos?", type: "mcq_single", options: ["29 CFR 1910.178", "29 CFR 1926.453", "29 CFR 1910.147", "29 CFR 1926.450"], correctAnswers: "29 CFR 1926.453", explanation: "29 CFR 1926.453 es la norma de OSHA para elevadores aéreos. Los elevadores de tijera se aplican bajo 1910.178." },
      { question: "¿Qué cubre el estándar ANSI A92.24?", type: "mcq_single", options: ["Requisitos de diseño del equipo", "Requisitos de capacitación para operadores de MEWP", "Calificaciones de capacidad de carga", "Programas de mantenimiento"], correctAnswers: "Requisitos de capacitación para operadores de MEWP", explanation: "ANSI A92.24 cubre los requisitos de capacitación para operadores de MEWP, ocupantes, supervisores y personal de servicio." },
      { question: "Este curso en línea por sí solo satisface completamente todos los requisitos de capacitación de OSHA para elevadores aéreos.", type: "mcq_single", options: ["Verdadero", "Falso"], correctAnswers: "Falso", explanation: "OSHA requiere instrucción formal (este curso) MÁS capacitación práctica y evaluación en el equipo específico por parte del empleador." },
    ],
  },

  // ═══ MÓDULO 1: Fundamentos de Elevadores Aéreos y Clasificaciones ═══
  {
    module: "Fundamentos de Elevadores Aéreos y Clasificaciones",
    title: "¿Qué es una Plataforma de Trabajo Móvil Elevadora (MEWP)?",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "¿Qué es una Plataforma de Trabajo Móvil Elevadora (MEWP)?" },
      { type: "heading", level: 2, text: "¿Qué es una Plataforma de Trabajo Móvil Elevadora (MEWP)?" },
      { type: "heading", level: 3, text: "Definición" },
      { type: "paragraph", html: "Una <strong>Plataforma de Trabajo Móvil Elevadora (MEWP)</strong> es una máquina utilizada para posicionar personal, herramientas y materiales en ubicaciones de trabajo elevadas. Los MEWPs incluyen elevadores aéreos, elevadores de tijera, elevadores de pluma y torres verticales. El término MEWP fue adoptado por ANSI en la revisión de 2020 de los estándares A92." },
      { type: "heading", level: 3, text: "Grupos de MEWPs (ANSI A92.20)" },
      { type: "paragraph", html: "ANSI clasifica los MEWPs en dos grupos según cómo se posiciona la plataforma:" },
      { type: "list", items: [
        "<strong>Grupo A:</strong> Plataformas que solo se pueden elevar verticalmente — la plataforma permanece dentro de las líneas de volcadura (ej. elevadores de tijera, elevadores verticales)",
        "<strong>Grupo B:</strong> Plataformas que pueden posicionarse más allá de las líneas de volcadura — la pluma permite que la plataforma se extienda horizontalmente (ej. elevadores de pluma articulados, elevadores de pluma telescópicos)",
      ] },
      { type: "heading", level: 3, text: "Tipos de MEWPs" },
      { type: "paragraph", html: "Dentro de cada grupo, los MEWPs se clasifican además por tipo:" },
      { type: "list", items: [
        "<strong>Tipo 1:</strong> La conducción solo se permite en posición plegada (no elevada)",
        "<strong>Tipo 2:</strong> La conducción se permite con la plataforma en posición elevada",
        "<strong>Tipo 3:</strong> La conducción se permite con la plataforma elevada, pero se controla desde la plataforma",
      ] },
      { type: "heading", level: 3, text: "Tipos Comunes de Equipo" },
      { type: "list", items: [
        "<strong>Elevadores de tijera</strong> (Grupo A) — solo elevación vertical, gran área de plataforma",
        "<strong>Elevadores de pluma articulados</strong> (Grupo B) — brazo articulado proporciona alcance arriba y sobre",
        "<strong>Elevadores de pluma telescópicos</strong> (Grupo B) — brazo recto para máximo alcance horizontal",
        "<strong>Elevadores verticales de personal</strong> (Grupo A) — plataformas pequeñas para acceso vertical de una persona",
      ] },
      { type: "key_takeaways", items: [
        "Los MEWPs se clasifican en Grupo A (solo vertical) y Grupo B (puede extenderse más allá de las líneas de volcadura)",
        "Los elevadores de tijera son Grupo A; los elevadores de pluma son Grupo B",
        "Los Tipos 1, 2 y 3 definen cuándo y desde dónde se permite conducir",
        "El término MEWP reemplazó a 'plataforma de trabajo aéreo' en la revisión ANSI de 2020",
      ] },
    ]),
  },
  {
    module: "Fundamentos de Elevadores Aéreos y Clasificaciones",
    title: "Elevadores de Tijera: Operación y Componentes",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("scissor-lift-hero.svg"), alt: "Elevadores de Tijera: Operación y Componentes" },
      { type: "heading", level: 2, text: "Elevadores de Tijera: Operación y Componentes" },
      { type: "heading", level: 3, text: "¿Qué es un Elevador de Tijera?" },
      { type: "paragraph", html: "Un <strong>elevador de tijera</strong> es un MEWP del Grupo A que utiliza soportes tubulares cruzados (mecanismo de pantógrafo) para subir y bajar la plataforma verticalmente. Los elevadores de tijera proporcionan una plataforma de trabajo grande y estable ideal para tareas que requieren múltiples trabajadores y materiales a alturas moderadas." },
      { type: "heading", level: 3, text: "Componentes Principales" },
      { type: "list", items: [
        "<strong>Plataforma:</strong> El área de trabajo con barandillas y puerta de entrada",
        "<strong>Mecanismo de tijera:</strong> Soportes cruzados que se extienden/contraen",
        "<strong>Chasis/base:</strong> La unidad de conducción con ruedas u orugas",
        "<strong>Controles:</strong> Paneles de control superior (plataforma) e inferior (tierra)",
        "<strong>Fuente de energía:</strong> Batería eléctrica o combustión interna (diésel, gasolina, GLP)",
      ] },
      { type: "heading", level: 3, text: "Controles de Operación" },
      { type: "paragraph", html: "Los elevadores de tijera tienen <strong>controles superiores e inferiores</strong>. Los controles superiores están en la plataforma y son usados por el operador durante la elevación. Los controles inferiores están a nivel del suelo. Según OSHA, los controles inferiores deben poder anular los superiores en una emergencia, pero no deben usarse para operación normal cuando hay un operador en la plataforma." },
      { type: "heading", level: 3, text: "Capacidad de Conducción" },
      { type: "paragraph", html: "La mayoría de los elevadores de tijera modernos son <strong>Tipo 3</strong> — pueden ser conducidos desde los controles de la plataforma mientras están elevados. Sin embargo, conducir mientras está elevado debe hacerse con precaución y solo en superficies adecuadas." },
      { type: "callout", variant: "tip", text: "Siempre lea el manual de operación del fabricante para la marca y modelo específico antes de operar cualquier MEWP." },
      { type: "key_takeaways", items: [
        "Los elevadores de tijera son MEWPs del Grupo A con elevación solo vertical",
        "Tienen controles superiores (plataforma) e inferiores (tierra)",
        "Los controles inferiores pueden anular los superiores en emergencias",
        "La mayoría de los elevadores de tijera modernos pueden conducirse desde la plataforma",
      ] },
    ]),
  },
  {
    module: "Fundamentos de Elevadores Aéreos y Clasificaciones",
    title: "Elevadores de Pluma: Articulados y Telescópicos",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "Elevadores de Pluma: Articulados y Telescópicos" },
      { type: "heading", level: 2, text: "Elevadores de Pluma: Articulados y Telescópicos" },
      { type: "heading", level: 3, text: "Elevadores de Pluma Articulados" },
      { type: "paragraph", html: "Los <strong>elevadores de pluma articulados</strong> (plumas articuladas) tienen múltiples secciones articuladas que permiten que la plataforma alcance por encima y sobre obstáculos. El brazo articulado proporciona excelente maniobrabilidad. Clasificados como <strong>Grupo B</strong> porque la plataforma puede extenderse más allá de las líneas de volcadura." },
      { type: "heading", level: 3, text: "Elevadores de Pluma Telescópicos" },
      { type: "paragraph", html: "Los <strong>elevadores de pluma telescópicos</strong> usan secciones rectas extensibles para máximo alcance horizontal y vertical. Ofrecen las capacidades de alcance más altas pero no pueden alcanzar sobre obstáculos. También clasificados como <strong>Grupo B</strong>." },
      { type: "heading", level: 3, text: "Conozca Su Elevador de Pluma" },
      { type: "paragraph", html: "Antes de operar, necesita conocer los componentes clave de la máquina. Toque cada marcador para aprender qué hace." },
      { type: "hotspot_diagram", src: img("aerial-lift-anatomy.svg"), alt: "Vista lateral de un elevador de pluma articulado con canasta elevada",
        caption: "Anatomía de un elevador de pluma articulado — toque cada marcador para explorar.",
        hotspots: [
          { x: 24, y: 79, label: "Chasis", description: "La base con ruedas que soporta y mueve toda la máquina. Su peso contrapesa la plataforma elevada — siempre posiciónelo sobre terreno firme y nivelado." },
          { x: 31, y: 69, label: "Torreta y Controles Inferiores", description: "La torreta giratoria sostiene la pluma y aloja el panel de control inferior (tierra). Los controles inferiores deben poder anular los controles de la plataforma en una emergencia." },
          { x: 36, y: 53, label: "Pluma Inferior", description: "La primera sección de la pluma se eleva desde la torreta. En un elevador articulado trabaja junto con la articulación para llevar la plataforma por encima de obstáculos." },
          { x: 49, y: 41, label: "Articulación (Nudillo)", description: "La unión articulada entre las secciones de la pluma. Esta articulación es lo que permite que una pluma articulada alcance sobre equipos y estructuras que una pluma telescópica no puede." },
          { x: 62, y: 37, label: "Pluma Superior", description: "Extiende la plataforma más allá de las líneas de volcadura — por eso los elevadores de pluma son MEWPs del Grupo B y exigen atención adicional a la estabilidad." },
          { x: 82, y: 37, label: "Canasta y Barandillas", description: "La plataforma de trabajo. Las barandillas son su primera línea de protección contra caídas — nunca se pare sobre ellas ni se incline por encima, y mantenga ambos pies en el piso de la plataforma." },
          { x: 81, y: 23, label: "Arnés y Línea del Operador", description: "El operador usa un arnés de cuerpo completo con una línea de seguridad sujeta al punto de anclaje designado por el fabricante — requerido en todo momento en la canasta de un elevador de pluma." },
          { x: 87, y: 21, label: "Controles de la Plataforma", description: "La consola de control superior permite al operador conducir, girar, subir y bajar desde la canasta. Pruebe estos controles cada día antes del uso." },
        ] },
      { type: "heading", level: 3, text: "Diferencias Clave de los Elevadores de Tijera" },
      { type: "list", items: [
        "Los elevadores de pluma pueden posicionar la plataforma <strong>más allá de la huella del chasis</strong>",
        "Tienen <strong>mayor alcance</strong> pero típicamente plataformas más pequeñas",
        "Los MEWPs del Grupo B requieren consideraciones adicionales de <strong>protección contra caídas</strong>",
        "Los estabilizadores generalmente son requeridos para la operación",
      ] },
      { type: "key_takeaways", items: [
        "Las plumas articuladas tienen brazos articulados para alcance arriba y sobre",
        "Las plumas telescópicas usan extensión recta para máximo alcance",
        "Ambos son MEWPs del Grupo B — la plataforma se extiende más allá de las líneas de volcadura",
        "Los estabilizadores generalmente son requeridos para operación de pluma",
      ] },
    ]),
  },
  {
    module: "Fundamentos de Elevadores Aéreos y Clasificaciones",
    title: "Verificación de Conocimiento: Fundamentos de MEWP",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Un elevador de tijera está clasificado como qué grupo de MEWP?", type: "mcq_single", options: ["Grupo A", "Grupo B", "Grupo C", "No es un MEWP"], correctAnswers: "Grupo A", explanation: "Los elevadores de tijera son MEWPs del Grupo A porque la plataforma solo se puede elevar verticalmente y permanece dentro de las líneas de volcadura." },
      { question: "¿Qué tipo de elevador de pluma tiene secciones articuladas que permiten alcanzar sobre obstáculos?", type: "mcq_single", options: ["Elevador de pluma telescópico", "Elevador de pluma articulado", "Torre vertical", "Elevador de tijera"], correctAnswers: "Elevador de pluma articulado", explanation: "Los elevadores de pluma articulados tienen múltiples secciones articuladas que permiten que la plataforma alcance por encima y sobre obstáculos." },
      { question: "En un MEWP, los controles inferiores deben poder:", type: "mcq_single", options: ["Solo usarse para conducir", "Anular los controles superiores en una emergencia", "Bloquearse permanentemente", "Solo usarse para reabastecimiento"], correctAnswers: "Anular los controles superiores en una emergencia", explanation: "Según OSHA, los controles inferiores deben poder anular los superiores en una emergencia." },
    ],
  },

  // ═══ MÓDULO 2: Inspección Pre-Operación ═══
  {
    module: "Inspección Pre-Operación",
    title: "Lista de Inspección Pre-Operación",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Lista de Inspección Pre-Operación" },
      { type: "heading", level: 2, text: "Lista de Inspección Pre-Operación" },
      { type: "heading", level: 3, text: "Requisito de OSHA" },
      { type: "paragraph", html: "Bajo <strong>29 CFR 1926.453(a)(1)</strong>, los controles del elevador deben ser probados cada día antes de su uso para determinar que están en condiciones seguras de funcionamiento. Este es un requisito diario obligatorio." },
      { type: "heading", level: 3, text: "Inspección Visual" },
      { type: "paragraph", html: "Camine alrededor de todo el MEWP, verificando:" },
      { type: "list", items: [
        "<strong>Plataforma y barandillas:</strong> Revise daños, componentes flojos, barandillas faltantes",
        "<strong>Mangueras y cables:</strong> Busque fugas, abrasión, dobleces o desgaste",
        "<strong>Llantas/ruedas:</strong> Revise daños, inflado apropiado",
        "<strong>Batería/combustible:</strong> Revise nivel de carga, fugas",
        "<strong>Componentes estructurales:</strong> Inspeccione grietas, dobleces, fallas de soldadura",
        "<strong>Estabilizadores:</strong> Revise función apropiada y condición de las almohadillas",
        "<strong>Señales de seguridad:</strong> Asegure que las etiquetas de capacidad y advertencias sean legibles",
      ] },
      { type: "heading", level: 3, text: "Prueba Funcional" },
      { type: "paragraph", html: "Después de la inspección visual, realice una <strong>prueba funcional</strong> de todos los controles:" },
      { type: "list", items: [
        "Pruebe <strong>controles superiores</strong>: subir, bajar, conducir, girar",
        "Pruebe <strong>controles inferiores</strong>: subir, bajar, parada de emergencia",
        "Pruebe el <strong>sistema de descenso de emergencia</strong>",
        "Pruebe la <strong>bocina</strong> y <strong>sistemas de alarma</strong>",
        "Pruebe los <strong>frenos</strong> y la <strong>dirección</strong>",
        "Pruebe el <strong>botón de parada de emergencia</strong>",
      ] },
      { type: "heading", level: 3, text: "Practique la Secuencia" },
      { type: "drag_drop", mode: "ordering",
        prompt: "Ordene los pasos de la inspección diaria pre-operación en la secuencia correcta.",
        items: [
          { id: "insp-walk", label: "Camine alrededor del MEWP y complete la inspección visual" },
          { id: "insp-lower", label: "Pruebe el funcionamiento de los controles inferiores (tierra)" },
          { id: "insp-upper", label: "Pruebe el funcionamiento de los controles superiores (plataforma)" },
          { id: "insp-estop", label: "Pruebe la parada de emergencia y el sistema de descenso de emergencia" },
          { id: "insp-tag", label: "Marque fuera de servicio y reporte el MEWP si encuentra algún defecto" },
        ] },
      { type: "heading", level: 3, text: "Marcar Equipo Inseguro" },
      { type: "paragraph", html: "Si encuentra algún defecto o problema de seguridad, <strong>no opere el MEWP</strong>. Márquelo fuera de servicio inmediatamente y reporte el problema a su supervisor. El equipo debe ser reparado antes de volver a servicio." },
      { type: "callout", variant: "warning", text: "Nunca opere un MEWP que no pase la inspección. Cualquier defecto debe corregirse antes del uso." },
      { type: "key_takeaways", items: [
        "OSHA requiere probar los controles cada día antes del uso (29 CFR 1926.453)",
        "Realice inspección visual y prueba funcional de todos los controles",
        "Revise plataforma, barandillas, mangueras, llantas, batería/combustible",
        "Marque y reporte cualquier equipo inseguro inmediatamente",
      ] },
    ]),
  },
  {
    module: "Inspección Pre-Operación",
    title: "Mantenimiento de Batería y Combustible",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("ppe-gloves.svg"), alt: "Mantenimiento de Batería y Combustible" },
      { type: "heading", level: 2, text: "Mantenimiento de Batería y Combustible" },
      { type: "heading", level: 3, text: "MEWPs Eléctricos" },
      { type: "paragraph", html: "Los MEWPs eléctricos usan baterías de ciclo profundo. El mantenimiento adecuado extiende la vida de la batería:" },
      { type: "list", items: [
        "Cargue baterías solo en <strong>áreas designadas y ventiladas</strong>",
        "Apague el cargador antes de conectar/desconectar",
        "Las baterías producen <strong>gas hidrógeno</strong> durante la carga — asegure ventilación",
        "Use <strong>guantes resistentes a químicos y protección ocular</strong>",
        "Nunca fume o use llamas abiertas cerca de baterías en carga",
      ] },
      { type: "heading", level: 3, text: "MEWPs de Combustión Interna" },
      { type: "paragraph", html: "MEWPs de diésel, gasolina o GLP requieren seguridad específica:" },
      { type: "list", items: [
        "Reabastezca solo en <strong>áreas designadas</strong> con ventilación",
        "Apague el motor antes de reabastecer",
        "Prohibido fumar o llamas abiertas dentro de <strong>50 pies</strong>",
        "Use guantes al manejar tanques de GLP",
        "Revise fugas después de conectar tanques de GLP",
      ] },
      { type: "heading", level: 3, text: "Mantenimiento Diario" },
      { type: "paragraph", html: "Revise al inicio de cada turno:" },
      { type: "list", items: [
        "Nivel de carga de batería o combustible suficiente",
        "Nivel de fluido hidráulico dentro del rango aceptable",
        "Nivel de aceite del motor (para motores de combustión)",
        "Sin fugas de ningún tipo",
      ] },
      { type: "callout", variant: "warning", text: "El gas hidrógeno de las baterías en carga es altamente explosivo. Siempre asegure ventilación adecuada." },
      { type: "key_takeaways", items: [
        "Cargue baterías solo en áreas designadas y ventiladas",
        "Las baterías producen gas hidrógeno explosivo durante la carga",
        "Prohibido fumar a 50 pies de áreas de carga o reabastecimiento",
        "Revise todos los niveles de fluido al inicio de cada turno",
      ] },
    ]),
  },
  {
    module: "Inspección Pre-Operación",
    title: "Verificación de Conocimiento: Inspección Pre-Operación",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Con qué frecuencia deben probarse los controles antes del uso según OSHA?", type: "mcq_single", options: ["Semanalmente", "Mensualmente", "Cada día antes del uso", "Solo después de reparaciones"], correctAnswers: "Cada día antes del uso", explanation: "29 CFR 1926.453(a)(1) requiere que los controles sean probados cada día antes del uso." },
      { question: "Si encuentra una barandilla dañada durante la inspección, debe:", type: "mcq_single", options: ["Continuar y reportar al final del turno", "Marcarlo fuera de servicio y no operar", "Usarlo solo para tareas de poca altura", "Repararlo con cinta"], correctAnswers: "Marcarlo fuera de servicio y no operar", explanation: "Cualquier defecto requiere que el equipo sea marcado fuera de servicio y no operado hasta ser reparado." },
      { question: "Las baterías en carga producen qué gas explosivo?", type: "mcq_single", options: ["Oxígeno", "Nitrógeno", "Hidrógeno", "Dióxido de carbono"], correctAnswers: "Hidrógeno", explanation: "Las baterías eléctricas producen gas hidrógeno durante la carga, que es altamente explosivo." },
    ],
  },

  // ═══ MÓDULO 3: Estabilidad y Manejo de Cargas ═══
  {
    module: "Estabilidad y Manejo de Cargas",
    title: "Principios de Estabilidad del MEWP",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("stability-triangle.svg"), alt: "Principios de Estabilidad del MEWP" },
      { type: "heading", level: 2, text: "Principios de Estabilidad del MEWP" },
      { type: "heading", level: 3, text: "Líneas de Volcadura" },
      { type: "paragraph", html: "Cada MEWP tiene <strong>líneas de volcadura</strong> — el eje alrededor del cual el MEWP podría volcarse si el centro de gravedad se desplaza demasiado. Para MEWPs del Grupo A (tijera), las líneas son típicamente las ruedas o estabilizadores. Para el Grupo B (pluma), son las almohadillas de los estabilizadores o las posiciones de las ruedas." },
      { type: "heading", level: 3, text: "Centro de Gravedad" },
      { type: "paragraph", html: "El <strong>centro de gravedad combinado</strong> incluye el MEWP mismo, la carga de la plataforma (personal, herramientas, materiales) y la posición de la pluma/plataforma. Si el centro de gravedad combinado se mueve fuera de las líneas de volcadura, el MEWP se volcará." },
      { type: "heading", level: 3, text: "Factores que Afectan la Estabilidad" },
      { type: "list", items: [
        "<strong>Altura de plataforma:</strong> Mayor elevación sube el centro de gravedad",
        "<strong>Peso de carga:</strong> Exceder la capacidad desplaza el centro de gravedad",
        "<strong>Extensión de pluma:</strong> La extensión horizontal mueve el centro de gravedad hacia afuera",
        "<strong>Pendiente:</strong> Operar en pendiente desplaza el centro de gravedad cuesta abajo",
        "<strong>Viento:</strong> La fuerza del viento puede desestabilizar el MEWP",
        "<strong>Condiciones de superficie:</strong> Terreno blando, hielo o superficies mojadas",
      ] },
      { type: "heading", level: 3, text: "Estabilizadores" },
      { type: "paragraph", html: "Muchos MEWPs, especialmente del Grupo B, requieren <strong>estabilizadores</strong> desplegados antes de la elevación. OSHA requiere que los frenos estén puestos y los estabilizadores posicionados sobre almohadillas o superficie sólida." },
      { type: "callout", variant: "warning", text: "Las volcaduras son una causa principal de fatalidades con MEWPs. Siempre respete los límites de capacidad y estabilidad." },
      { type: "key_takeaways", items: [
        "Las líneas de volcadura definen el límite de estabilidad",
        "Altura, carga, extensión de pluma, pendiente y viento afectan la estabilidad",
        "Los estabilizadores deben desplegarse sobre almohadillas/superficie sólida",
        "El centro de gravedad combinado debe mantenerse dentro de las líneas de volcadura",
      ] },
    ]),
  },
  {
    module: "Estabilidad y Manejo de Cargas",
    title: "Capacidad Nominal y Límites de Carga",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("load-center.svg"), alt: "Capacidad Nominal y Límites de Carga" },
      { type: "heading", level: 2, text: "Capacidad Nominal y Límites de Carga" },
      { type: "heading", level: 3, text: "Placa de Capacidad del Fabricante" },
      { type: "paragraph", html: "Cada MEWP tiene una placa de <strong>capacidad nominal</strong> que especifica la carga máxima que la plataforma puede soportar. Esto incluye el peso combinado de todo el personal, herramientas y materiales. <strong>Nunca exceda esta clasificación.</strong>" },
      { type: "heading", level: 3, text: "Consideraciones de Capacidad para Pluma" },
      { type: "paragraph", html: "Para elevadores de pluma del Grupo B, la capacidad puede variar según la posición de la pluma. Algunos tienen <strong>clasificaciones de capacidad variable</strong> que cambian con la extensión y ángulo. Siempre verifique la placa para la configuración específica." },
      { type: "heading", level: 3, text: "Límites de Personal" },
      { type: "paragraph", html: "La placa también especifica el número máximo de ocupantes permitidos en la plataforma. Nunca exceda este límite." },
      { type: "heading", level: 3, text: "Distribución de Carga" },
      { type: "paragraph", html: "Distribuya las cargas uniformemente en la plataforma. Concentrar peso en un lado puede desplazar el centro de gravedad. Asegure todas las herramientas y materiales." },
      { type: "callout", variant: "warning", text: "Sobrecargar un MEWP es una de las principales causas de accidentes de volcadura. Siempre verifique la carga total." },
      { type: "key_takeaways", items: [
        "Nunca exceda la capacidad nominal del fabricante",
        "La capacidad incluye el peso combinado de personal, herramientas y materiales",
        "La capacidad de pluma puede variar con la posición (capacidad variable)",
        "Distribuya las cargas uniformemente y asegure todos los materiales",
      ] },
    ]),
  },
  {
    module: "Estabilidad y Manejo de Cargas",
    title: "Verificación de Conocimiento: Estabilidad y Cargas",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Qué sucede si el centro de gravedad combinado se mueve fuera de las líneas de volcadura?", type: "mcq_single", options: ["Nada", "El MEWP se volcará", "Sonará una alarma", "La plataforma bajará automáticamente"], correctAnswers: "El MEWP se volcará", explanation: "Si el centro de gravedad combinado se mueve fuera de las líneas de volcadura, el MEWP se volcará." },
      { question: "¿Qué factor NO afecta la estabilidad del MEWP?", type: "mcq_single", options: ["Altura de plataforma", "Peso de carga", "Condiciones de viento", "El nombre del operador"], correctAnswers: "El nombre del operador", explanation: "Altura, peso, viento, pendiente y condiciones de superficie afectan la estabilidad. El nombre del operador es irrelevante." },
      { question: "La capacidad nominal en un MEWP incluye el peso de:", type: "mcq_single", options: ["Solo personal", "Solo herramientas", "Personal, herramientas y materiales combinados", "Solo la plataforma"], correctAnswers: "Personal, herramientas y materiales combinados", explanation: "La capacidad nominal incluye el peso combinado de todo el personal, herramientas y materiales." },
    ],
  },

  // ═══ MÓDULO 4: Operación Segura y Protección contra Caídas ═══
  {
    module: "Operación Segura y Protección contra Caídas",
    title: "Requisitos de Protección contra Caídas",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pedestrian-safety.svg"), alt: "Requisitos de Protección contra Caídas" },
      { type: "heading", level: 2, text: "Requisitos de Protección contra Caídas" },
      { type: "heading", level: 3, text: "Norma de Protección contra Caídas de OSHA" },
      { type: "paragraph", html: "Bajo <strong>29 CFR 1926.453</strong>, los empleados siempre deben pararse firmemente en el piso de la canasta. Se debe usar un <strong>cinturón corporal</strong> y un <strong>arnés de seguridad</strong> adjunto a la pluma o canasta. Sin embargo, desde el 1 de enero de 1998, los cinturones corporales <strong>NO son aceptables</strong> como parte de un sistema personal de detención de caídas — se debe usar un <strong>arnés de cuerpo completo</strong>." },
      { type: "heading", level: 3, text: "Sistema Personal de Detención de Caídas" },
      { type: "paragraph", html: "Un sistema completo de protección contra caídas consiste en:" },
      { type: "list", items: [
        "<strong>Arnés de cuerpo completo</strong> — distribuye las fuerzas de caída a través del cuerpo",
        "<strong>Línea de seguridad</strong> — conecta el arnés al punto de anclaje",
        "<strong>Punto de anclaje</strong> — el punto de attachment designado en la pluma o canasta (aprobado por el fabricante)",
      ] },
      { type: "flip_cards", title: "Equipo de Protección contra Caídas — Conozca Cada Pieza", cards: [
        { front: "Arnés de Cuerpo Completo", back: "Distribuye las fuerzas de detención de caída entre muslos, pelvis, pecho y hombros. Requerido desde el 1 de enero de 1998 — los cinturones corporales no son aceptables." },
        { front: "Línea de Seguridad", back: "Conecta su arnés al punto de anclaje. Inspeccione cortes, deshilachado y ganchos dañados antes de cada uso." },
        { front: "Punto de Anclaje", back: "El punto de sujeción designado por el fabricante en la plataforma o pluma. Nunca se ancle a estructuras, postes eléctricos ni nada fuera del MEWP." },
        { front: "Cinturón Corporal", back: "NO es aceptable para detención de caídas desde el 1 de enero de 1998. En una caída, un cinturón concentra toda la fuerza en el abdomen — use un arnés de cuerpo completo." },
      ] },
      { type: "heading", level: 3, text: "Puntos de Anclaje" },
      { type: "paragraph", html: "Siempre attache la línea de seguridad al <strong>punto de anclaje designado por el fabricante</strong>. Nunca attache a estructuras cercanas, líneas eléctricas, u otro equipo fuera del MEWP." },
      { type: "heading", level: 3, text: "Inspección del Arnés" },
      { type: "paragraph", html: "Inspeccione su arnés y línea antes de cada uso: revise cortes, desgarros, costuras dañadas, herrajes (anillos D, hebillas), y etiquetas legibles. Reemplace cualquier equipo dañado inmediatamente." },
      { type: "callout", variant: "warning", text: "Desde el 1 de enero de 1998, los cinturones corporales NO son aceptables. Se requieren arneses de cuerpo completo." },
      { type: "key_takeaways", items: [
        "Los cinturones corporales NO son aceptables desde 1998 — use arneses de cuerpo completo",
        "Attache la línea solo al punto de anclaje designado por el fabricante",
        "Nunca attache a estructuras o equipo fuera del MEWP",
        "Inspeccione el arnés y la línea antes de cada uso",
      ] },
    ]),
  },
  {
    module: "Operación Segura y Protección contra Caídas",
    title: "Procedimientos de Operación Segura",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("safe-driving.svg"), alt: "Procedimientos de Operación Segura" },
      { type: "heading", level: 2, text: "Procedimientos de Operación Segura" },
      { type: "heading", level: 3, text: "Antes de Elevar" },
      { type: "paragraph", html: "Antes de subir la plataforma:" },
      { type: "list", items: [
        "Verifique que la superficie sea <strong>nivelada y capaz de soportar la carga</strong>",
        "Despliegue estabilizadores si lo requiere el fabricante",
        "Ponga calzas en las ruedas si está en una pendiente",
        "Revise <strong>peligros aéreos</strong> (líneas eléctricas, estructuras)",
        "Asegure que el área esté libre de peatones y obstrucciones",
      ] },
      { type: "heading", level: 3, text: "Mientras Está Elevado" },
      { type: "paragraph", html: "Cuando la plataforma está elevada:" },
      { type: "list", items: [
        "<strong>Siempre use su arnés y attache la línea</strong>",
        "Mantenga ambos pies firmemente en el piso de la plataforma",
        "Nunca se pare en barandillas o escaleras",
        "No exceda la capacidad nominal o el límite de personal",
      ] },
      { type: "heading", level: 3, text: "Conducir Mientras Está Elevado" },
      { type: "paragraph", html: "Si conducir mientras está elevado es permitido por el fabricante:" },
      { type: "list", items: [
        "Conduzca a <strong>muy baja velocidad</strong>",
        "Vigile peligros de superficie y obstáculos",
        "Evite arranques, paradas o giros repentinos",
        "Nunca conduzca cerca de bordes abiertos",
      ] },
      { type: "heading", level: 3, text: "Bajar la Plataforma" },
      { type: "paragraph", html: "Antes de bajar: asegure que el área debajo esté libre, verifique que el camino esté libre de obstrucciones, baje lentamente y bajo control." },
      { type: "callout", variant: "tip", text: "Antes de elevar, siempre mire hacia arriba y alrededor para peligros aéreos como líneas eléctricas y estructuras." },
      { type: "key_takeaways", items: [
        "Siempre use arnés y attache al punto de anclaje designado",
        "Revise peligros aéreos antes de elevar",
        "Nunca exceda la capacidad o los límites de personal",
        "Baje lentamente y asegure que el área esté libre",
      ] },
    ]),
  },
  {
    module: "Operación Segura y Protección contra Caídas",
    title: "Verificación de Conocimiento: Operación Segura y Protección contra Caídas",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Desde el 1 de enero de 1998, qué tipo de protección contra caídas es requerida (no cinturones)?", type: "mcq_single", options: ["Solo cinturón corporal", "Arnés de cuerpo completo", "Sin protección contra caídas", "Una cuerda y nudo"], correctAnswers: "Arnés de cuerpo completo", explanation: "Los cinturones corporales no son aceptables desde 1998. Se requieren arneses de cuerpo completo." },
      { question: "Al conducir un MEWP mientras está elevado, debe:", type: "mcq_single", options: ["Conducir a velocidad normal", "Conducir a muy baja velocidad y vigilar peligros", "Tocar la bocina repetidamente", "Nunca conducir mientras está elevado bajo ninguna circunstancia"], correctAnswers: "Conducir a muy baja velocidad y vigilar peligros", explanation: "Si conducir mientras está elevado es permitido, conduzca a muy baja velocidad y vigile peligros." },
      { question: "La línea de seguridad debe attacherse a:", type: "mcq_single", options: ["Cualquier objeto resistente cercano", "El punto de anclaje designado por el fabricante en el MEWP", "Una viga del edificio", "La protección superior"], correctAnswers: "El punto de anclaje designado por el fabricante en el MEWP", explanation: "Siempre attache la línea solo al punto de anclaje designado por el fabricante." },
    ],
  },

  // ═══ MÓDULO 5: Peligros del Lugar de Trabajo y Seguridad Eléctrica ═══
  {
    module: "Peligros del Lugar de Trabajo y Seguridad Eléctrica",
    title: "Peligros Eléctricos y Líneas de Energía",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "Peligros Eléctricos y Líneas de Energía" },
      { type: "heading", level: 2, text: "Peligros Eléctricos y Líneas de Energía" },
      { type: "heading", level: 3, text: "Distancia Mínima de Líneas de Energía" },
      { type: "paragraph", html: "OSHA requiere distancias mínimas de líneas de energía:" },
      { type: "list", items: [
        "<strong>Hasta 50kV:</strong> Mínimo 10 pies",
        "<strong>50kV a 200kV:</strong> Mínimo 15 pies",
        "<strong>200kV a 350kV:</strong> Mínimo 20 pies",
        "<strong>350kV a 500kV:</strong> Mínimo 25 pies",
      ] },
      { type: "heading", level: 3, text: "Reglas de Seguridad con Líneas de Energía" },
      { type: "paragraph", html: "Trate siempre las líneas de energía como <strong>energizadas y peligrosas</strong>. No confíe en el aislamiento. Use un <strong>vigilante</strong> si la pluma podría girar hacia las líneas. Tenga en cuenta el <strong>viento</strong>." },
      { type: "scenario", title: "Decisión con Líneas de Energía",
        prompt: "Le asignan reparar un letrero en la fachada de un edificio. Una línea de distribución de 25kV pasa a unos 12 pies del área de trabajo, y un viento con ráfagas está aumentando. ¿Qué hace?",
        choices: [
          { text: "Proceder con cuidado — 12 pies es más que el mínimo de 10 pies", correct: false, feedback: "El mínimo de 10 pies es un límite absoluto, no una meta. Con ráfagas empujando la plataforma y la posible deriva de la pluma, no puede garantizar la distancia. Deténgase y reevalúe con su supervisor." },
          { text: "Detenerse y coordinar que la línea sea desenergizada, o reposicionarse para que la pluma no pueda alcanzar dentro de 10 pies — y usar un vigilante", correct: true, feedback: "Correcto. Trate cada línea como energizada. Con ráfagas de viento, elimine el peligro mediante la compañía eléctrica o posiciónese de modo que la plataforma físicamente no pueda entrar en la distancia mínima, con un vigilante observando." },
          { text: "Amarrar la plataforma al edificio para que el viento no lo empuje hacia la línea", correct: false, feedback: "Nunca sujete la plataforma ni su línea de seguridad a nada fuera del MEWP. Eso crea un peligro de volcadura y caída — y no hace segura la distancia." },
        ] },
      { type: "heading", level: 3, text: "Si Ocurre Contacto" },
      { type: "paragraph", html: "Si el MEWP contacta una línea de energía:" },
      { type: "list", ordered: true, items: [
        "<strong>Quédese en la plataforma</strong> — no intente saltar",
        "Advierta a otros que se alejen",
        "Llame a emergencias (911) y a la compañía eléctrica",
        "Intente romper el contacto moviendo la pluma",
        "No salga de la plataforma hasta que la línea sea desenergizada",
      ] },
      { type: "heading", level: 3, text: "Seguridad del Personal en Tierra" },
      { type: "paragraph", html: "Si el MEWP está en contacto con una línea, el personal en tierra está en riesgo de electrocución por <strong>potencial de paso</strong>. Deben permanecer a al menos <strong>35 pies</strong> de distancia." },
      { type: "callout", variant: "warning", text: "El contacto con líneas de energía es frecuentemente fatal. Mantenga distancias mínimas en todo momento." },
      { type: "key_takeaways", items: [
        "Mínimo 10 pies de distancia de líneas hasta 50kV",
        "Trate siempre las líneas como energizadas y peligrosas",
        "Si ocurre contacto: quédese en la plataforma, llame al 911",
        "El personal en tierra debe permanecer a 35+ pies de distancia",
      ] },
    ]),
  },
  {
    module: "Peligros del Lugar de Trabajo y Seguridad Eléctrica",
    title: "Peligros Ambientales y del Lugar de Trabajo",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Peligros Ambientales y del Lugar de Trabajo" },
      { type: "heading", level: 2, text: "Peligros Ambientales y del Lugar de Trabajo" },
      { type: "heading", level: 3, text: "Condiciones Climáticas" },
      { type: "list", items: [
        "<strong>Viento:</strong> La mayoría de los MEWPs tienen una clasificación máxima de velocidad del viento (típicamente 28 mph). Nunca la exceda.",
        "<strong>Lluvia y hielo:</strong> Hacen las superficies resbalosas.",
        "<strong>Relámpagos:</strong> Nunca opere un MEWP durante una tormenta — la pluma actúa como pararrayos.",
        "<strong>Nieve y hielo:</strong> Añaden peso, reducen tracción.",
      ] },
      { type: "embedded_quiz", title: "Verificación del Clima", questions: [
        { question: "El viento en el sitio aumenta a 30 mph. La clasificación máxima de viento de su MEWP es 28 mph. ¿Qué debe hacer?", type: "mcq_single", options: ["Continuar — 2 mph sobre el límite es insignificante", "Bajar la plataforma y detener el trabajo elevado hasta que baje el viento", "Subir la plataforma más lento de lo normal", "Agregar peso a la plataforma para estabilidad"], correctAnswers: "Bajar la plataforma y detener el trabajo elevado hasta que baje el viento", explanation: "Nunca exceda la clasificación de viento del fabricante. La fuerza del viento aumenta con la altura — baje la plataforma y espere a que mejoren las condiciones." },
        { question: "Una tormenta eléctrica se acerca a su sitio de trabajo exterior. Usted debe:", type: "mcq_single", options: ["Seguir trabajando hasta que empiece la lluvia", "Bajar la plataforma, detener el trabajo y buscar refugio", "Trabajar más rápido para terminar la tarea", "Elevarse por encima de los árboles para ver mejor"], correctAnswers: "Bajar la plataforma, detener el trabajo y buscar refugio", explanation: "Nunca opere un MEWP durante relámpagos — la pluma puede actuar como pararrayos. Detenga el trabajo antes de que llegue la tormenta." },
      ] },
      { type: "heading", level: 3, text: "Condiciones de Superficie" },
      { type: "paragraph", html: "Antes de operar, verifique: terreno blando, barro, capacidad del piso, hoyos cubiertos, pendientes, superficies mojadas." },
      { type: "heading", level: 3, text: "Peligros Aéreos" },
      { type: "paragraph", html: "Revise siempre peligros aéreos: líneas eléctricas, estructuras de edificios, puertas aéreas, ramas de árboles, objetos que caen." },
      { type: "heading", level: 3, text: "Tráfico de Peatones" },
      { type: "paragraph", html: "Use <strong>barricadas o cinta de precaución</strong>, publique <strong>señales de advertencia</strong>, use un <strong>vigilante</strong> en áreas de alto tráfico, toque la <strong>bocina</strong> al bajar o mover." },
      { type: "callout", variant: "warning", text: "Relámpagos + MEWP = peligro extremo. La pluma actúa como pararrayos. Nunca opere durante tormentas." },
      { type: "key_takeaways", items: [
        "Nunca exceda la clasificación máxima de velocidad del viento del fabricante",
        "Nunca opere un MEWP durante tormentas eléctricas",
        "Revise condiciones de superficie para terreno blando y pendientes",
        "Use barricadas y vigilantes para proteger peatones",
      ] },
    ]),
  },
  {
    module: "Peligros del Lugar de Trabajo y Seguridad Eléctrica",
    title: "Verificación de Conocimiento: Peligros del Lugar de Trabajo",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Cuál es la distancia mínima de líneas de energía hasta 50kV?", type: "mcq_single", options: ["5 pies", "10 pies", "15 pies", "25 pies"], correctAnswers: "10 pies", explanation: "OSHA requiere una distancia mínima de 10 pies de líneas hasta 50kV." },
      { question: "Si un MEWP contacta una línea de energía, el operador debe:", type: "mcq_single", options: ["Saltar inmediatamente", "Quedarse en la plataforma y llamar al 911", "Empujar la línea", "Bajar por la pluma"], correctAnswers: "Quedarse en la plataforma y llamar al 911", explanation: "Quédese en la plataforma — saltar puede causar electrocución. Llame a emergencias." },
      { question: "Nunca debe operar un MEWP durante qué condición climática?", type: "mcq_single", options: ["Llovizna ligera", "Tormenta/relámpagos", "Cielos nublados", "Temperaturas frescas"], correctAnswers: "Tormenta/relámpagos", explanation: "Nunca opere durante una tormenta — la pluma actúa como pararrayos." },
    ],
  },

  // ═══ MÓDULO 6: Procedimientos de Emergencia y Rescate ═══
  {
    module: "Procedimientos de Emergencia y Rescate",
    title: "Controles de Emergencia y Descenso",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Controles de Emergencia y Descenso" },
      { type: "heading", level: 2, text: "Controles de Emergencia y Descenso" },
      { type: "heading", level: 3, text: "Sistema de Descenso de Emergencia" },
      { type: "paragraph", html: "Todos los MEWPs están equipados con <strong>sistemas de descenso de emergencia</strong> que permiten bajar la plataforma desde el suelo si el operador está incapacitado o los controles superiores fallan. Conozca dónde están estos controles antes de operar." },
      { type: "heading", level: 3, text: "Anulación de Controles Inferiores" },
      { type: "paragraph", html: "Según OSHA 1926.453(b)(2)(iii), los controles inferiores deben poder <strong>anular los controles superiores</strong>. Esto permite que una persona en el suelo baje la plataforma en una emergencia." },
      { type: "heading", level: 3, text: "Parada de Emergencia" },
      { type: "paragraph", html: "Todos los MEWPs tienen <strong>botones de parada de emergencia</strong> en ambas estaciones de control. Presionar el botón detiene inmediatamente todas las funciones. Debe restablecerse manualmente." },
      { type: "heading", level: 3, text: "Falla de Energía" },
      { type: "paragraph", html: "Si se pierde energía mientras la plataforma está elevada: no entre en pánico, use la <strong>válvula manual de descenso</strong>, llame para asistencia si no puede bajar." },
      { type: "callout", variant: "tip", text: "Antes de operar, localice y pruebe todos los controles de emergencia." },
      { type: "key_takeaways", items: [
        "Conozca la ubicación de los controles de descenso de emergencia",
        "Los controles inferiores pueden anular los superiores",
        "Los botones de parada están en ambas estaciones",
        "Si falla la energía, use sistemas de descenso manual",
      ] },
    ]),
  },
  {
    module: "Procedimientos de Emergencia y Rescate",
    title: "Planificación y Procedimientos de Rescate",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pedestrian-safety.svg"), alt: "Planificación y Procedimientos de Rescate" },
      { type: "heading", level: 2, text: "Planificación y Procedimientos de Rescate" },
      { type: "heading", level: 3, text: "Requisitos de Rescate ANSI A92.22" },
      { type: "paragraph", html: "ANSI A92.22 requiere que se desarrolle un <strong>plan de rescate</strong> antes del uso del MEWP. Debe abordar cómo se recuperará a un operador si no puede operar los controles." },
      { type: "heading", level: 3, text: "Componentes del Plan" },
      { type: "paragraph", html: "Identificación de <strong>personal de rescate capacitado</strong>, ubicación de controles inferiores, acceso a un <strong>MEWP secundario</strong>, números de contacto de emergencia." },
      { type: "heading", level: 3, text: "Si el Operador Está Incapacitado" },
      { type: "paragraph", html: "Use los <strong>controles inferiores</strong> para bajar la plataforma. Si fallan, use la <strong>válvula de descenso de emergencia</strong>. Si no puede bajar, use un <strong>MEWP secundario</strong>. Llame al <strong>911</strong>." },
      { type: "heading", level: 3, text: "Respuesta a Volcadura" },
      { type: "paragraph", html: "<strong>Quédese en la plataforma</strong> — no salte. Brácese y sujete las barandillas. Pida ayuda. Busque evaluación médica." },
      { type: "callout", variant: "warning", text: "Nunca intente escalar la pluma o el mecanismo de tijera para rescatar a alguien." },
      { type: "key_takeaways", items: [
        "ANSI A92.22 requiere un plan de rescate antes del uso del MEWP",
        "Identifique personal de rescate capacitado antes de comenzar",
        "Use controles inferiores o descenso de emergencia para rescatar",
        "En una volcadura, quédese en la plataforma y no salte",
      ] },
    ]),
  },
  {
    module: "Procedimientos de Emergencia y Rescate",
    title: "Verificación de Conocimiento: Procedimientos de Emergencia",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "¿Qué requiere ANSI A92.22 antes del uso del MEWP?", type: "mcq_single", options: ["Un plan de rescate", "Un reporte climático", "Un segundo operador", "Una batería de respaldo"], correctAnswers: "Un plan de rescate", explanation: "ANSI A92.22 requiere un plan de rescate antes del uso del MEWP." },
      { question: "Si ocurre una volcadura, el operador debe:", type: "mcq_single", options: ["Saltar inmediatamente", "Quedarse en la plataforma y sujetarse", "Intentar enderezar el MEWP", "Bajar por la pluma"], correctAnswers: "Quedarse en la plataforma y sujetarse", explanation: "Quédese en la plataforma durante una volcadura. No salte." },
      { question: "El botón de parada de emergencia está ubicado en:", type: "mcq_single", options: ["Solo en controles superiores", "Solo en controles inferiores", "Ambas estaciones de control", "Solo en el chasis"], correctAnswers: "Ambas estaciones de control", explanation: "Los botones de parada están en ambas estaciones de control." },
    ],
  },

  // ═══ MÓDULO 7: Examen Final y Finalización ═══
  {
    module: "Examen Final y Finalización",
    title: "Examen Final: Certificación de Elevadores Aéreos y de Tijera",
    type: "exam",
    estimatedMinutes: 15,
    config: { passing_score: 80, max_attempts: 3, randomize_questions: true },
    questions: [
      { question: "¿Qué norma de OSHA cubre específicamente los elevadores aéreos?", type: "mcq_single", options: ["29 CFR 1910.178", "29 CFR 1926.453", "29 CFR 1910.147", "29 CFR 1926.450"], correctAnswers: "29 CFR 1926.453", explanation: "29 CFR 1926.453 es la norma de OSHA para elevadores aéreos." },
      { question: "¿Un elevador de tijera está clasificado como qué grupo de MEWP?", type: "mcq_single", options: ["Grupo A", "Grupo B", "Grupo C", "Grupo D"], correctAnswers: "Grupo A", explanation: "Los elevadores de tijera son MEWPs del Grupo A." },
      { question: "¿Con qué frecuencia deben probarse los controles antes del uso?", type: "mcq_single", options: ["Semanalmente", "Mensualmente", "Cada día antes del uso", "Solo después de reparaciones"], correctAnswers: "Cada día antes del uso", explanation: "29 CFR 1926.453(a)(1) requiere probar los controles cada día antes del uso." },
      { question: "Desde el 1 de enero de 1998, qué tipo de protección contra caídas es requerida?", type: "mcq_single", options: ["Solo cinturón corporal", "Arnés de cuerpo completo", "Sin protección", "Una red de seguridad"], correctAnswers: "Arnés de cuerpo completo", explanation: "Los cinturones corporales no son aceptables desde 1998. Se requieren arneses de cuerpo completo." },
      { question: "¿Cuál es la distancia mínima de líneas de energía hasta 50kV?", type: "mcq_single", options: ["5 pies", "10 pies", "15 pies", "25 pies"], correctAnswers: "10 pies", explanation: "OSHA requiere mínimo 10 pies de líneas hasta 50kV." },
      { question: "Si un MEWP contacta una línea de energía, el operador debe:", type: "mcq_single", options: ["Saltar inmediatamente", "Quedarse en la plataforma y llamar al 911", "Empujar la línea", "Bajar por la pluma"], correctAnswers: "Quedarse en la plataforma y llamar al 911", explanation: "Quédese en la plataforma — saltar puede causar electrocución." },
      { question: "¿Qué debe hacer si encuentra un defecto durante la inspección?", type: "mcq_single", options: ["Continuar y reportar después", "Marcarlo fuera de servicio y no operar", "Usarlo para tareas cortas", "Repararlo con cinta"], correctAnswers: "Marcarlo fuera de servicio y no operar", explanation: "Cualquier defecto requiere marcar el equipo fuera de servicio." },
      { question: "La línea de seguridad debe attacherse a:", type: "mcq_single", options: ["Cualquier objeto cercano", "El punto de anclaje designado por el fabricante", "Una viga del edificio", "La protección superior"], correctAnswers: "El punto de anclaje designado por el fabricante", explanation: "Siempre attache al punto de anclaje designado por el fabricante." },
      { question: "Nunca opere un MEWP durante qué condición?", type: "mcq_single", options: ["Llovizna ligera", "Tormenta/relámpagos", "Cielos nublados", "Clima fresco"], correctAnswers: "Tormenta/relámpagos", explanation: "Nunca opere durante tormentas — la pluma actúa como pararrayos." },
      { question: "Si ocurre una volcadura, el operador debe:", type: "mcq_single", options: ["Saltar inmediatamente", "Quedarse en la plataforma y sujetarse", "Intentar enderezar el MEWP", "Apagar el motor"], correctAnswers: "Quedarse en la plataforma y sujetarse", explanation: "Quédese en la plataforma. No salte. Brácese y pida ayuda." },
      { question: "¿Qué requiere ANSI A92.22 antes del uso del MEWP?", type: "mcq_single", options: ["Un plan de rescate", "Un reporte climático", "Un segundo operador", "Una grabación"], correctAnswers: "Un plan de rescate", explanation: "ANSI A92.22 requiere un plan de rescate." },
      { question: "Los controles inferiores en un MEWP deben poder:", type: "mcq_single", options: ["Solo conducir", "Anular los controles superiores en emergencia", "Bloquearse permanentemente", "Solo reabastecimiento"], correctAnswers: "Anular los controles superiores en emergencia", explanation: "Los controles inferiores deben poder anular los superiores." },
      { question: "Las baterías en carga producen qué gas explosivo?", type: "mcq_single", options: ["Oxígeno", "Nitrógeno", "Hidrógeno", "Dióxido de carbono"], correctAnswers: "Hidrógeno", explanation: "Las baterías producen gas hidrógeno durante la carga." },
      { question: "¿Qué sucede si el centro de gravedad se mueve fuera de las líneas de volcadura?", type: "mcq_single", options: ["Nada", "El MEWP se volcará", "Sonará una alarma", "Bajará automáticamente"], correctAnswers: "El MEWP se volcará", explanation: "Si el centro de gravedad se mueve fuera, el MEWP se volcará." },
      { question: "La capacidad nominal incluye el peso de:", type: "mcq_single", options: ["Solo personal", "Solo herramientas", "Personal, herramientas y materiales", "Solo plataforma"], correctAnswers: "Personal, herramientas y materiales", explanation: "Incluye el peso combinado de todo." },
      { question: "Un camión de elevación no debe moverse con la pluma elevada a menos que:", type: "mcq_single", options: ["El supervisor apruebe", "El equipo esté diseñado para esto", "Sea emergencia", "Los trabajadores usen arnés"], correctAnswers: "El equipo esté diseñado para esto", explanation: "Per OSHA 1926.453(b)(2)(vii), no mover a menos que esté específicamente diseñado." },
      { question: "Prohibido fumar dentro de cuántos pies de baterías en carga?", type: "mcq_single", options: ["10 pies", "25 pies", "50 pies", "100 pies"], correctAnswers: "50 pies", explanation: "Prohibido fumar dentro de 50 pies de áreas de carga." },
      { question: "Este curso en línea satisface completamente todos los requisitos de OSHA.", type: "mcq_single", options: ["Verdadero", "Falso"], correctAnswers: "Falso", explanation: "OSHA requiere instrucción formal MÁS capacitación práctica y evaluación." },
      { question: "El personal en tierra debe permanecer a cuánta distancia de un MEWP en contacto con línea eléctrica?", type: "mcq_single", options: ["10 pies", "25 pies", "35 pies", "50 pies"], correctAnswers: "35 pies", explanation: "Mínimo 35 pies debido al potencial de paso." },
      { question: "Los empleados siempre deben pararse firmemente en el ___ de la canasta.", type: "mcq_single", options: ["Borde", "Piso", "Barandilla", "Barandilla intermedia"], correctAnswers: "Piso", explanation: "OSHA requiere pararse en el piso de la canasta." },
      { question: "Qué debe desplegarse antes de elevar un elevador de pluma que los requiere?", type: "mcq_single", options: ["Estabilizadores", "Cables de extensión", "Redes de seguridad", "Escaleras de cuerda"], correctAnswers: "Estabilizadores", explanation: "Los estabilizadores deben desplegarse antes de elevar." },
      { question: "Nunca opere un MEWP excediendo la máxima:", type: "mcq_single", options: ["Clasificación de color", "Clasificación de velocidad del viento", "Clasificación de decibeles", "Presión de llantas"], correctAnswers: "Clasificación de velocidad del viento", explanation: "Nunca exceda la clasificación máxima de viento (típicamente 28 mph)." },
    ],
  },
  {
    module: "Examen Final y Finalización",
    title: "Felicitaciones: ¿Qué Sigue?",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: img("aerial-lift-hero.svg"), alt: "¡Está Certificado! ¿Qué Sigue?" },
      { type: "heading", level: 2, text: "¡Está Certificado! ¿Qué Sigue?" },
      { type: "heading", level: 3, text: "Su Certificado" },
      { type: "paragraph", html: "¡Felicitaciones por completar la porción de instrucción formal de su certificación de operador de elevadores aéreos y de tijera! Su certificado digital está disponible para descargar con número único y código QR." },
      { type: "heading", level: 3, text: "Siguiente Paso: Evaluación Práctica" },
      { type: "paragraph", html: "Su empleador debe completar la <strong>capacitación práctica y evaluación</strong> en el equipo específico. Comparta el paquete de documentación con su supervisor." },
      { type: "heading", level: 3, text: "Manténgase Seguro" },
      { type: "paragraph", html: "Continúe siguiendo procedimientos de operación segura. Si necesita repaso, puede volver a este curso en cualquier momento." },
      { type: "callout", variant: "tip", text: "Guarde el enlace de su página de verificación para verificación instantánea." },
      { type: "key_takeaways", items: [
        "Descargue su certificado",
        "Comparta el paquete del empleador para evaluación práctica",
        "Su empleador debe proporcionar capacitación específica al equipo",
        "La re-evaluación es requerida al menos cada 3 años",
      ] },
    ]),
  },
];
