import type { LessonBlock } from "@shared/lesson-blocks";

export interface StepDef {
  title: string;
  type: "lesson" | "video" | "checkpoint" | "download" | "exam" | "content";
  config: any;
  estimatedMinutes: number;
  module: string;
  questions?: QuestionDef[];
}

export interface QuestionDef {
  question: string;
  type: "mcq_single" | "mcq_multi";
  options: string[];
  correctAnswers: string;
  explanation: string;
}

export const CANONICAL_COURSE = {
  title: "Forklift Train the Trainer Certification",
  slug: "online-forklift-train-the-trainer",
  description: "Comprehensive OSHA-compliant Train the Trainer certification for forklift operator training. Covers OSHA 29 CFR 1910.178(l)(2)(iii) trainer qualifications, adult learning principles, training program design, all required OSHA topics, practical training methodology, operator evaluation, program administration, and safety culture. Upon completion, you will be qualified to train and evaluate forklift operators at your facility.",
  category: "trainer",
  price: "150.00",
};

const img = (name: string) => `/images/training/${name}`;

const blocks = (b: LessonBlock[]) => ({ blocks: b });

export const COURSE_STEPS: StepDef[] = [
  // ═══ MODULE 0: OSHA Regulatory Framework ═══
  {
    module: "OSHA Regulatory Framework",
    title: "Welcome & OSHA Regulatory Framework",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "Welcome & OSHA Regulatory Framework" },
      { type: "heading", level: 2, text: "Welcome & OSHA Regulatory Framework" },
      { type: "heading", level: 3, text: "About This Course" },
      { type: "paragraph", html: "Welcome to the Forklift Train the Trainer Certification! This course prepares you to become a <strong>qualified forklift operator trainer</strong> under OSHA 29 CFR 1910.178(l)(2)(iii). The course takes approximately <strong>2-3 hours</strong> to complete." },
      { type: "heading", level: 3, text: "Trainer Qualifications (1910.178(l)(2)(iii))" },
      { type: "paragraph", html: "OSHA states: <em>\"All operator training and evaluation shall be conducted by persons who have the knowledge, training, and experience to train powered industrial truck operators and evaluate their competence.\"</em>" },
      { type: "paragraph", html: "OSHA does <strong>not</strong> require a specific certification for trainers. Instead, the standard requires three qualifications:" },
      { type: "list", ordered: true, items: [
        "<strong>Knowledge</strong> — of the OSHA standard and the subject matter",
        "<strong>Training</strong> — formal training on the topics they will teach",
        "<strong>Experience</strong> — practical experience operating the equipment",
      ] },
      { type: "flip_cards", title: "The Three Trainer Qualifications", cards: [
        { front: "Knowledge", back: "You must know the OSHA standard (29 CFR 1910.178) and the subject matter thoroughly — capacity, stability, inspections, and safe operating rules." },
        { front: "Training", back: "You must have received formal training on the topics you will teach. This course provides that formal trainer training." },
        { front: "Experience", back: "You must have practical experience operating the equipment. A trainer who cannot demonstrate a skill cannot credibly teach or evaluate it." },
      ] },
      { type: "heading", level: 3, text: "What This Course Covers" },
      { type: "list", items: [
        "Complete review of 29 CFR 1910.178",
        "Employer responsibilities under the standard",
        "Documentation and certification requirements (1910.178(l)(6))",
        "All 22 required training topics (truck-related and workplace-related)",
        "Adult learning principles and training methodology",
        "Practical training design and operator evaluation",
        "Program administration and safety culture",
      ] },
      { type: "heading", level: 3, text: "Important Note" },
      { type: "paragraph", html: "This Train the Trainer course qualifies you to <strong>train and evaluate operators</strong>. It does <strong>not</strong> certify you to operate equipment. You must already be a competent forklift operator before taking this course. The trainer must maintain their own operator competence." },
      { type: "callout", variant: "warning", text: "This course does not certify you to operate a forklift. You must already be a competent operator." },
      { type: "key_takeaways", items: [
        "OSHA requires trainers to have knowledge, training, and experience",
        "No specific trainer certification is required by OSHA",
        "This course covers the formal training component for trainers",
        "Train the Trainer does NOT certify you to operate equipment",
      ] },
    ]),
  },
  {
    module: "OSHA Regulatory Framework",
    title: "Employer Responsibilities & Documentation",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "Employer Responsibilities & Documentation" },
      { type: "heading", level: 2, text: "Employer Responsibilities & Documentation" },
      { type: "heading", level: 3, text: "Employer's Duty (1910.178(l)(1))" },
      { type: "paragraph", html: "The employer is responsible for ensuring that each operator is <strong>trained</strong>, <strong>evaluated</strong>, and <strong>certified</strong> as required. This includes:" },
      { type: "list", items: [
        "Initial training for new operators",
        "Evaluation of operator competence in the workplace",
        "Refresher training when needed (accidents, unsafe operation, new equipment)",
        "Re-evaluation at least every 3 years",
      ] },
      { type: "heading", level: 3, text: "Certification Requirements (1910.178(l)(6))" },
      { type: "paragraph", html: "The employer must certify that each operator has been trained and evaluated. The certification must include:" },
      { type: "list", items: [
        "<strong>Name of the operator</strong>",
        "<strong>Date of the training</strong>",
        "<strong>Date of the evaluation</strong>",
        "<strong>Identity of the person(s)</strong> performing the training or evaluation",
      ] },
      { type: "heading", level: 3, text: "Record-Keeping" },
      { type: "paragraph", html: "Training records should be maintained and available for OSHA inspection. While OSHA does not specify a retention period, best practice is to keep records for the duration of employment plus 3 years. Records should include:" },
      { type: "list", items: [
        "Training curriculum and topics covered",
        "Evaluation checklists and results",
        "Operator permits/authorizations",
        "Refresher training records",
        "Accident/near-miss reports and subsequent retraining",
      ] },
      { type: "heading", level: 3, text: "OSHA Inspection & Enforcement" },
      { type: "paragraph", html: "OSHA can conduct <strong>unannounced inspections</strong>. Fines for non-compliance can reach <strong>$15,625 per violation</strong> (as of 2023) for serious violations, and up to <strong>$156,259</strong> for willful or repeated violations. Having proper training documentation is your first line of defense." },
      { type: "callout", variant: "tip", text: "Create a training file for each operator containing their certification, evaluation forms, and any refresher training records." },
      { type: "key_takeaways", items: [
        "The employer is ultimately responsible for operator training and evaluation",
        "Certification must include operator name, training date, eval date, and trainer identity",
        "Maintain training records for employment duration plus 3 years",
        "OSHA fines for non-compliance can exceed $15,000 per violation",
      ] },
    ]),
  },
  {
    module: "OSHA Regulatory Framework",
    title: "Knowledge Check: OSHA Framework",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "What three qualifications must a forklift trainer have under OSHA 1910.178(l)(2)(iii)?", type: "mcq_single", options: ["A college degree, a teaching certificate, and 5 years experience", "Knowledge, training, and experience", "A high school diploma, forklift certification, and supervisor approval", "OSHA certification, first aid training, and a CDL"], correctAnswers: "Knowledge, training, and experience", explanation: "OSHA requires trainers to have the knowledge, training, and experience to train operators and evaluate their competence." },
      { question: "What must the operator certification include per 1910.178(l)(6)?", type: "mcq_single", options: ["Operator's Social Security Number", "Operator name, training date, evaluation date, and trainer identity", "Operator's medical records", "Only the operator's signature"], correctAnswers: "Operator name, training date, evaluation date, and trainer identity", explanation: "The certification must include the operator's name, date of training, date of evaluation, and the identity of the trainer/evaluator." },
      { question: "How often must operators be re-evaluated per OSHA?", type: "mcq_single", options: ["Every year", "Every 2 years", "Every 3 years", "Every 5 years"], correctAnswers: "Every 3 years", explanation: "OSHA requires operator re-evaluation at least every three years under 1910.178(l)(4)(iii)." },
    ],
  },

  // ═══ MODULE 1: Adult Learning Principles ═══
  {
    module: "Adult Learning Principles",
    title: "How Adults Learn: Andragogy Basics",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "How Adults Learn: Andragogy Basics" },
      { type: "heading", level: 2, text: "How Adults Learn: Andragogy Basics" },
      { type: "heading", level: 3, text: "Adult Learning Theory" },
      { type: "paragraph", html: "Adults learn differently than children. Malcolm Knowles identified key principles of adult learning (<strong>andragogy</strong>):" },
      { type: "list", items: [
        "<strong>Self-directed:</strong> Adults want to take responsibility for their learning",
        "<strong>Experience-based:</strong> Adults bring life experience that is a valuable resource",
        "<strong>Relevance-oriented:</strong> Adults learn best when content is directly relevant to their work",
        "<strong>Problem-centered:</strong> Adults prefer learning that solves real problems",
        "<strong>Motivated internally:</strong> Adults are motivated by factors like self-esteem, better quality of work, etc.",
      ] },
      { type: "heading", level: 3, text: "Learning Styles" },
      { type: "paragraph", html: "People learn through different modalities. Include all three in your training:" },
      { type: "list", items: [
        "<strong>Visual:</strong> Diagrams, videos, demonstrations, charts",
        "<strong>Auditory:</strong> Lectures, discussions, verbal explanations",
        "<strong>Kinesthetic:</strong> Hands-on practice, equipment operation, role-playing",
      ] },
      { type: "heading", level: 3, text: "Effective Presentation Techniques" },
      { type: "list", items: [
        "Start with the <strong>why</strong> — explain the safety rationale",
        "Use <strong>real-world examples</strong> from the workplace",
        "Keep sessions <strong>short</strong> (15-20 minutes per topic)",
        "Encourage <strong>questions and discussion</strong>",
        "Use <strong>multimedia</strong> — videos, slides, demonstrations",
        "Check for understanding frequently",
        "Provide <strong>hands-on practice</strong> immediately after instruction",
      ] },
      { type: "heading", level: 3, text: "Managing Group Dynamics" },
      { type: "paragraph", html: "As a trainer, you must manage the group effectively:" },
      { type: "list", items: [
        "Create a <strong>safe learning environment</strong> where questions are welcomed",
        "Handle <strong>dominant participants</strong> by redirecting to others",
        "Draw out <strong>quiet participants</strong> by asking for their input",
        "Address <strong>safety misconceptions</strong> directly and respectfully",
        "Keep the training <strong>on schedule</strong>",
      ] },
      { type: "callout", variant: "tip", text: "Ask trainees about their experience at the start of training. Their stories make great teaching examples." },
      { type: "key_takeaways", items: [
        "Adults are self-directed, experience-based, and relevance-oriented learners",
        "Include visual, auditory, and kinesthetic elements in training",
        "Start with the 'why' and use real-world examples",
        "Create a safe learning environment and manage group dynamics",
      ] },
    ]),
  },
  {
    module: "Adult Learning Principles",
    title: "Assessment Strategies",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Assessment Strategies" },
      { type: "heading", level: 2, text: "Assessment Strategies" },
      { type: "heading", level: 3, text: "Knowledge Assessment" },
      { type: "paragraph", html: "Test understanding of formal instruction through:" },
      { type: "list", items: [
        "<strong>Written tests</strong> — multiple choice, true/false, short answer",
        "<strong>Oral questioning</strong> — ask trainees to explain concepts",
        "<strong>Quizzes throughout</strong> — not just at the end",
        "<strong>Case studies</strong> — present scenarios and ask for the correct response",
      ] },
      { type: "heading", level: 3, text: "Practical Assessment" },
      { type: "paragraph", html: "Evaluate hands-on skills through:" },
      { type: "list", items: [
        "<strong>Demonstration</strong> — have trainees demonstrate each skill",
        "<strong>Observation</strong> — observe operators performing real tasks",
        "<strong>Checklist evaluation</strong> — use standardized checklists",
        "<strong>Progressive evaluation</strong> — start simple, add complexity",
      ] },
      { type: "heading", level: 3, text: "Pass/Fail Criteria" },
      { type: "paragraph", html: "Establish clear pass/fail criteria before training begins:" },
      { type: "list", items: [
        "What score constitutes passing (typically 80%)",
        "Which practical skills are mandatory",
        "What constitutes a critical safety failure (automatic fail)",
        "How many attempts are allowed",
        "What remediation is provided for failures",
      ] },
      { type: "heading", level: 3, text: "Providing Feedback" },
      { type: "paragraph", html: "Give <strong>constructive feedback</strong> that is:" },
      { type: "list", items: [
        "<strong>Specific</strong> — point to exact behaviors",
        "<strong>Timely</strong> — immediately after the observation",
        "<strong>Balanced</strong> — address both strengths and areas for improvement",
        "<strong>Actionable</strong> — tell them what to do differently",
      ] },
      { type: "key_takeaways", items: [
        "Use both knowledge and practical assessments",
        "Establish clear pass/fail criteria before training begins",
        "Use standardized checklists for practical evaluations",
        "Provide specific, timely, balanced, and actionable feedback",
      ] },
    ]),
  },
  {
    module: "Adult Learning Principles",
    title: "Knowledge Check: Adult Learning",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Adults learn best when training is:", type: "mcq_single", options: ["Purely theoretical", "Directly relevant to their work", "Memorization-based", "Conducted in long sessions"], correctAnswers: "Directly relevant to their work", explanation: "Adults are relevance-oriented — they learn best when content is directly applicable to their job." },
      { question: "Which is NOT one of the three learning styles?", type: "mcq_single", options: ["Visual", "Auditory", "Kinesthetic", "Olfactory"], correctAnswers: "Olfactory", explanation: "The three main learning styles are visual, auditory, and kinesthetic. Olfactory (smell) is not a learning style." },
      { question: "Feedback should be:", type: "mcq_single", options: ["Delayed by several days", "General and vague", "Specific, timely, balanced, and actionable", "Only about weaknesses"], correctAnswers: "Specific, timely, balanced, and actionable", explanation: "Effective feedback is specific, timely, balanced (strengths and weaknesses), and actionable." },
    ],
  },

  // ═══ MODULE 2: Training Program Design ═══
  {
    module: "Training Program Design",
    title: "Designing Your Training Program",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "Designing Your Training Program" },
      { type: "heading", level: 2, text: "Designing Your Training Program" },
      { type: "heading", level: 3, text: "Needs Assessment" },
      { type: "paragraph", html: "Before designing training, identify what your operators need to know:" },
      { type: "list", items: [
        "<strong>Equipment types</strong> in use at your facility",
        "<strong>Workplace conditions</strong> — surfaces, ramps, docks, pedestrian traffic",
        "<strong>Operator experience levels</strong> — new vs. experienced",
        "<strong>Site-specific hazards</strong> and safety incidents",
        "<strong>Regulatory requirements</strong> — OSHA 1910.178(l)(3)",
      ] },
      { type: "heading", level: 3, text: "Learning Objectives" },
      { type: "paragraph", html: "Write <strong>measurable learning objectives</strong> using action verbs:" },
      { type: "list", items: [
        "\"The operator will <strong>demonstrate</strong> a pre-shift inspection...\"",
        "\"The operator will <strong>identify</strong> the stability triangle...\"",
        "\"The operator will <strong>perform</strong> a safe load pickup...\"",
      ] },
      { type: "paragraph", html: "Avoid vague objectives like \"understand\" or \"know\" — these can't be measured." },
      { type: "heading", level: 3, text: "Curriculum Structure" },
      { type: "paragraph", html: "Structure your training in logical modules:" },
      { type: "list", ordered: true, items: [
        "<strong>Formal instruction</strong> (classroom/online) — theory and knowledge",
        "<strong>Practical training</strong> — hands-on demonstrations and guided practice",
        "<strong>Evaluation</strong> — assess both knowledge and skills",
        "<strong>Documentation</strong> — complete certification records",
      ] },
      { type: "drag_drop", mode: "ordering",
        prompt: "Arrange the phases of an OSHA-compliant training program in the correct order.",
        items: [
          { id: "phase-formal", label: "Formal instruction — theory and knowledge" },
          { id: "phase-practical", label: "Practical training — demonstrations and guided practice" },
          { id: "phase-evaluation", label: "Evaluation — assess knowledge and skills" },
          { id: "phase-documentation", label: "Documentation — complete certification records" },
        ] },
      { type: "heading", level: 3, text: "Training Materials" },
      { type: "paragraph", html: "Prepare materials including:" },
      { type: "list", items: [
        "PowerPoint or slide presentations",
        "Equipment manuals and OSHA standards",
        "Pre-operation inspection checklists",
        "Practical evaluation forms",
        "Written test and answer key",
        "Site-specific safety rules",
        "Visual aids — diagrams of stability triangle, load center, etc.",
      ] },
      { type: "callout", variant: "tip", text: "Customize your training to your specific workplace — generic training misses site-specific hazards." },
      { type: "key_takeaways", items: [
        "Start with a needs assessment of your facility and operators",
        "Write measurable learning objectives with action verbs",
        "Structure training: formal instruction, practical, evaluation, documentation",
        "Prepare all materials before the training session",
      ] },
    ]),
  },
  {
    module: "Training Program Design",
    title: "Designing Practical Exercises",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Designing Practical Exercises" },
      { type: "heading", level: 2, text: "Designing Practical Exercises" },
      { type: "heading", level: 3, text: "Progressive Skill Building" },
      { type: "paragraph", html: "Design exercises that build skills progressively:" },
      { type: "list", ordered: true, items: [
        "<strong>Basic controls</strong> — starting, steering, stopping",
        "<strong>Simple maneuvers</strong> — forward, reverse, turning",
        "<strong>Load handling</strong> — picking up, carrying, stacking",
        "<strong>Complex operations</strong> — ramps, docks, narrow aisles",
        "<strong>Site-specific tasks</strong> — actual workplace scenarios",
      ] },
      { type: "heading", level: 3, text: "Setting Up Practice Courses" },
      { type: "paragraph", html: "Create a designated practice area with:" },
      { type: "list", items: [
        "Cones or markers for steering courses",
        "Pallets and loads for handling practice",
        "Simulated ramp or dock area",
        "Narrow aisle simulation",
        "Clear space away from pedestrians and traffic",
      ] },
      { type: "heading", level: 3, text: "Guided Practice Technique" },
      { type: "list", ordered: true, items: [
        "<strong>Demonstrate</strong> the skill yourself first",
        "<strong>Explain</strong> each step as you perform it",
        "Have the trainee <strong>practice</strong> with your guidance",
        "Provide <strong>immediate feedback</strong>",
        "Allow <strong>independent practice</strong> once competent",
        "Evaluate the final performance",
      ] },
      { type: "heading", level: 3, text: "Correcting Unsafe Behaviors" },
      { type: "paragraph", html: "When you observe unsafe behavior during practice:" },
      { type: "list", items: [
        "<strong>Stop</strong> the operation immediately",
        "Explain <strong>why</strong> the behavior is unsafe",
        "Demonstrate the <strong>correct</strong> procedure",
        "Have the trainee <strong>redo</strong> the operation correctly",
        "Document any <strong>recurring issues</strong>",
      ] },
      { type: "key_takeaways", items: [
        "Build skills progressively from basic controls to complex operations",
        "Set up a designated practice area away from traffic",
        "Use demonstrate-explain-practice-feedback cycle",
        "Stop unsafe behavior immediately and correct it",
      ] },
    ]),
  },
  {
    module: "Training Program Design",
    title: "Knowledge Check: Program Design",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Learning objectives should use:", type: "mcq_single", options: ["Vague terms like 'understand'", "Measurable action verbs like 'demonstrate'", "Long paragraphs", "Only the instructor's goals"], correctAnswers: "Measurable action verbs like 'demonstrate'", explanation: "Objectives should use measurable action verbs so you can verify the trainee achieved them." },
      { question: "The recommended progression for practical training is:", type: "mcq_single", options: ["Start with complex operations", "Start with basic controls and build progressively", "Only test at the end", "Skip to site-specific tasks"], correctAnswers: "Start with basic controls and build progressively", explanation: "Build skills progressively: basic controls, simple maneuvers, load handling, complex operations, site-specific tasks." },
      { question: "When you observe unsafe behavior during practice, you should:", type: "mcq_single", options: ["Wait until the end to address it", "Stop the operation immediately", "Ignore minor issues", "Only report it to the supervisor"], correctAnswers: "Stop the operation immediately", explanation: "Stop unsafe behavior immediately, explain why it's unsafe, demonstrate the correct way, and have the trainee redo it." },
    ],
  },

  // ═══ MODULE 3: Required Training Topics Deep Dive ═══
  {
    module: "Required Topics Deep Dive",
    title: "Truck-Related Topics (1910.178(l)(3)(i))",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("forklift-hero.svg"), alt: "Truck-Related Topics (1910.178(l)(3)(i))" },
      { type: "heading", level: 2, text: "Truck-Related Topics (1910.178(l)(3)(i))" },
      { type: "heading", level: 3, text: "OSHA Requires 13 Truck-Related Topics" },
      { type: "paragraph", html: "OSHA 1910.178(l)(3)(i) requires training on <strong>13 truck-related topics</strong>. As a trainer, you must cover ALL of these in your operator training:" },
      { type: "heading", level: 3, text: "Topics A-E: Operating Knowledge" },
      { type: "list", items: [
        "<strong>(A)</strong> Operating instructions, warnings, and precautions for the types of truck",
        "<strong>(B)</strong> Differences between the truck and the automobile",
        "<strong>(C)</strong> Truck controls and instrumentation: location, function, and operation",
        "<strong>(D)</strong> Engine or motor operation",
        "<strong>(E)</strong> Steering and maneuvering",
      ] },
      { type: "heading", level: 3, text: "Topics F-I: Visibility and Capacity" },
      { type: "list", items: [
        "<strong>(F)</strong> Visibility (including restrictions due to loading)",
        "<strong>(G)</strong> Fork and attachment adaptation, operation, and use limitations",
        "<strong>(H)</strong> Vehicle capacity",
        "<strong>(I)</strong> Vehicle stability (stability triangle)",
      ] },
      { type: "heading", level: 3, text: "Topics J-M: Maintenance and Limitations" },
      { type: "list", items: [
        "<strong>(J)</strong> Any vehicle inspection and maintenance the operator must perform",
        "<strong>(K)</strong> Refueling and/or charging and recharging of batteries",
        "<strong>(L)</strong> Operating limitations",
        "<strong>(M)</strong> Any other operating instructions, warnings, or precautions from the operator's manual",
      ] },
      { type: "heading", level: 3, text: "Teaching Tips for Truck-Related Topics" },
      { type: "list", items: [
        "Use the <strong>actual equipment</strong> for controls and instrumentation",
        "Have operators <strong>demonstrate</strong> each control function",
        "Show the <strong>data plate</strong> and explain capacity ratings",
        "Demonstrate the <strong>stability triangle</strong> visually",
        "Walk through a complete <strong>pre-shift inspection</strong>",
      ] },
      { type: "embedded_quiz", questions: [
        { question: "What is the most effective way to teach truck controls and instrumentation?", type: "mcq_single", options: ["Show photos in a slideshow", "Use the actual equipment operators will use", "Have operators read the manual on their own", "Describe the controls verbally"], correctAnswers: "Use the actual equipment operators will use", explanation: "Controls and instrumentation should be taught on the actual equipment, with operators demonstrating each control function themselves." },
        { question: "Vehicle stability (the stability triangle) falls under which category of required topics?", type: "mcq_single", options: ["Truck-related topics", "Workplace-related topics", "Optional topics", "Trainer-only topics"], correctAnswers: "Truck-related topics", explanation: "Vehicle stability is topic (I) of the 13 truck-related topics required by 1910.178(l)(3)(i)." },
      ] },
      { type: "callout", variant: "tip", text: "Create a checklist of all 13 topics and check them off as you cover each one during training." },
      { type: "key_takeaways", items: [
        "OSHA requires 13 truck-related topics under 1910.178(l)(3)(i)",
        "Cover controls, steering, visibility, capacity, stability, inspection, and maintenance",
        "Use the actual equipment for teaching controls and instrumentation",
        "Demonstrate the stability triangle visually for better understanding",
      ] },
    ]),
  },
  {
    module: "Required Topics Deep Dive",
    title: "Workplace-Related Topics (1910.178(l)(3)(ii))",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Workplace-Related Topics (1910.178(l)(3)(ii))" },
      { type: "heading", level: 2, text: "Workplace-Related Topics (1910.178(l)(3)(ii))" },
      { type: "heading", level: 3, text: "OSHA Requires 9 Workplace-Related Topics" },
      { type: "paragraph", html: "OSHA 1910.178(l)(3)(ii) requires training on <strong>9 workplace-related topics</strong>. These are site-specific and must be tailored to your facility:" },
      { type: "heading", level: 3, text: "Topics A-C: Surface and Load Conditions" },
      { type: "list", items: [
        "<strong>(A)</strong> Surface conditions where the vehicle will be operated",
        "<strong>(B)</strong> Composition of loads to be carried and load stability",
        "<strong>(C)</strong> Load manipulation, stacking, and unstacking",
      ] },
      { type: "heading", level: 3, text: "Topics D-F: Traffic and Hazards" },
      { type: "list", items: [
        "<strong>(D)</strong> Pedestrian traffic in areas where the vehicle will be operated",
        "<strong>(E)</strong> Narrow aisles and other restricted places",
        "<strong>(F)</strong> Hazardous (classified) locations where the vehicle will be operated",
      ] },
      { type: "heading", level: 3, text: "Topics G-I: Ramps, Ventilation, and Conditions" },
      { type: "list", items: [
        "<strong>(G)</strong> Ramps and other sloped surfaces that could affect stability",
        "<strong>(H)</strong> Closed environments where insufficient ventilation or poor maintenance could cause buildup of carbon monoxide or diesel exhaust",
        "<strong>(I)</strong> Other unique or potentially hazardous environmental conditions in the workplace",
      ] },
      { type: "heading", level: 3, text: "Teaching Tips for Workplace Topics" },
      { type: "list", items: [
        "Walk through the <strong>actual facility</strong> to show site-specific hazards",
        "Take photos of <strong>specific areas</strong> (ramps, docks, narrow aisles) for training",
        "Review your facility's <strong>traffic patterns and pedestrian zones</strong>",
        "Discuss <strong>actual loads</strong> handled at your facility",
        "Address <strong>ventilation</strong> if operating IC engines indoors",
      ] },
      { type: "key_takeaways", items: [
        "OSHA requires 9 workplace-related topics under 1910.178(l)(3)(ii)",
        "These topics are site-specific and must be customized to your facility",
        "Cover surface conditions, loads, pedestrians, narrow aisles, ramps, and ventilation",
        "Walk through the actual facility during training to show real hazards",
      ] },
    ]),
  },
  {
    module: "Required Topics Deep Dive",
    title: "Knowledge Check: Required Topics",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "How many truck-related topics does OSHA require under 1910.178(l)(3)(i)?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "13", explanation: "OSHA requires 13 truck-related topics (A through M) covering operating instructions, controls, steering, visibility, capacity, stability, inspection, maintenance, and more." },
      { question: "How many workplace-related topics does OSHA require under 1910.178(l)(3)(ii)?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "9", explanation: "OSHA requires 9 workplace-related topics (A through I) covering surface conditions, loads, pedestrians, narrow aisles, ramps, ventilation, and other site-specific hazards." },
      { question: "Workplace-related training topics should be:", type: "mcq_single", options: ["Generic and applicable to any facility", "Customized to your specific facility and hazards", "Memorized from the OSHA standard", "Skipped if operators are experienced"], correctAnswers: "Customized to your specific facility and hazards", explanation: "Workplace-related topics are site-specific and must be tailored to your facility's actual conditions, hazards, and equipment." },
    ],
  },

  // ═══ MODULE 4: Practical Training Methodology ═══
  {
    module: "Practical Training Methodology",
    title: "Conducting Practical Training Sessions",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("warehouse-aisle.svg"), alt: "Conducting Practical Training Sessions" },
      { type: "heading", level: 2, text: "Conducting Practical Training Sessions" },
      { type: "heading", level: 3, text: "Setting Up for Success" },
      { type: "paragraph", html: "Before the practical training session:" },
      { type: "list", items: [
        "Ensure the practice area is <strong>clear of pedestrians and obstacles</strong>",
        "Verify the forklift is in <strong>safe operating condition</strong>",
        "Have all <strong>evaluation checklists</strong> ready",
        "Brief the trainee on what to expect",
        "Review <strong>emergency procedures</strong> before starting",
      ] },
      { type: "heading", level: 3, text: "The Demonstration-Practice-Evaluation Cycle" },
      { type: "list", ordered: true, items: [
        "<strong>Demonstrate</strong> each skill at normal speed, then slowly with explanation",
        "<strong>Guided practice:</strong> trainee performs while you provide step-by-step coaching",
        "<strong>Independent practice:</strong> trainee performs without coaching",
        "<strong>Evaluate:</strong> observe and score against the checklist",
      ] },
      { type: "heading", level: 3, text: "Key Skills to Practice" },
      { type: "list", items: [
        "<strong>Pre-shift inspection</strong> — complete walkaround and functional tests",
        "<strong>Basic driving</strong> — forward, reverse, turning, stopping",
        "<strong>Load handling</strong> — picking up, traveling with, and depositing loads",
        "<strong>Ramp operation</strong> — ascending and descending with/without loads",
        "<strong>Dock operations</strong> — entering trailers, dock plates",
        "<strong>Parking and shutdown</strong> — proper securing procedures",
      ] },
      { type: "heading", level: 3, text: "Safety During Training" },
      { type: "paragraph", html: "As the trainer, you are responsible for safety during training:" },
      { type: "list", items: [
        "Always maintain a <strong>clear escape route</strong> for yourself",
        "Never allow the trainee to perform <strong>dangerous maneuvers</strong>",
        "Stop the exercise immediately if <strong>unsafe behavior</strong> occurs",
        "Keep other personnel <strong>clear of the training area</strong>",
        "Have <strong>emergency contact information</strong> readily available",
      ] },
      { type: "scenario", title: "Trainer Judgment Call",
        prompt: "During guided practice, your trainee picks up a pallet and starts turning with the load raised about five feet off the ground, moving quickly. No one else is nearby. What do you do?",
        choices: [
          { text: "Let them finish the maneuver, then bring it up during the debrief", correct: false, feedback: "Unsafe behavior must be stopped the moment you see it. A raised load in a fast turn is a classic tip-over setup — waiting for the debrief means waiting for an accident." },
          { text: "Stop the exercise immediately, explain why it is unsafe, demonstrate the correct technique, and have them redo it", correct: true, feedback: "Correct. Stop the operation immediately, explain why the behavior is unsafe, demonstrate the correct procedure, and have the trainee redo the operation correctly. Document any recurring issues." },
          { text: "Climb onto the truck and take over the controls to finish the maneuver", correct: false, feedback: "Never approach or mount a moving forklift — that puts you in the danger zone. Signal the trainee to stop, then correct the behavior from a safe position." },
        ] },
      { type: "callout", variant: "warning", text: "As the trainer, you are responsible for safety during practical training. Never allow dangerous maneuvers." },
      { type: "key_takeaways", items: [
        "Use the demonstrate-practice-evaluate cycle for each skill",
        "Practice: inspection, driving, load handling, ramps, docks, parking",
        "Keep the training area clear and maintain emergency readiness",
        "Stop exercises immediately if unsafe behavior occurs",
      ] },
    ]),
  },
  {
    module: "Practical Training Methodology",
    title: "Knowledge Check: Practical Training",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "The recommended training cycle for practical skills is:", type: "mcq_single", options: ["Test first, then teach", "Demonstrate, guided practice, independent practice, evaluate", "Only evaluate at the end", "Let trainees figure it out"], correctAnswers: "Demonstrate, guided practice, independent practice, evaluate", explanation: "The effective cycle is: demonstrate the skill, guide practice, allow independent practice, then evaluate." },
      { question: "If a trainee performs an unsafe maneuver during practice, you should:", type: "mcq_single", options: ["Let them finish and address it later", "Stop the exercise immediately", "Ignore it if no one was hurt", "Only note it on the evaluation form"], correctAnswers: "Stop the exercise immediately", explanation: "Stop unsafe behavior immediately. Safety is the trainer's responsibility during training." },
    ],
  },

  // ═══ MODULE 5: Operator Evaluation ═══
  {
    module: "Operator Evaluation",
    title: "Conducting the Operator Evaluation",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("pre-shift-checklist.svg"), alt: "Conducting the Operator Evaluation" },
      { type: "heading", level: 2, text: "Conducting the Operator Evaluation" },
      { type: "heading", level: 3, text: "Evaluation vs. Training" },
      { type: "paragraph", html: "Training and evaluation are <strong>separate activities</strong>. Training is when you teach and coach. Evaluation is when you <strong>observe and assess</strong> without coaching. The evaluation determines whether the operator is competent to operate independently." },
      { type: "heading", level: 3, text: "Evaluation Checklist Design" },
      { type: "paragraph", html: "Create a standardized evaluation checklist that covers:" },
      { type: "list", items: [
        "<strong>Pre-shift inspection</strong> — completed correctly",
        "<strong>Vehicle startup</strong> — proper sequence and safety checks",
        "<strong>Driving skills</strong> — smooth operation, speed control, turning",
        "<strong>Load handling</strong> — proper pickup, transport, and deposit",
        "<strong>Ramp/dock operations</strong> — safe procedures",
        "<strong>Parking and shutdown</strong> — proper securing",
        "<strong>Safety awareness</strong> — horn use, pedestrian awareness, hazard recognition",
      ] },
      { type: "heading", level: 3, text: "Conducting the Evaluation" },
      { type: "list", ordered: true, items: [
        "Brief the operator on what they will be evaluated on",
        "Explain that this is an <strong>evaluation, not training</strong> — no coaching",
        "Observe and score each item on the checklist",
        "Take notes on specific observations",
        "Debrief after the evaluation — share results",
      ] },
      { type: "heading", level: 3, text: "Pass/Fail Decision Making" },
      { type: "paragraph", html: "Establish clear criteria:" },
      { type: "list", items: [
        "<strong>Pass:</strong> All critical items performed safely, no safety violations",
        "<strong>Conditional pass:</strong> Minor issues that can be corrected with coaching",
        "<strong>Fail:</strong> Any critical safety violation, unsafe operation",
        "<strong>Critical failures</strong> (automatic fail): tipping risk, near-miss with pedestrian, exceeding capacity",
      ] },
      { type: "heading", level: 3, text: "Handling Unsuccessful Evaluations" },
      { type: "paragraph", html: "If an operator fails the evaluation:" },
      { type: "list", items: [
        "Explain <strong>specifically</strong> what was unsafe",
        "Provide <strong>additional training</strong> on the failed areas",
        "Allow <strong>re-evaluation</strong> after remediation",
        "Document the failure, remediation, and re-evaluation",
        "Never allow an operator who failed evaluation to operate independently",
      ] },
      { type: "callout", variant: "tip", text: "Keep evaluation checklists consistent across all operators to ensure fairness and compliance." },
      { type: "key_takeaways", items: [
        "Evaluation is separate from training — observe without coaching",
        "Use a standardized evaluation checklist for all operators",
        "Establish clear pass/fail criteria including critical safety failures",
        "Provide remediation and re-evaluation for operators who fail",
      ] },
    ]),
  },
  {
    module: "Operator Evaluation",
    title: "Knowledge Check: Operator Evaluation",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "During an evaluation, the trainer should:", type: "mcq_single", options: ["Coach the operator through each step", "Observe without coaching", "Take over if the operator struggles", "Skip items the operator already knows"], correctAnswers: "Observe without coaching", explanation: "Evaluation is separate from training. Observe and assess without coaching to determine true competence." },
      { question: "If an operator fails the evaluation, you should:", type: "mcq_single", options: ["Certify them anyway", "Provide additional training and re-evaluate", "Fire the operator", "Ignore the failure"], correctAnswers: "Provide additional training and re-evaluate", explanation: "Provide remediation training on failed areas, then re-evaluate. Document the entire process." },
    ],
  },

  // ═══ MODULE 6: Program Administration & Safety Culture ═══
  {
    module: "Program Administration & Safety Culture",
    title: "Administering Your Training Program",
    type: "lesson",
    estimatedMinutes: 5,
    config: blocks([
      { type: "hero_image", src: img("osha-compliance.svg"), alt: "Administering Your Training Program" },
      { type: "heading", level: 2, text: "Administering Your Training Program" },
      { type: "heading", level: 3, text: "Training Records Management" },
      { type: "paragraph", html: "Maintain organized training records for each operator:" },
      { type: "list", items: [
        "Training date and curriculum covered",
        "Evaluation results and checklist",
        "Certification with trainer identity",
        "Refresher training records",
        "Re-evaluation records (3-year cycle)",
        "Incident/near-miss reports and subsequent retraining",
      ] },
      { type: "heading", level: 3, text: "Refresher Training Triggers (1910.178(l)(4))" },
      { type: "paragraph", html: "Refresher training is required when:" },
      { type: "list", items: [
        "The operator is <strong>observed operating unsafely</strong>",
        "The operator is <strong>involved in an accident or near-miss</strong>",
        "The operator receives an <strong>evaluation revealing unsafe operation</strong>",
        "The operator is <strong>assigned to a different type of truck</strong>",
        "A <strong>workplace condition changes</strong> affecting safe operation",
      ] },
      { type: "paragraph", html: "Plus, evaluation at least every <strong>3 years</strong>." },
      { type: "drag_drop", mode: "matching",
        prompt: "Match each situation to the refresher-training trigger it represents.",
        items: [
          { id: "sit-speeding", label: "An operator is seen speeding through a blind intersection without sounding the horn", targetId: "trig-unsafe" },
          { id: "sit-rack", label: "An operator clips a rack upright while backing out of an aisle", targetId: "trig-accident" },
          { id: "sit-reach", label: "A sit-down counterbalance operator is assigned to a stand-up reach truck", targetId: "trig-newtruck" },
          { id: "sit-ramp", label: "A new ramp is installed between the warehouse and the yard", targetId: "trig-workplace" },
        ],
        targets: [
          { id: "trig-unsafe", label: "Observed operating unsafely" },
          { id: "trig-accident", label: "Accident or near-miss" },
          { id: "trig-newtruck", label: "Assigned to a different type of truck" },
          { id: "trig-workplace", label: "Workplace condition change" },
        ] },
      { type: "heading", level: 3, text: "Managing New Equipment" },
      { type: "paragraph", html: "When new equipment is introduced:" },
      { type: "list", items: [
        "Provide <strong>equipment-specific training</strong> before allowing operation",
        "Review the <strong>operator's manual</strong> for the new equipment",
        "Conduct <strong>familiarization training</strong> on controls and differences",
        "Evaluate operators on the new equipment before certifying",
        "Update training records",
      ] },
      { type: "heading", level: 3, text: "Continuous Improvement" },
      { type: "paragraph", html: "Regularly review and improve your training program:" },
      { type: "list", items: [
        "Review <strong>accident and near-miss data</strong> for trends",
        "Update training materials when <strong>regulations change</strong>",
        "Solicit <strong>feedback from trainees</strong>",
        "Stay current with <strong>OSHA updates and interpretations</strong>",
        "Conduct <strong>self-audits</strong> of your training records",
      ] },
      { type: "key_takeaways", items: [
        "Maintain detailed training records for every operator",
        "Refresher training is triggered by unsafe operation, accidents, new equipment, or workplace changes",
        "Provide equipment-specific training when introducing new trucks",
        "Continuously improve your program based on data and feedback",
      ] },
    ]),
  },
  {
    module: "Program Administration & Safety Culture",
    title: "Building a Safety Culture",
    type: "lesson",
    estimatedMinutes: 4,
    config: blocks([
      { type: "hero_image", src: img("pedestrian-safety.svg"), alt: "Building a Safety Culture" },
      { type: "heading", level: 2, text: "Building a Safety Culture" },
      { type: "heading", level: 3, text: "The Trainer's Role in Safety Culture" },
      { type: "paragraph", html: "As a forklift trainer, you are a <strong>safety leader</strong> in your organization. Your attitude, behavior, and commitment to safety set the tone for all operators. Lead by example — always follow safe practices yourself." },
      { type: "heading", level: 3, text: "Promoting 'Safety First' Mindset" },
      { type: "list", items: [
        "Encourage operators to <strong>stop work</strong> if they feel unsafe",
        "Reward <strong>reporting of hazards and near-misses</strong>",
        "Never pressure operators to <strong>rush at the expense of safety</strong>",
        "Make safety a <strong>regular topic</strong> in team meetings",
        "Recognize and praise <strong>safe behaviors</strong>",
      ] },
      { type: "heading", level: 3, text: "Management Commitment" },
      { type: "paragraph", html: "A safety culture requires <strong>management commitment</strong>. As a trainer, advocate for:" },
      { type: "list", items: [
        "Adequate <strong>training time and resources</strong>",
        "Proper <strong>equipment maintenance</strong>",
        "Enforcement of <strong>safety rules</strong> consistently",
        "Investigation of all <strong>accidents and near-misses</strong>",
        "Regular <strong>safety audits and inspections</strong>",
      ] },
      { type: "heading", level: 3, text: "Safety as an Ongoing Process" },
      { type: "paragraph", html: "Safety is not a one-time event — it's an <strong>ongoing process</strong>. Regular reinforcement, refresher training, and open communication about safety are essential. A strong safety culture reduces accidents, improves productivity, and protects your most valuable asset: your people." },
      { type: "callout", variant: "tip", text: "Start each shift with a 2-minute safety briefing. It keeps safety top of mind." },
      { type: "key_takeaways", items: [
        "The trainer is a safety leader — lead by example",
        "Encourage a 'stop work' policy for unsafe conditions",
        "Advocate for management commitment to safety",
        "Safety is an ongoing process, not a one-time event",
      ] },
    ]),
  },
  {
    module: "Program Administration & Safety Culture",
    title: "Knowledge Check: Administration & Culture",
    type: "checkpoint",
    estimatedMinutes: 2,
    config: { passing_score: 0, max_attempts: 999 },
    questions: [
      { question: "Refresher training is required when (select the best answer):", type: "mcq_single", options: ["Only every 3 years", "When the operator is observed operating unsafely", "Only when OSHA requests it", "Only when new equipment is purchased"], correctAnswers: "When the operator is observed operating unsafely", explanation: "Refresher training is required for unsafe operation, accidents/near-misses, failed evaluations, new equipment types, or workplace condition changes — plus evaluation every 3 years." },
      { question: "As a trainer, your role in safety culture is to:", type: "mcq_single", options: ["Just teach the material and move on", "Lead by example and be a safety leader", "Enforce rules but not follow them yourself", "Only report to management"], correctAnswers: "Lead by example and be a safety leader", explanation: "The trainer is a safety leader who sets the tone. Always follow safe practices yourself and promote a safety-first mindset." },
    ],
  },

  // ═══ MODULE 7: Final Exam & Completion ═══
  {
    module: "Final Exam & Completion",
    title: "Final Exam: Forklift Train the Trainer Certification",
    type: "exam",
    estimatedMinutes: 15,
    config: { passing_score: 80, max_attempts: 3, randomize_questions: true },
    questions: [
      { question: "What OSHA standard establishes trainer qualifications for forklift training?", type: "mcq_single", options: ["29 CFR 1910.178(l)(2)(iii)", "29 CFR 1926.453", "29 CFR 1910.147", "29 CFR 1926.500"], correctAnswers: "29 CFR 1910.178(l)(2)(iii)", explanation: "29 CFR 1910.178(l)(2)(iii) states that training must be conducted by persons with the knowledge, training, and experience to train operators." },
      { question: "What three qualifications must a forklift trainer possess?", type: "mcq_single", options: ["Degree, certificate, license", "Knowledge, training, and experience", "Age, education, and physical fitness", "Seniority, approval, and tenure"], correctAnswers: "Knowledge, training, and experience", explanation: "OSHA requires trainers to have the knowledge, training, and experience to train operators and evaluate their competence." },
      { question: "What must operator certification include per 1910.178(l)(6)?", type: "mcq_single", options: ["Operator's photo", "Operator name, training date, eval date, trainer identity", "Operator's SSN", "Only the employer's signature"], correctAnswers: "Operator name, training date, eval date, trainer identity", explanation: "Certification must include the operator's name, date of training, date of evaluation, and identity of the trainer/evaluator." },
      { question: "How often must operators be re-evaluated?", type: "mcq_single", options: ["Every year", "Every 2 years", "Every 3 years", "Every 5 years"], correctAnswers: "Every 3 years", explanation: "OSHA requires operator re-evaluation at least every three years." },
      { question: "How many truck-related topics must be covered in operator training?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "13", explanation: "1910.178(l)(3)(i) requires 13 truck-related topics (A through M)." },
      { question: "How many workplace-related topics must be covered?", type: "mcq_single", options: ["5", "9", "13", "22"], correctAnswers: "9", explanation: "1910.178(l)(3)(ii) requires 9 workplace-related topics (A through I)." },
      { question: "Adults learn best when training is:", type: "mcq_single", options: ["Purely theoretical", "Directly relevant to their work", "Memorization-based", "In long lectures"], correctAnswers: "Directly relevant to their work", explanation: "Adults are relevance-oriented — they learn best when content is directly applicable to their job." },
      { question: "The three learning styles are:", type: "mcq_single", options: ["Visual, auditory, kinesthetic", "Reading, writing, arithmetic", "Fast, medium, slow", "Individual, group, online"], correctAnswers: "Visual, auditory, kinesthetic", explanation: "The three main learning styles are visual (seeing), auditory (hearing), and kinesthetic (hands-on)." },
      { question: "Learning objectives should use:", type: "mcq_single", options: ["Vague terms like 'understand'", "Measurable action verbs like 'demonstrate'", "Long paragraphs", "Only the instructor's name"], correctAnswers: "Measurable action verbs like 'demonstrate'", explanation: "Objectives should use measurable action verbs so you can verify the trainee achieved them." },
      { question: "The recommended practical training cycle is:", type: "mcq_single", options: ["Test, teach, test", "Demonstrate, guided practice, independent practice, evaluate", "Lecture only", "Evaluate only"], correctAnswers: "Demonstrate, guided practice, independent practice, evaluate", explanation: "The effective cycle is demonstrate, guide practice, allow independent practice, then evaluate." },
      { question: "During an evaluation, the trainer should:", type: "mcq_single", options: ["Coach through each step", "Observe without coaching", "Take over if struggling", "Skip known items"], correctAnswers: "Observe without coaching", explanation: "Evaluation is separate from training — observe and assess without coaching." },
      { question: "Refresher training is required when:", type: "mcq_single", options: ["Only every 3 years", "The operator is observed operating unsafely", "Only when OSHA visits", "Only for new hires"], correctAnswers: "The operator is observed operating unsafely", explanation: "Refresher training is required for unsafe operation, accidents, failed evaluations, new equipment, or workplace changes." },
      { question: "If an operator fails the practical evaluation:", type: "mcq_single", options: ["Certify them anyway", "Provide additional training and re-evaluate", "Terminate employment", "Ignore the failure"], correctAnswers: "Provide additional training and re-evaluate", explanation: "Provide remediation training on failed areas, then re-evaluate. Document the entire process." },
      { question: "This Train the Trainer course certifies you to:", type: "mcq_single", options: ["Operate any forklift", "Train and evaluate forklift operators", "Inspect forklifts for OSHA", "Sell forklift training materials"], correctAnswers: "Train and evaluate forklift operators", explanation: "Train the Trainer qualifies you to train and evaluate operators. It does NOT certify you to operate equipment — you must already be a competent operator." },
      { question: "Workplace-related training topics should be:", type: "mcq_single", options: ["Generic for any facility", "Customized to your specific facility", "Skipped for experienced operators", "Memorized from OSHA text"], correctAnswers: "Customized to your specific facility", explanation: "Workplace topics are site-specific — they must be tailored to your facility's actual conditions and hazards." },
      { question: "As a trainer, you are a:", type: "mcq_single", options: ["Just a teacher", "Safety leader who leads by example", "Enforcer of rules", "Record keeper only"], correctAnswers: "Safety leader who leads by example", explanation: "The trainer is a safety leader whose attitude and behavior set the tone for all operators." },
      { question: "OSHA can fine employers up to how much per serious violation?", type: "mcq_single", options: ["$1,000", "$5,000", "$15,625", "$100,000"], correctAnswers: "$15,625", explanation: "As of 2023, OSHA fines for serious violations can reach $15,625 per violation, and up to $156,259 for willful or repeated violations." },
      { question: "What is a critical failure that should result in automatic evaluation failure?", type: "mcq_single", options: ["Slow driving", "Tipping risk or near-miss with pedestrian", "Forgetting to honk once", "Parking slightly off-center"], correctAnswers: "Tipping risk or near-miss with pedestrian", explanation: "Critical safety failures like tipping risk, near-misses with pedestrians, or exceeding capacity should result in automatic evaluation failure." },
      { question: "Effective feedback should be:", type: "mcq_single", options: ["Delayed and vague", "Specific, timely, balanced, and actionable", "Only about weaknesses", "Given only at the end of training"], correctAnswers: "Specific, timely, balanced, and actionable", explanation: "Effective feedback is specific, timely, balanced (strengths and weaknesses), and actionable." },
      { question: "Training records should be maintained for:", type: "mcq_single", options: ["30 days", "1 year", "Duration of employment plus 3 years", "Forever"], correctAnswers: "Duration of employment plus 3 years", explanation: "Best practice is to keep training records for employment duration plus 3 years, though OSHA does not specify a retention period." },
    ],
  },
  {
    module: "Final Exam & Completion",
    title: "Congratulations: You're a Certified Trainer",
    type: "lesson",
    estimatedMinutes: 3,
    config: blocks([
      { type: "hero_image", src: img("train-the-trainer-hero.svg"), alt: "You're a Certified Trainer! What's Next" },
      { type: "heading", level: 2, text: "You're a Certified Trainer! What's Next" },
      { type: "heading", level: 3, text: "Your Certification" },
      { type: "paragraph", html: "Congratulations on completing the Forklift Train the Trainer Certification! You are now qualified to <strong>train and evaluate forklift operators</strong> at your facility in accordance with OSHA 29 CFR 1910.178(l)(2)(iii)." },
      { type: "heading", level: 3, text: "Next Steps" },
      { type: "list", items: [
        "Download your trainer certificate",
        "Develop your site-specific training curriculum",
        "Create practical evaluation checklists",
        "Schedule your first operator training session",
        "Maintain your own operator competence",
      ] },
      { type: "heading", level: 3, text: "Stay Current" },
      { type: "paragraph", html: "Continue to develop your skills as a trainer. Stay current with OSHA regulations, attend refresher training, and continuously improve your training program based on feedback and incident data." },
      { type: "callout", variant: "tip", text: "Start with a pilot training session to refine your curriculum before rolling it out to all operators." },
      { type: "key_takeaways", items: [
        "You are now qualified to train and evaluate forklift operators",
        "Develop your site-specific training curriculum and evaluation forms",
        "Maintain your own operator competence",
        "Stay current with OSHA regulations and best practices",
      ] },
    ]),
  },
];
