import type { InsertSeoPage } from "../shared/schema";

export function generateSpanishPriorityPages(): InsertSeoPage[] {
  return [
    {
      slug: "certificacion-de-montacargas-en-linea",
      locale: "es",
      templateKey: "TEMPLATE_COURSE",
      published: true,
      title: "Certificación de Montacargas en Línea — Capacitación Conforme a OSHA | $59.99",
      metaDescription: "Obtén tu certificación de montacargas en línea en tan solo un día. Nuestra capacitación cumple con OSHA 29 CFR 1910.178. Certificado con verificación QR incluido.",
      heroH1: "Certificación de Montacargas en Línea",
      heroSubtitle: "Completa tu capacitación de operador de montacargas conforme a OSHA en línea. Estudia a tu propio ritmo, obtén tu certificado el mismo día.",
      introParagraph: "ForkliftCertified ofrece un programa integral de certificación de montacargas en línea diseñado para cumplir con los requisitos de OSHA 29 CFR 1910.178 para instrucción formal. Nuestro programa cubre todos los temas de capacitación requeridos, incluyendo inspecciones de vehículos, manejo de cargas, principios de estabilidad, seguridad peatonal y peligros en el lugar de trabajo. Al completar, recibes un certificado digital con verificación por código QR que los empleadores pueden confirmar al instante.",
      primaryKeyword: "certificacion de montacargas en linea",
      secondaryKeywords: ["certificacion montacargas online", "capacitacion osha montacargas", "licencia de montacargas en linea"],
      canonicalSlug: "certificacion-de-montacargas-en-linea",
      bodySections: [
        { type: "step_list", heading: "Cómo Funciona", steps: [
          { title: "Crea Tu Cuenta", description: "Regístrate y adquiere el curso de certificación por un pago único de $59.99." },
          { title: "Completa la Capacitación en Línea", description: "Avanza a través de 8 módulos que cubren todos los temas requeridos por OSHA a tu propio ritmo." },
          { title: "Aprueba el Examen Final", description: "Obtén 80% o más en el examen de certificación. Tres intentos incluidos." },
          { title: "Obtén Tu Certificación", description: "Descarga tu certificado inmediatamente. Verificado por QR y listo para el empleador." },
        ]},
        { type: "icon_list", heading: "Qué Incluye", items: [
          "Curso integral de 8 módulos que cubre todos los temas de OSHA 29 CFR 1910.178",
          "Puntos de control interactivos después de cada módulo",
          "Examen final de certificación con hasta 3 intentos",
          "Certificado digital con código QR de verificación único",
          "Paquete de documentación para el empleador (listas de evaluación, formularios de autorización)",
          "Documento de referencia de regulaciones OSHA",
          "Acceso de por vida a los materiales del curso para capacitación de actualización",
        ]},
        { type: "comparison_table", heading: "¿Por Qué Elegir ForkliftCertified?", columns: [
          { label: "Currículo conforme a OSHA", ours: "✓", others: "Varía" },
          { label: "Certificados verificados por QR", ours: "✓", others: "✗" },
          { label: "Kit de documentación para empleador", ours: "✓", others: "✗" },
          { label: "Certificación el mismo día", ours: "✓", others: "3-5 días" },
          { label: "Duración del acceso al curso", ours: "De por vida", others: "30-90 días" },
          { label: "Precio", ours: "$59.99", others: "$80-$150" },
        ]},
        { type: "callout", variant: "info", heading: "Importante: Evaluación del Empleador Requerida", content: "OSHA requiere tres componentes para la certificación de operador: instrucción formal (nuestro curso en línea), capacitación práctica y evaluación. El empleador debe completar la evaluación práctica en su lugar de trabajo. Proporcionamos todas las herramientas de documentación que su empleador necesita." },
      ],
      faqJson: [
        { q: "¿Cuánto tiempo toma la certificación de montacargas en línea?", a: "La mayoría de los estudiantes completan el curso en 4-6 horas, aunque puedes tomarte el tiempo que necesites. Puedes pausar y reanudar en cualquier momento." },
        { q: "¿La certificación en línea cumple con OSHA?", a: "Sí. Nuestro programa de capacitación cubre todos los temas requeridos por la Norma OSHA 29 CFR 1910.178 para el componente de instrucción formal de la certificación de operador." },
        { q: "¿Recibo el certificado inmediatamente?", a: "Sí. Una vez que apruebes el examen final, tu certificado digital está disponible para descarga inmediata. Incluye un código QR único para verificación del empleador." },
        { q: "¿Mi empleador puede verificar mi certificación?", a: "Sí. Cada certificado tiene un código de verificación único y un código QR que enlaza a nuestra página de verificación, donde los empleadores pueden confirmar al instante el estado de tu certificación." },
        { q: "¿Qué pasa si no apruebo el examen?", a: "Tienes hasta 3 intentos para aprobar el examen final con una puntuación del 80% o más. Puedes revisar el material del curso entre intentos." },
        { q: "¿La certificación de montacargas es válida en todos los estados?", a: "OSHA es una agencia federal, por lo que los requisitos de capacitación bajo 29 CFR 1910.178 aplican en todo el país. Algunos estados pueden tener requisitos adicionales." },
      ],
    },
    {
      slug: "costo-certificacion-montacargas",
      locale: "es",
      templateKey: "TEMPLATE_PRICING",
      published: true,
      title: "Costo de Certificación de Montacargas — Programa Completo $59.99 | ForkliftCertified",
      metaDescription: "¿Cuánto cuesta la certificación de montacargas? Nuestra certificación en línea completa conforme a OSHA es $59.99 sin cargos ocultos. Incluye certificado, documentos para empleador y acceso de por vida.",
      heroH1: "¿Cuánto Cuesta la Certificación de Montacargas?",
      heroSubtitle: "Precios transparentes sin cargos ocultos. Todo lo que necesitas por $59.99.",
      introParagraph: "Los costos de certificación de montacargas varían ampliamente dependiendo del proveedor, formato y ubicación. Las clases presenciales típicamente cuestan entre $150-$300, mientras que los programas en línea van de $40-$150. En ForkliftCertified, nuestro programa completo de certificación en línea cuesta $59.99 — un pago único que incluye el curso completo, examen de certificación, certificado digital y kit de documentación para el empleador.",
      primaryKeyword: "costo certificacion montacargas",
      secondaryKeywords: ["cuanto cuesta certificacion montacargas", "precio capacitacion montacargas", "costo licencia montacargas"],
      bodySections: [
        { type: "comparison_table", heading: "Comparación de Costos", columns: [
          { label: "Certificación en línea completa", ours: "$59.99", others: "$80-$150" },
          { label: "Capacitación presencial", ours: "N/A", others: "$150-$300" },
          { label: "Capacitación grupal en sitio", ours: "Descuentos por volumen", others: "$200-$500/persona" },
          { label: "Cargos ocultos de renovación", ours: "Ninguno", others: "Común" },
          { label: "Certificado incluido", ours: "✓ Incluido", others: "Frecuentemente extra" },
        ]},
        { type: "icon_list", heading: "Qué Incluyen Tus $59.99", items: [
          "Curso completo de capacitación de 8 módulos conforme a OSHA",
          "Examen final de certificación (hasta 3 intentos)",
          "Certificado digital con verificación QR",
          "Paquete de documentación para el empleador",
          "Acceso de por vida a los materiales del curso",
          "Sin cargos recurrentes ni cobros ocultos",
        ]},
        { type: "callout", variant: "tip", heading: "Descuentos Grupales Disponibles", content: "¿Capacitando 5 o más operadores? Contáctenos sobre precios por volumen para empresas y programas de capacitación grupal." },
      ],
      faqJson: [
        { q: "¿Por qué el costo de la certificación varía tanto?", a: "Los costos varían según el formato de capacitación (en línea vs. presencial), la reputación del proveedor, los materiales incluidos y la ubicación. Los programas en línea son típicamente menos costosos porque no requieren instalaciones físicas ni instructores." },
        { q: "¿Hay cargos ocultos?", a: "No. Nuestro precio de $59.99 incluye todo: el curso completo de capacitación, examen de certificación, certificado digital y kit de documentación para el empleador. No hay cargos de renovación ni sorpresas." },
        { q: "¿Una certificación más barata es menos legítima?", a: "No necesariamente. Lo que importa es que la capacitación cubra todos los temas requeridos por OSHA. Nuestro programa está diseñado para cumplir con todos los requisitos de 29 CFR 1910.178 a una fracción del costo de la capacitación presencial." },
        { q: "¿Mi empleador paga por la certificación?", a: "Muchos empleadores cubren el costo de la certificación de montacargas como gasto empresarial. OSHA requiere que los empleadores proporcionen capacitación sin costo para los empleados. Consulte con su empleador — pueden reembolsarle o comprar la capacitación directamente." },
      ],
    },
    {
      slug: "certificacion-montacargas-cerca-de-mi",
      locale: "es",
      templateKey: "TEMPLATE_NEAR_ME_HUB",
      published: true,
      title: "Certificación de Montacargas Cerca de Mí — Encuentra Capacitación en Tu Área | ForkliftCertified",
      metaDescription: "Encuentra certificación de montacargas cerca de ti. Capacitación en línea disponible en todo el país más ubicaciones presenciales. Certifícate el mismo día con capacitación conforme a OSHA.",
      heroH1: "Certificación de Montacargas Cerca de Mí",
      heroSubtitle: "Ya sea que prefieras capacitación en línea o presencial, tenemos opciones cerca de ti. Nuestra certificación en línea está disponible en los 50 estados.",
      introParagraph: "¿Buscas certificación de montacargas cerca de ti? ForkliftCertified ofrece capacitación conforme a OSHA accesible desde cualquier lugar. Nuestro programa de certificación en línea te permite completar tu capacitación desde casa o el trabajo, mientras que nuestras ubicaciones presenciales en ciudades selectas ofrecen opciones de capacitación práctica.",
      primaryKeyword: "certificacion montacargas cerca de mi",
      secondaryKeywords: ["capacitacion montacargas cerca de mi", "licencia montacargas cerca de mi", "clases montacargas cerca de mi"],
      bodySections: [
        { type: "icon_list", heading: "Opciones de Capacitación", items: [
          "Certificación en línea disponible en los 50 estados — comienza inmediatamente",
          "Certificación el mismo día al completar el curso",
          "Ubicaciones de capacitación presencial en ciudades selectas",
          "Opciones de capacitación grupal en sitio para empresas",
        ]},
      ],
      faqJson: [
        { q: "¿Necesito encontrar capacitación presencial cerca de mí?", a: "No necesariamente. Nuestra certificación en línea es accesible desde cualquier lugar de EE.UU. y cumple con los mismos requisitos de OSHA que la capacitación presencial para el componente de instrucción formal." },
        { q: "¿Puedo completar la certificación desde casa?", a: "Sí. Nuestro programa de certificación en línea está completamente basado en la web y se puede completar desde cualquier computadora o tablet con conexión a internet." },
        { q: "¿La certificación en línea es válida en mi estado?", a: "Sí. Los requisitos de capacitación de OSHA bajo 29 CFR 1910.178 son estándares federales que aplican en todos los estados." },
      ],
    },
    {
      slug: "verificacion-certificacion-montacargas",
      locale: "es",
      templateKey: "TEMPLATE_KNOWLEDGE_ARTICLE",
      published: true,
      title: "Verificación de Certificación de Montacargas — Verificar Credenciales de Operador | ForkliftCertified",
      metaDescription: "Verifica las credenciales de certificación de operador de montacargas al instante. Usa nuestro sistema de verificación QR para confirmar el estado de certificación de cualquier operador de ForkliftCertified.",
      heroH1: "Verificación de Certificación de Montacargas",
      heroSubtitle: "Verificación instantánea de credenciales de operador de montacargas para empleadores y supervisores.",
      introParagraph: "Los empleadores y supervisores pueden verificar al instante las credenciales de certificación de montacargas de cualquier operador certificado por ForkliftCertified. Cada certificado incluye un código QR único y un número de verificación que se puede usar para confirmar la validez de la certificación, la fecha de finalización y los temas de capacitación cubiertos.",
      primaryKeyword: "verificacion certificacion montacargas",
      secondaryKeywords: ["verificar licencia montacargas", "confirmar certificacion operador", "verificacion qr montacargas"],
      bodySections: [
        { type: "step_list", heading: "Cómo Verificar una Certificación", steps: [
          { title: "Localiza el Código QR", description: "Encuentra el código QR en el certificado de montacargas del operador." },
          { title: "Escanea o Ingresa el Código", description: "Escanea el código QR con tu teléfono o ingresa el número de verificación en nuestra página de verificación." },
          { title: "Revisa los Resultados", description: "Confirma al instante el estado de certificación del operador, fecha de finalización y temas de capacitación cubiertos." },
        ]},
      ],
      faqJson: [
        { q: "¿Cómo verifico una certificación de montacargas?", a: "Escanea el código QR en el certificado del operador o ingresa el número de verificación en nuestra página de verificación en línea." },
        { q: "¿Qué información muestra la verificación?", a: "La verificación confirma el nombre del operador, fecha de certificación, temas de capacitación completados y el estado actual de la certificación." },
        { q: "¿Cuánto tiempo es válida la certificación?", a: "OSHA requiere que los operadores sean re-evaluados al menos cada tres años. La certificación en sí permanece en nuestro sistema indefinidamente para fines de verificación." },
      ],
    },
    {
      slug: "requisitos-osha-montacargas",
      locale: "es",
      templateKey: "TEMPLATE_PILLAR",
      published: true,
      title: "Requisitos OSHA para Montacargas — Guía Completa 29 CFR 1910.178 | ForkliftCertified",
      metaDescription: "Guía completa de requisitos OSHA para operadores de montacargas bajo 29 CFR 1910.178. Obligaciones de capacitación, inspección y cumplimiento para empleadores y operadores.",
      heroH1: "Requisitos OSHA para Montacargas",
      heroSubtitle: "Todo lo que necesitas saber sobre los requisitos de OSHA para operación de montacargas y certificación de operadores.",
      introParagraph: "La Administración de Seguridad y Salud Ocupacional (OSHA) establece requisitos específicos para la operación de montacargas bajo la norma 29 CFR 1910.178. Esta guía cubre todos los aspectos de los requisitos OSHA, incluyendo capacitación de operadores, inspecciones de vehículos, requisitos de evaluación y sanciones por incumplimiento.",
      primaryKeyword: "requisitos osha montacargas",
      secondaryKeywords: ["norma osha montacargas", "29 cfr 1910.178 español", "cumplimiento osha montacargas"],
      bodySections: [
        { type: "icon_list", heading: "Componentes de Capacitación Requeridos por OSHA", items: [
          "Instrucción formal: Capacitación basada en conocimiento (nuestro curso en línea cumple este requisito)",
          "Capacitación práctica: Operación supervisada del montacargas",
          "Evaluación: Demostración de competencia evaluada por persona calificada",
        ]},
        { type: "rich_text", heading: "Temas de Capacitación Requeridos", content: "<p>OSHA 29 CFR 1910.178(l) requiere que la capacitación cubra los siguientes temas según sea aplicable: controles de operación del camión, instrumentación, señales de advertencia, inspecciones pre-operación, operaciones del vehículo, manipulación de cargas, superficies de operación y condiciones de piso, y operación en rampas e inclinaciones.</p>" },
        { type: "callout", variant: "warning", heading: "Sanciones por Incumplimiento", content: "Las violaciones de OSHA relacionadas con montacargas pueden resultar en multas de hasta $16,131 por violación grave y hasta $161,323 por violaciones intencionales o repetidas." },
      ],
      faqJson: [
        { q: "¿Es obligatoria la certificación de montacargas?", a: "Sí. OSHA requiere que todos los operadores de montacargas sean capacitados y certificados antes de operar un vehículo industrial motorizado." },
        { q: "¿Con qué frecuencia se requiere recertificación?", a: "OSHA requiere que los operadores sean re-evaluados al menos cada tres años. También se requiere re-capacitación si el operador tiene un accidente, se observan prácticas inseguras, o cambian las condiciones del lugar de trabajo." },
        { q: "¿Quién puede capacitar operadores de montacargas?", a: "OSHA requiere que la capacitación sea proporcionada por personas que tengan el conocimiento, la capacitación y la experiencia necesarios para capacitar y evaluar a los operadores." },
      ],
    },
    {
      slug: "capacitacion-grupal-montacargas",
      locale: "es",
      templateKey: "TEMPLATE_GROUP_TRAINING",
      published: true,
      title: "Capacitación Grupal de Montacargas para Empresas — Precios por Volumen | ForkliftCertified",
      metaDescription: "Capacitación grupal de montacargas para empresas. Precios por volumen, seguimiento de cumplimiento y soporte dedicado para equipos de 5+ operadores.",
      heroH1: "Capacitación Grupal de Montacargas para Empresas",
      heroSubtitle: "Soluciones de capacitación escalables con precios por volumen y seguimiento de cumplimiento.",
      introParagraph: "ForkliftCertified ofrece programas de capacitación grupal diseñados para empresas con múltiples operadores de montacargas. Nuestras soluciones empresariales incluyen precios por volumen, panel de seguimiento de cumplimiento, informes de progreso y soporte dedicado de cuenta.",
      primaryKeyword: "capacitacion grupal montacargas",
      secondaryKeywords: ["capacitacion empresarial montacargas", "descuento volumen montacargas", "certificacion grupal montacargas"],
      bodySections: [
        { type: "icon_list", heading: "Beneficios Empresariales", items: [
          "Precios por volumen para 5+ operadores",
          "Panel de seguimiento de cumplimiento del equipo",
          "Informes de progreso y finalización",
          "Soporte dedicado de cuenta",
          "Opciones de facturación empresarial",
          "Documentación de auditoría lista para OSHA",
        ]},
      ],
      faqJson: [
        { q: "¿Cuántos operadores necesitamos para el precio grupal?", a: "Nuestros precios grupales comienzan con un mínimo de 5 operadores. Contáctenos para una cotización personalizada basada en el tamaño de su equipo." },
        { q: "¿Podemos rastrear el progreso de nuestro equipo?", a: "Sí. Nuestro panel empresarial le permite rastrear el estado de capacitación, fechas de certificación y fechas de renovación de todos los operadores de su equipo." },
      ],
    },
    {
      slug: "capacitacion-montacargas-en-sitio",
      locale: "es",
      templateKey: "TEMPLATE_GUIDE",
      published: true,
      title: "Capacitación de Montacargas en Sitio — Entrenamiento en Su Empresa | ForkliftCertified",
      metaDescription: "Solicite capacitación de montacargas en sitio para su empresa. Instrucción práctica y teórica en sus instalaciones con certificación conforme a OSHA.",
      heroH1: "Capacitación de Montacargas en Sitio",
      heroSubtitle: "Lleve la capacitación certificada directamente a sus instalaciones. Ideal para empresas con múltiples operadores.",
      introParagraph: "ForkliftCertified ofrece servicios de capacitación en sitio donde nuestros instructores certificados visitan sus instalaciones para proporcionar capacitación práctica y teórica conforme a OSHA. Esta opción es ideal para empresas que necesitan certificar múltiples operadores sin interrumpir las operaciones.",
      primaryKeyword: "capacitacion montacargas en sitio",
      secondaryKeywords: ["entrenamiento montacargas en empresa", "capacitacion presencial montacargas", "instructor montacargas en sitio"],
      bodySections: [
        { type: "icon_list", heading: "Ventajas de la Capacitación en Sitio", items: [
          "Instrucción personalizada en sus propias instalaciones y equipos",
          "Horarios flexibles que minimizan la interrupción de operaciones",
          "Evaluación práctica con los montacargas de su empresa",
          "Documentación completa de cumplimiento OSHA",
          "Precios grupales competitivos",
        ]},
        { type: "step_list", heading: "Cómo Solicitar Capacitación en Sitio", steps: [
          { title: "Solicite una Cotización", description: "Complete nuestro formulario de solicitud con la cantidad de operadores y tipo de montacargas." },
          { title: "Programación", description: "Coordinamos la fecha y hora que mejor se adapte a su operación." },
          { title: "Capacitación", description: "Nuestro instructor certificado llega a sus instalaciones y conduce la capacitación teórica y práctica." },
          { title: "Certificación", description: "Los operadores aprobados reciben su certificado digital con verificación QR." },
        ]},
      ],
      faqJson: [
        { q: "¿Cuántos operadores se requieren para capacitación en sitio?", a: "Recomendamos un mínimo de 5 operadores para hacer la capacitación en sitio costo-efectiva. Contáctenos para grupos más pequeños." },
        { q: "¿Qué áreas cubren para capacitación en sitio?", a: "Ofrecemos capacitación en sitio en California, Nevada y áreas circundantes. Contáctenos para verificar la disponibilidad en su ubicación." },
      ],
    },
    {
      slug: "tarjeta-billetera-montacargas",
      locale: "es",
      templateKey: "TEMPLATE_KNOWLEDGE_ARTICLE",
      published: true,
      title: "Tarjeta de Billetera de Certificación de Montacargas — Reemplazo y Solicitud | ForkliftCertified",
      metaDescription: "Solicita tu tarjeta de billetera de certificación de montacargas. Tarjeta laminada resistente con código QR de verificación. Reemplazo disponible para tarjetas perdidas o dañadas.",
      heroH1: "Tarjeta de Billetera de Certificación de Montacargas",
      heroSubtitle: "Lleva tu certificación siempre contigo con nuestra tarjeta de billetera profesional.",
      introParagraph: "La tarjeta de billetera de certificación de montacargas de ForkliftCertified es una credencial física laminada que puedes llevar contigo en todo momento. Incluye tu nombre, número de certificación, fecha de emisión y un código QR para verificación instantánea por parte de empleadores e inspectores.",
      primaryKeyword: "tarjeta billetera certificacion montacargas",
      secondaryKeywords: ["tarjeta operador montacargas", "reemplazo tarjeta montacargas", "credencial montacargas"],
      bodySections: [
        { type: "icon_list", heading: "Características de la Tarjeta", items: [
          "Tarjeta PVC laminada de alta durabilidad",
          "Código QR de verificación instantánea",
          "Nombre completo y número de certificación",
          "Fecha de emisión y vigencia",
          "Diseño profesional con logo de ForkliftCertified",
        ]},
      ],
      faqJson: [
        { q: "¿Cómo solicito mi tarjeta de billetera?", a: "Puedes solicitar tu tarjeta de billetera durante el proceso de certificación o después desde tu panel de usuario. Tiene un costo adicional de $14.99 con envío incluido." },
        { q: "¿Puedo solicitar un reemplazo si pierdo mi tarjeta?", a: "Sí. Puedes solicitar una tarjeta de reemplazo en cualquier momento desde tu panel de usuario por $14.99." },
        { q: "¿La tarjeta de billetera es obligatoria?", a: "No. Tu certificado digital es suficiente para demostrar tu certificación. La tarjeta de billetera es una conveniencia adicional para llevar tu credencial en persona." },
      ],
    },
  ];
}


export function getAllSpanishSeoPages(): InsertSeoPage[] {
  return generateSpanishPriorityPages();
}
